// 状态管理统一导出

// 游戏全局状态
export {
  gamePhase,
  gameSeed,
  gameTime,
  isPlaying,
  type GamePhase,
} from './gameSignals';

// 玩家状态
export {
  player,
  isPlayerCreated,
  playerLevel,
  playerHp,
  playerMp,
  playerMaxHp,
  playerMaxMp,
  playerHpPercent,
  playerMpPercent,
  playerGold,
  playerExp,
  playerPosition,
  createPlayer,
  updatePlayerHp,
  updatePlayerMp,
  updatePlayerGold,
  updatePlayerPosition,
  addPlayerExp,
  // 属性点系统
  allocateAttributePoint,
  deallocateAttributePoint,
  resetAttributePoints,
  calculateResetCost,
  playerAttributePoints,
  playerAllocatedPoints,
} from './playerSignals';

// 伙伴状态
export {
  companions,
  activeCompanions,
  activeBonds,
  bondBonuses,
  unlockCompanion,
  setCompanionActive,
  increaseFavorability,
  getCompanion,
  canUnlockCompanion,
} from './companionSignals';

// 战斗状态
export {
  battleState,
  isInBattle as isBattleActive,
  currentRound,
  battleSpeed,
  isAutoBattle,
  currentActorIndex,
  playerFormation,
  enemies,
  actionQueue,
  isBattleEnded,
  battleResult,
  startBattle,
  executeAction,
  endBattle,
  clearBattle,
  isSkillUsable,
  getSkillCooldown,
} from './battleSignals';

// UI状态
export {
  currentPage,
  showSidebar,
  isLoading,
  loadingText,
  toastMessage,
  toastType,
  showModal,
  modalContent,
  navigateTo,
  toggleSidebar,
  closeSidebar,
  showLoading,
  hideLoading,
  showToast,
  showSuccess,
  showError,
  showConfirm,
  closeModal,
  confirmModal,
  cancelModal,
  type Page,
} from './uiSignals';

// 背包状态
export {
  inventoryItems,
  inventoryEquipments,
  equippedSlots,
  maxInventorySlots,
  itemCount,
  equipmentCount,
  isInventoryFull,
  addItem,
  removeItem,
  addEquipment,
  removeEquipment,
  equipItem,
  unequipItem,
  getEquipmentStats,
  clearInventory,
  // 词条锁定状态
  affixLockStates,
  selectedEquipmentForReforge,
  getLockedAffixIndices,
  toggleAffixLock,
  lockAffix,
  unlockAffix,
  unlockAllAffixes,
  clearAffixLockState,
  isAffixLocked,
  getLockedAffixCount,
  setSelectedEquipmentForReforge,
} from './inventorySignals';

// 宠物状态
export {
  playerPets,
  activePet,
  petCount,
  maxPets,
  createPet,
  addPet,
  removePet,
  setActivePet,
  unsetActivePet,
  addPetExp,
  restorePet,
  renamePet,
  clearPets,
} from './petSignals';

// 修炼状态
export {
  cultivationData as cultivation,
  activeCultivationType,
  isAutoCultivating,
  currentRealm,
  currentRealmName,
  totalCultivationLevel,
  cultivationBonus,
  realmBonusMultiplier,
  canBreakthrough,
  realmInfo,
  activeCultivationProgress,
  initCultivation,
  setActiveCultivationType,
  startAutoCultivation,
  stopAutoCultivation,
  gainCultivationExp,
  useCultivationPill,
  attemptBreakthrough,
  processOfflineCultivation,
  resetCultivation,
  getCultivationProgress,
  getProgressPercent,
  updateLastCultivateTime,
} from './cultivationSignals';

// 阵法状态
export {
  playerFormations,
  activeFormationId,
  isFormationInitialized,
  activeFormation,
  activeFormationLevel,
  unlockedFormationCount,
  getPlayerFormation,
  isFormationUnlocked,
  unlockFormation,
  setActiveFormation,
  addFormationExp,
  getActiveFormationEffects,
  getActiveCounterBonus,
  initializeFormations,
  resetFormations,
  getAllFormationStatus,
} from './formationSignals';

// 成就状态
export {
  achievementProgress,
  achievementStats,
  achievementTracker,
  playerTitles,
  activeTitle as activePlayerTitle,
  isAchievementInitialized,
  selectedAchievementCategory,
  newlyUnlockedAchievements,
  isAchievementLoading,
  filteredAchievementProgress,
  unlockedAchievementCount,
  totalAchievementCount,
  earnedAchievementPoints,
  claimableRewardCount,
  initAchievements,
  refreshAchievements,
  triggerAchievementEvent,
  claimAchievementReward,
  activatePlayerTitle,
  deactivatePlayerTitle,
  setSelectedAchievementCategory,
  clearNewlyUnlockedAchievements,
  removeNewlyUnlockedAchievement,
  resetAchievementState,
  getAchievementProgressInfo,
  triggerMultipleAchievementEvents,
  updateLevelAchievement,
  updateKillAchievement,
  updateDungeonAchievement,
  updateEquipmentAchievement,
  updateMapExploration,
  updateFavorabilityAchievement,
  updateBattleWinAchievement,
  updateDamageAchievement,
  getCategoryName,
  getCategoryIcon,
} from './achievementSignals';
