// 状态管理统一导出

// 游戏全局状态
export {
  gamePhase,
  gameSeed,
  gameTime,
  isPlaying,
  type GamePhase,
} from './gameSignals';

// 玩家状态
export {
  player,
  isPlayerCreated,
  playerLevel,
  playerHp,
  playerMp,
  playerMaxHp,
  playerMaxMp,
  playerHpPercent,
  playerMpPercent,
  playerGold,
  playerExp,
  playerPosition,
  createPlayer,
  updatePlayerHp,
  updatePlayerMp,
  updatePlayerGold,
  updatePlayerPosition,
  addPlayerExp,
  // 属性点系统
  allocateAttributePoint,
  deallocateAttributePoint,
  resetAttributePoints,
  calculateResetCost,
  playerAttributePoints,
  playerAllocatedPoints,
} from './playerSignals';

// 伙伴状态
export {
  companions,
  activeCompanions,
  activeBonds,
  bondBonuses,
  unlockCompanion,
  setCompanionActive,
  increaseFavorability,
  getCompanion,
  canUnlockCompanion,
  checkCompanionUnlockByCondition,
  checkLevelUnlockCompanion,
  checkDungeonUnlockCompanion,
  checkStoryUnlockCompanion,
  getUnlockableCompanions,
} from './companionSignals';

// 战斗状态
export {
  battleState,
  isInBattle as isBattleActive,
  currentRound,
  battleSpeed,
  isAutoBattle,
  currentActorIndex,
  playerFormation,
  enemies,
  actionQueue,
  isBattleEnded,
  battleResult,
  startBattle,
  executeAction,
  endBattle,
  clearBattle,
  isSkillUsable,
  getSkillCooldown,
  // 宠物捕捉
  canCaptureEnemy,
  getCaptureRate,
  // 自动战斗配置
  autoBattleConfig,
  updateCharacterAutoConfig,
  updatePetAutoConfig,
  resetAutoBattleConfig,
  // 伙伴AI配置
  companionAIConfigs,
  getCompanionAIConfig,
  updateCompanionAIConfig,
  resetCompanionAIConfig,
} from './battleSignals';

// UI状态
export {
  currentPage,
  showSidebar,
  isLoading,
  loadingText,
  toastMessage,
  toastType,
  showModal,
  modalContent,
  navigateTo,
  toggleSidebar,
  closeSidebar,
  showLoading,
  hideLoading,
  showToast,
  showSuccess,
  showError,
  showConfirm,
  closeModal,
  confirmModal,
  cancelModal,
  type Page,
} from './uiSignals';

// 背包状态
export {
  inventoryItems,
  inventoryEquipments,
  equippedSlots,
  maxInventorySlots,
  itemCount,
  equipmentCount,
  isInventoryFull,
  addItem,
  removeItem,
  useItem,
  hasItem,
  addEquipment,
  removeEquipment,
  equipItem,
  unequipItem,
  getEquipmentStats,
  clearInventory,
  // 词条锁定状态
  affixLockStates,
  selectedEquipmentForReforge,
  getLockedAffixIndices,
  toggleAffixLock,
  lockAffix,
  unlockAffix,
  unlockAllAffixes,
  clearAffixLockState,
  isAffixLocked,
  getLockedAffixCount,
  setSelectedEquipmentForReforge,
} from './inventorySignals';

// 宠物状态
export {
  playerPets,
  activePet,
  petCount,
  maxPets,
  createPet,
  addPet,
  removePet,
  setActivePet,
  unsetActivePet,
  addPetExp,
  restorePet,
  renamePet,
  clearPets,
} from './petSignals';

// 修炼状态
export {
  cultivationData as cultivation,
  activeCultivationType,
  isAutoCultivating,
  currentRealm,
  currentRealmName,
  totalCultivationLevel,
  cultivationBonus,
  realmBonusMultiplier,
  canBreakthrough,
  realmInfo,
  activeCultivationProgress,
  initCultivation,
  setActiveCultivationType,
  startAutoCultivation,
  stopAutoCultivation,
  gainCultivationExp,
  useCultivationPill,
  attemptBreakthrough,
  processOfflineCultivation,
  resetCultivation,
  getCultivationProgress,
  getProgressPercent,
  updateLastCultivateTime,
} from './cultivationSignals';

// 阵法状态
export {
  playerFormations,
  activeFormationId,
  isFormationInitialized,
  activeFormation,
  activeFormationLevel,
  unlockedFormationCount,
  getPlayerFormation,
  isFormationUnlocked,
  unlockFormation,
  setActiveFormation,
  addFormationExp,
  getActiveFormationEffects,
  getActiveCounterBonus,
  initializeFormations,
  resetFormations,
  getAllFormationStatus,
} from './formationSignals';

// 成就状态
export {
  achievementProgress,
  achievementStats,
  achievementTracker,
  playerTitles,
  activeTitle as activePlayerTitle,
  isAchievementInitialized,
  selectedAchievementCategory,
  newlyUnlockedAchievements,
  isAchievementLoading,
  filteredAchievementProgress,
  unlockedAchievementCount,
  totalAchievementCount,
  earnedAchievementPoints,
  claimableRewardCount,
  initAchievements,
  refreshAchievements,
  triggerAchievementEvent,
  claimAchievementReward,
  activatePlayerTitle,
  deactivatePlayerTitle,
  setSelectedAchievementCategory,
  clearNewlyUnlockedAchievements,
  removeNewlyUnlockedAchievement,
  resetAchievementState,
  getAchievementProgressInfo,
  triggerMultipleAchievementEvents,
  updateLevelAchievement,
  updateKillAchievement,
  updateDungeonAchievement,
  updateEquipmentAchievement,
  updateMapExploration,
  updateFavorabilityAchievement,
  updateBattleWinAchievement,
  updateDamageAchievement,
  getCategoryName,
  getCategoryIcon,
} from './achievementSignals';

// 任务状态
export {
  questProgress,
  questStats,
  questTracker,
  isQuestInitialized,
  selectedQuestType,
  selectedQuestId,
  currentDialog,
  currentDialogIndex,
  isQuestLoading,
  newlyCompletedQuests,
  filteredQuestProgress,
  activeQuests,
  availableQuests,
  claimableQuests,
  mainQuestProgress,
  selectedQuestDetail,
  isDialogActive,
  currentDialogLine,
  initQuests,
  refreshQuests,
  acceptQuest,
  completeQuest,
  claimQuestReward,
  triggerQuestEvent,
  showQuestDialog,
  advanceDialog,
  closeDialog,
  setSelectedQuestType,
  setSelectedQuestId,
  clearNewlyCompletedQuests,
  removeNewlyCompletedQuest,
  resetQuestState,
  getQuestProgressInfo,
  updateKillQuestEvent,
  updateItemCollectEvent,
  updateNpcTalkEvent,
  updateMapVisitEvent,
  updateEquipEvent,
  updateLevelQuestEvent,
  updateBattleWinEvent,
  getQuestTypeName,
  getQuestTypeIcon,
  getChapterName,
} from './questSignals';

// 挂机战斗状态
export {
  autoBattleEnabled,
  autoBattleStatus,
  autoBattleSettings,
  autoBattleStats,
  canAutoBattle,
  autoBattleRunTime,
  formatRunTime,
  startAutoBattle,
  stopAutoBattle,
  pauseAutoBattle,
  resumeAutoBattle,
  toggleAutoBattle,
  updateAutoBattleSettings,
  resetAutoBattleStats,
  attackMonsterImmediately,
  getCurrentMapMonsters,
  type AutoBattleStatus,
  type AutoBattleSettings,
  type AutoBattleStats,
} from './autoBattleSignals';

// 副本状态
export {
  // 状态
  dungeonRunState,
  dungeonProgressList,
  isInDungeon,
  currentDungeonId,
  currentDungeonDifficulty,
  currentFloor,
  isDungeonBattle,
  currentDungeon,
  isBossFloor,
  dungeonProgressPercent,
  isDungeonInitialized,
  // 初始化
  initDungeons,
  // 副本操作
  enterDungeon,
  advanceDungeonFloor,
  completeDungeon,
  failDungeon,
  exitDungeon,
  refreshDungeonProgress,
  // 检查函数
  canEnterDungeon,
  getDungeonProgress,
  getDungeonRemainingRuns,
  hasFirstClear,
  // 战斗回调
  onDungeonBattleWin,
  onDungeonBattleLose,
  // 辅助函数
  updateDungeonStats,
  getDifficultyName,
  getDifficultyColor,
  getDungeonTypeName,
  // 类型
  type EnterDungeonResult,
} from './dungeonSignals';
