/**
 * 地图数据 - 从 xiyou/assets/data/config/map_info.json 迁移
 * 95 个地图文件
 */

/** 地图信息 */
export interface MigratedMap {
  id: string;
  fileName: string;
  name: string;
  area?: string;
}

/** 地图名称映射 */
export const MAP_NAME_MAPPING: Record<string, string> = {
  alg: '阿罗国',
  bfg: '白虎峰',
  bgd: '白骨洞',
  bglm: '白骨陵墓',
  bhmj: '百花迷境',
  bjd: '芭蕉洞',
  bjt: '冰晶塔',
  bl: '碧龙',
  bmy: '白马银',
  bqg: '七宫殿',
  bxg: '冰峡谷',
  byd: '白云洞',
  byzzl: '白云庄之路',
  cac: '长安城',
  ccg: '长城观',
  cwd: '宠物店',
  cys: '朝阳山',
  df: '东方府',
  dy18: '地狱十八层',
  dyj: '大雁塔',
  dyt: '大雁塔',
  emgc: '峨眉观',
  fcs: '方寸山',
  fxq: '风云区',
  gczc: '古城战场',
  ghl: '鬼火林',
  gjz: '将军府',
  gzai: '广州爱',
  hd: '海底',
  hdml: '海底迷宫',
  hdmlsc: '海底迷宫深处',
  hsl: '华山',
  hy: '汉阳',
  hz: '杭州',
  jdd: '解刀洞',
  jds: '金顶山',
  jjd: '将军殿',
  jjg: '金刚宫',
  jjl: '将军岭',
  jpf: '金瓶儿',
  jsg: '金山宫',
  jsh: '金山后',
  jt: '祭坛',
  kfgc: '开封府',
  lg: '龙宫',
  lhd: '龙虎洞',
  lht01: '龙王殿',
  ljl: '龙脊岭',
  mapid: '地图中心',
  maptop: '地图顶层',
  mz: '梅庄',
  neg: '南国',
  pds: '普陀山',
  psd: '菩提寺',
  psdd: '菩提殿',
  pts: '普陀寺',
  pty: '普陀崖',
  qls: '麒麟山',
  scl: '三轮',
  sl: '水帘洞',
  std: '狮驼岭',
  tfg: '天王府',
  tg: '天宫',
  tl: '天牢',
  ttsf: '通天水府',
  ttt: '天台',
  tzg: '天尊宫',
  vip1qy: 'VIP一区',
  vip2qy: 'VIP二区',
  vip3qy: 'VIP三区',
  vip4qy: 'VIP四区',
  vipqy: 'VIP区',
  wdd: '无底洞',
  wjg: '武馆',
  wsc: '五庄观',
  wxz01: '五行阵',
  xgt: '仙宫殿',
  xl: '雪岭',
  xlys: '西梁玉山',
  xsc: '雪山城',
  xsmg: '雪山迷宫',
  xyj: '西游界',
  xyt: '仙云台',
  yc: '银川',
  yg: '月光',
  ygd: '月光殿',
  yh: '月湖',
  yhq: '月湖区',
  yld: '月亮洞',
  yls: '月灵山',
  zgz: '中观庄',
  zyt: '镇妖塔',
  zzbl: '紫竹林',
  zzg: '紫竹观',
  zzl: '紫竹林',
};

/** 迁移后的地图数据 */
export const MIGRATED_MAPS: MigratedMap[] = [
  { id: 'xiyou-map-0001', fileName: 'alg.php', name: '阿罗国' },
  { id: 'xiyou-map-0002', fileName: 'bfg.php', name: '白虎峰' },
  { id: 'xiyou-map-0003', fileName: 'bgd.php', name: '白骨洞' },
  { id: 'xiyou-map-0004', fileName: 'bglm.php', name: '白骨陵墓' },
  { id: 'xiyou-map-0005', fileName: 'bhmj.php', name: '百花迷境' },
  { id: 'xiyou-map-0006', fileName: 'bjd.php', name: '芭蕉洞' },
  { id: 'xiyou-map-0007', fileName: 'bjt.php', name: '冰晶塔' },
  { id: 'xiyou-map-0008', fileName: 'bl.php', name: '碧龙' },
  { id: 'xiyou-map-0009', fileName: 'bmy.php', name: '白马银' },
  { id: 'xiyou-map-0010', fileName: 'bqg.php', name: '七宫殿' },
  { id: 'xiyou-map-0011', fileName: 'bxg.php', name: '冰峡谷' },
  { id: 'xiyou-map-0012', fileName: 'byd.php', name: '白云洞' },
  { id: 'xiyou-map-0013', fileName: 'byzzl.php', name: '白云庄之路' },
  { id: 'xiyou-map-0014', fileName: 'cac.php', name: '长安城' },
  { id: 'xiyou-map-0015', fileName: 'ccg.php', name: '长城观' },
  { id: 'xiyou-map-0016', fileName: 'cwd.php', name: '宠物店' },
  { id: 'xiyou-map-0017', fileName: 'cys.php', name: '朝阳山' },
  { id: 'xiyou-map-0018', fileName: 'df.php', name: '东方府' },
  { id: 'xiyou-map-0019', fileName: 'dy18.php', name: '地狱十八层' },
  { id: 'xiyou-map-0020', fileName: 'dyj.php', name: '大雁塔' },
  { id: 'xiyou-map-0021', fileName: 'dyt.php', name: '大雁塔' },
  { id: 'xiyou-map-0022', fileName: 'emgc.php', name: '峨眉观' },
  { id: 'xiyou-map-0023', fileName: 'fcs.php', name: '方寸山' },
  { id: 'xiyou-map-0024', fileName: 'fxq.php', name: '风云区' },
  { id: 'xiyou-map-0025', fileName: 'gczc.php', name: '古城战场' },
  { id: 'xiyou-map-0026', fileName: 'ghl.php', name: '鬼火林' },
  { id: 'xiyou-map-0027', fileName: 'gjz.php', name: '将军府' },
  { id: 'xiyou-map-0028', fileName: 'gzai.php', name: '广州爱' },
  { id: 'xiyou-map-0029', fileName: 'hd.php', name: '海底' },
  { id: 'xiyou-map-0030', fileName: 'hdml.php', name: '海底迷宫' },
  { id: 'xiyou-map-0031', fileName: 'hdmlsc.php', name: '海底迷宫深处' },
  { id: 'xiyou-map-0032', fileName: 'hsl.php', name: '华山' },
  { id: 'xiyou-map-0033', fileName: 'hy.php', name: '汉阳' },
  { id: 'xiyou-map-0034', fileName: 'hz.php', name: '杭州' },
  { id: 'xiyou-map-0035', fileName: 'jdd.php', name: '解刀洞' },
  { id: 'xiyou-map-0036', fileName: 'jds.php', name: '金顶山' },
  { id: 'xiyou-map-0037', fileName: 'jjd.php', name: '将军殿' },
  { id: 'xiyou-map-0038', fileName: 'jjg.php', name: '金刚宫' },
  { id: 'xiyou-map-0039', fileName: 'jjl.php', name: '将军岭' },
  { id: 'xiyou-map-0040', fileName: 'jpf.php', name: '金瓶儿' },
  { id: 'xiyou-map-0041', fileName: 'jsg.php', name: '金山宫' },
  { id: 'xiyou-map-0042', fileName: 'jsh.php', name: '金山后' },
  { id: 'xiyou-map-0043', fileName: 'jt.php', name: '祭坛' },
  { id: 'xiyou-map-0044', fileName: 'kfgc.php', name: '开封府' },
  { id: 'xiyou-map-0045', fileName: 'lg.php', name: '龙宫' },
  { id: 'xiyou-map-0046', fileName: 'lhd.php', name: '龙虎洞' },
  { id: 'xiyou-map-0047', fileName: 'lht01.php', name: '龙王殿' },
  { id: 'xiyou-map-0048', fileName: 'ljl.php', name: '龙脊岭' },
  { id: 'xiyou-map-0049', fileName: 'mapid.php', name: '地图中心' },
  { id: 'xiyou-map-0050', fileName: 'maptop.php', name: '地图顶层' },
  { id: 'xiyou-map-0051', fileName: 'mz.php', name: '梅庄' },
  { id: 'xiyou-map-0052', fileName: 'neg.php', name: '南国' },
  { id: 'xiyou-map-0053', fileName: 'pds.php', name: '普陀山' },
  { id: 'xiyou-map-0054', fileName: 'psd.php', name: '菩提寺' },
  { id: 'xiyou-map-0055', fileName: 'psdd.php', name: '菩提殿' },
  { id: 'xiyou-map-0056', fileName: 'pts.php', name: '普陀寺' },
  { id: 'xiyou-map-0057', fileName: 'pty.php', name: '普陀崖' },
  { id: 'xiyou-map-0058', fileName: 'qls.php', name: '麒麟山' },
  { id: 'xiyou-map-0059', fileName: 'scl.php', name: '三轮' },
  { id: 'xiyou-map-0060', fileName: 'sl.php', name: '水帘洞' },
  { id: 'xiyou-map-0061', fileName: 'std.php', name: '狮驼岭' },
  { id: 'xiyou-map-0062', fileName: 'tfg.php', name: '天王府' },
  { id: 'xiyou-map-0063', fileName: 'tg.php', name: '天宫' },
  { id: 'xiyou-map-0064', fileName: 'tl.php', name: '天牢' },
  { id: 'xiyou-map-0065', fileName: 'ttsf.php', name: '通天水府' },
  { id: 'xiyou-map-0066', fileName: 'ttt.php', name: '天台' },
  { id: 'xiyou-map-0067', fileName: 'tzg.php', name: '天尊宫' },
  { id: 'xiyou-map-0068', fileName: 'vip1qy.php', name: 'VIP一区' },
  { id: 'xiyou-map-0069', fileName: 'vip2qy.php', name: 'VIP二区' },
  { id: 'xiyou-map-0070', fileName: 'vip3qy.php', name: 'VIP三区' },
  { id: 'xiyou-map-0071', fileName: 'vip4qy.php', name: 'VIP四区' },
  { id: 'xiyou-map-0072', fileName: 'vipqy.php', name: 'VIP区' },
  { id: 'xiyou-map-0073', fileName: 'wdd.php', name: '无底洞' },
  { id: 'xiyou-map-0074', fileName: 'wjg.php', name: '武馆' },
  { id: 'xiyou-map-0075', fileName: 'wsc.php', name: '五庄观' },
  { id: 'xiyou-map-0076', fileName: 'wxz01.php', name: '五行阵' },
  { id: 'xiyou-map-0077', fileName: 'xgt.php', name: '仙宫殿' },
  { id: 'xiyou-map-0078', fileName: 'xl.php', name: '雪岭' },
  { id: 'xiyou-map-0079', fileName: 'xlys.php', name: '西梁玉山' },
  { id: 'xiyou-map-0080', fileName: 'xsc.php', name: '雪山城' },
  { id: 'xiyou-map-0081', fileName: 'xsmg.php', name: '雪山迷宫' },
  { id: 'xiyou-map-0082', fileName: 'xyj.php', name: '西游界' },
  { id: 'xiyou-map-0083', fileName: 'xyt.php', name: '仙云台' },
  { id: 'xiyou-map-0084', fileName: 'yc.php', name: '银川' },
  { id: 'xiyou-map-0085', fileName: 'yg.php', name: '月光' },
  { id: 'xiyou-map-0086', fileName: 'ygd.php', name: '月光殿' },
  { id: 'xiyou-map-0087', fileName: 'yh.php', name: '月湖' },
  { id: 'xiyou-map-0088', fileName: 'yhq.php', name: '月湖区' },
  { id: 'xiyou-map-0089', fileName: 'yld.php', name: '月亮洞' },
  { id: 'xiyou-map-0090', fileName: 'yls.php', name: '月灵山' },
  { id: 'xiyou-map-0091', fileName: 'zgz.php', name: '中观庄' },
  { id: 'xiyou-map-0092', fileName: 'zyt.php', name: '镇妖塔' },
  { id: 'xiyou-map-0093', fileName: 'zzbl.php', name: '紫竹林' },
  { id: 'xiyou-map-0094', fileName: 'zzg.php', name: '紫竹观' },
  { id: 'xiyou-map-0095', fileName: 'zzl.php', name: '紫竹林' },
];

/** 地图ID映射 (文件名 -> ID) */
export const MAP_ID_BY_FILENAME: Record<string, string> = Object.fromEntries(
  MIGRATED_MAPS.map((map) => [map.fileName.replace('.php', ''), map.id])
);

/** 地图总数 */
export const TOTAL_MAPS = MIGRATED_MAPS.length;
