// 成就配置

import type { Achievement, Title } from '@/types/achievement';

/** 成就类别配置 */
export const ACHIEVEMENT_CATEGORIES = {
  growth: { name: '成长', icon: '🌱', description: '角色成长相关成就' },
  combat: { name: '战斗', icon: '⚔️', description: '战斗相关成就' },
  collection: { name: '收集', icon: '📦', description: '收集相关成就' },
  explore: { name: '探索', icon: '🗺️', description: '探索相关成就' },
  social: { name: '社交', icon: '💕', description: '社交相关成就' },
} as const;

/** 成就配置列表 */
export const ACHIEVEMENTS: Achievement[] = [
  // ========== 成长类成就 ==========
  {
    id: 'growth_level_10',
    name: '初入江湖',
    description: '角色等级达到10级',
    category: 'growth',
    icon: '🌟',
    points: 5,
    condition: { type: 'reach_level', target: 10 },
    reward: { gold: 500, exp: 100 },
    order: 1,
  },
  {
    id: 'growth_level_30',
    name: '小有所成',
    description: '角色等级达到30级',
    category: 'growth',
    icon: '✨',
    points: 10,
    condition: { type: 'reach_level', target: 30 },
    prerequisiteId: 'growth_level_10',
    reward: { gold: 2000, exp: 500 },
    order: 2,
  },
  {
    id: 'growth_level_50',
    name: '独当一面',
    description: '角色等级达到50级',
    category: 'growth',
    icon: '💫',
    points: 15,
    condition: { type: 'reach_level', target: 50 },
    prerequisiteId: 'growth_level_30',
    reward: { gold: 5000, exp: 1000, titleId: 'title_veteran' },
    order: 3,
  },
  {
    id: 'growth_level_70',
    name: '名震一方',
    description: '角色等级达到70级',
    category: 'growth',
    icon: '🔥',
    points: 20,
    condition: { type: 'reach_level', target: 70 },
    prerequisiteId: 'growth_level_50',
    reward: { gold: 10000, titleId: 'title_master' },
    order: 4,
  },
  {
    id: 'growth_level_100',
    name: '登峰造极',
    description: '角色等级达到100级',
    category: 'growth',
    icon: '👑',
    points: 50,
    condition: { type: 'reach_level', target: 100 },
    prerequisiteId: 'growth_level_70',
    reward: { gold: 50000, titleId: 'title_legend' },
    order: 5,
  },
  {
    id: 'growth_realm_5',
    name: '筑基有成',
    description: '修炼境界达到第5阶',
    category: 'growth',
    icon: '🔮',
    points: 10,
    condition: { type: 'reach_realm', target: 5 },
    reward: { gold: 3000 },
    order: 6,
  },
  {
    id: 'growth_playtime_10h',
    name: '乐在其中',
    description: '累计游戏时长达到10小时',
    category: 'growth',
    icon: '⏰',
    points: 5,
    condition: { type: 'accumulate_playtime', target: 36000 }, // 秒
    reward: { gold: 1000 },
    order: 7,
  },
  {
    id: 'growth_gold_100k',
    name: '富甲一方',
    description: '累计获得10万金币',
    category: 'growth',
    icon: '💰',
    points: 15,
    condition: { type: 'accumulate_gold', target: 100000 },
    reward: { gold: 10000 },
    order: 8,
  },

  // ========== 战斗类成就 ==========
  {
    id: 'combat_monsters_100',
    name: '初露锋芒',
    description: '击败100只怪物',
    category: 'combat',
    icon: '🗡️',
    points: 5,
    condition: { type: 'defeat_monsters', target: 100 },
    reward: { gold: 500, exp: 200 },
    order: 1,
  },
  {
    id: 'combat_monsters_500',
    name: '斩妖除魔',
    description: '击败500只怪物',
    category: 'combat',
    icon: '⚔️',
    points: 10,
    condition: { type: 'defeat_monsters', target: 500 },
    prerequisiteId: 'combat_monsters_100',
    reward: { gold: 2000, exp: 800 },
    order: 2,
  },
  {
    id: 'combat_monsters_1000',
    name: '魔障尽除',
    description: '击败1000只怪物',
    category: 'combat',
    icon: '💀',
    points: 15,
    condition: { type: 'defeat_monsters', target: 1000 },
    prerequisiteId: 'combat_monsters_500',
    reward: { gold: 5000, titleId: 'title_demon_hunter' },
    order: 3,
  },
  {
    id: 'combat_boss_1',
    name: '初战告捷',
    description: '首次击败Boss',
    category: 'combat',
    icon: '🏆',
    points: 10,
    condition: { type: 'defeat_bosses', target: 1 },
    reward: { gold: 1000, exp: 500 },
    order: 4,
  },
  {
    id: 'combat_boss_10',
    name: 'Boss猎手',
    description: '击败10个Boss',
    category: 'combat',
    icon: '🎯',
    points: 20,
    condition: { type: 'defeat_bosses', target: 10 },
    prerequisiteId: 'combat_boss_1',
    reward: { gold: 5000, titleId: 'title_boss_hunter' },
    order: 5,
  },
  {
    id: 'combat_dungeon_first',
    name: '副本新手',
    description: '首次通关副本',
    category: 'combat',
    icon: '🏰',
    points: 10,
    condition: { type: 'clear_dungeon', target: 1 },
    reward: { gold: 1500, exp: 600 },
    order: 6,
  },
  {
    id: 'combat_damage_1m',
    name: '伤害制造者',
    description: '累计造成100万伤害',
    category: 'combat',
    icon: '💥',
    points: 10,
    condition: { type: 'total_damage_dealt', target: 1000000 },
    reward: { gold: 2000 },
    order: 7,
  },
  {
    id: 'combat_battles_100',
    name: '身经百战',
    description: '累计获得100场战斗胜利',
    category: 'combat',
    icon: '🎖️',
    points: 10,
    condition: { type: 'win_battles', target: 100 },
    reward: { gold: 3000 },
    order: 8,
  },

  // ========== 收集类成就 ==========
  {
    id: 'collect_equipment_10',
    name: '装备收藏家',
    description: '收集10件装备',
    category: 'collection',
    icon: '🎒',
    points: 10,
    condition: { type: 'collect_equipment', target: 10 },
    reward: { gold: 1000 },
    order: 1,
  },
  {
    id: 'collect_equipment_50',
    name: '装备大师',
    description: '收集50件装备',
    category: 'collection',
    icon: '📦',
    points: 20,
    condition: { type: 'collect_equipment', target: 50 },
    prerequisiteId: 'collect_equipment_10',
    reward: { gold: 5000 },
    order: 2,
  },
  {
    id: 'collect_legendary_1',
    name: '传说初现',
    description: '获得第一件传说品质装备',
    category: 'collection',
    icon: '🌟',
    points: 15,
    condition: { type: 'collect_legendary', target: 1 },
    reward: { gold: 3000 },
    order: 3,
  },
  {
    id: 'collect_legendary_5',
    name: '传说收集者',
    description: '收集5件传说品质装备',
    category: 'collection',
    icon: '✨',
    points: 25,
    condition: { type: 'collect_legendary', target: 5 },
    prerequisiteId: 'collect_legendary_1',
    reward: { gold: 10000, titleId: 'title_legendary_collector' },
    order: 4,
  },
  {
    id: 'collect_mythic_1',
    name: '神话降临',
    description: '获得第一件神话品质装备',
    category: 'collection',
    icon: '👑',
    points: 30,
    condition: { type: 'collect_mythic', target: 1 },
    hidden: true,
    reward: { gold: 20000, titleId: 'title_mythic_owner' },
    order: 5,
  },
  {
    id: 'collect_pet_3',
    name: '宠物爱好者',
    description: '拥有3只宠物',
    category: 'collection',
    icon: '🐾',
    points: 10,
    condition: { type: 'collect_pets', target: 3 },
    reward: { gold: 1500 },
    order: 6,
  },
  {
    id: 'collect_pet_10',
    name: '宠物大师',
    description: '拥有10只宠物',
    category: 'collection',
    icon: '🐉',
    points: 20,
    condition: { type: 'collect_pets', target: 10 },
    prerequisiteId: 'collect_pet_3',
    reward: { gold: 5000, titleId: 'title_pet_master' },
    order: 7,
  },
  {
    id: 'collect_companion_3',
    name: '人缘不错',
    description: '解锁3位伙伴',
    category: 'collection',
    icon: '👥',
    points: 15,
    condition: { type: 'collect_companions', target: 3 },
    reward: { gold: 2000 },
    order: 8,
  },

  // ========== 探索类成就 ==========
  {
    id: 'explore_maps_3',
    name: '初识天下',
    description: '探索3个不同地图',
    category: 'explore',
    icon: '🗺️',
    points: 10,
    condition: { type: 'explore_maps', target: 3 },
    reward: { gold: 1000 },
    order: 1,
  },
  {
    id: 'explore_maps_all',
    name: '足迹遍布',
    description: '探索所有地图',
    category: 'explore',
    icon: '🌍',
    points: 30,
    condition: { type: 'explore_maps', target: 10 },
    prerequisiteId: 'explore_maps_3',
    reward: { gold: 10000, titleId: 'title_explorer' },
    order: 2,
  },
  {
    id: 'explore_teleport_5',
    name: '传送网络',
    description: '解锁5个传送点',
    category: 'explore',
    icon: '🌀',
    points: 10,
    condition: { type: 'unlock_teleports', target: 5 },
    reward: { gold: 2000 },
    order: 3,
  },
  {
    id: 'explore_teleport_all',
    name: '通行无阻',
    description: '解锁所有传送点',
    category: 'explore',
    icon: '✈️',
    points: 25,
    condition: { type: 'unlock_teleports', target: 15 },
    prerequisiteId: 'explore_teleport_5',
    reward: { gold: 8000, titleId: 'title_traveler' },
    order: 4,
  },
  {
    id: 'explore_secrets_1',
    name: '好奇心',
    description: '发现第一个秘密',
    category: 'explore',
    icon: '🔍',
    points: 15,
    condition: { type: 'discover_secrets', target: 1 },
    hidden: true,
    reward: { gold: 3000 },
    order: 5,
  },
  {
    id: 'explore_secrets_5',
    name: '探秘者',
    description: '发现5个秘密',
    category: 'explore',
    icon: '🗝️',
    points: 25,
    condition: { type: 'discover_secrets', target: 5 },
    hidden: true,
    reward: { gold: 10000, titleId: 'title_secret_finder' },
    order: 6,
  },

  // ========== 社交类成就 ==========
  {
    id: 'social_favorability_1',
    name: '情谊初结',
    description: '与一位伙伴好感度达到满级',
    category: 'social',
    icon: '💕',
    points: 15,
    condition: { type: 'max_favorability', target: 1 },
    reward: { gold: 3000 },
    order: 1,
  },
  {
    id: 'social_favorability_3',
    name: '知心好友',
    description: '与三位伙伴好感度达到满级',
    category: 'social',
    icon: '💖',
    points: 25,
    condition: { type: 'max_favorability', target: 3 },
    prerequisiteId: 'social_favorability_1',
    reward: { gold: 10000, titleId: 'title_soulmate' },
    order: 2,
  },
  {
    id: 'social_bond_1',
    name: '羁绊初现',
    description: '解锁第一个羁绊',
    category: 'social',
    icon: '🔗',
    points: 15,
    condition: { type: 'unlock_bonds', target: 1 },
    reward: { gold: 2000, exp: 500 },
    order: 3,
  },
  {
    id: 'social_bond_5',
    name: '羁绊之主',
    description: '解锁5个羁绊',
    category: 'social',
    icon: '💎',
    points: 25,
    condition: { type: 'unlock_bonds', target: 5 },
    prerequisiteId: 'social_bond_1',
    reward: { gold: 8000, titleId: 'title_bond_master' },
    order: 4,
  },
  {
    id: 'social_bond_max_1',
    name: '羁绊满级',
    description: '将一个羁绊升到满级',
    category: 'social',
    icon: '🌟',
    points: 20,
    condition: { type: 'max_bond_level', target: 1 },
    prerequisiteId: 'social_bond_1',
    reward: { gold: 5000, titleId: 'title_bond_legend' },
    order: 5,
  },
];

/** 称号配置列表 */
export const TITLES: Title[] = [
  {
    id: 'title_veteran',
    name: '资深修行者',
    description: '等级达到50级获得',
    icon: '🎖️',
    color: '#4A90D9',
    condition: '等级达到50级',
  },
  {
    id: 'title_master',
    name: '修行大师',
    description: '等级达到70级获得',
    icon: '🏆',
    color: '#A335EE',
    statBonus: { strength: 10, intelligence: 10 },
    condition: '等级达到70级',
  },
  {
    id: 'title_legend',
    name: '传说之巅',
    description: '等级达到100级获得',
    icon: '👑',
    color: '#FF8000',
    statBonus: { strength: 20, intelligence: 20, vitality: 20 },
    condition: '等级达到100级',
    rare: true,
  },
  {
    id: 'title_demon_hunter',
    name: '斩妖者',
    description: '击败1000只怪物获得',
    icon: '⚔️',
    color: '#00AA00',
    statBonus: { physicalAttack: 20 },
    condition: '击败1000只怪物',
  },
  {
    id: 'title_boss_hunter',
    name: 'Boss猎手',
    description: '击败10个Boss获得',
    icon: '🎯',
    color: '#FF4444',
    statBonus: { physicalAttack: 30, magicAttack: 30 },
    condition: '击败10个Boss',
  },
  {
    id: 'title_legendary_collector',
    name: '传说收藏家',
    description: '收集5件传说装备获得',
    icon: '✨',
    color: '#FF8000',
    statBonus: { critRate: 0.05 },
    condition: '收集5件传说装备',
  },
  {
    id: 'title_mythic_owner',
    name: '神话持有者',
    description: '获得神话品质装备',
    icon: '👑',
    color: '#E6CC80',
    statBonus: { damageBonus: 0.05 },
    condition: '获得神话装备',
    rare: true,
  },
  {
    id: 'title_pet_master',
    name: '宠物大师',
    description: '拥有10只宠物获得',
    icon: '🐉',
    color: '#44FF44',
    statBonus: { maxHp: 200 },
    condition: '拥有10只宠物',
  },
  {
    id: 'title_explorer',
    name: '探险家',
    description: '探索所有地图获得',
    icon: '🗺️',
    color: '#00DDDD',
    statBonus: { speed: 10 },
    condition: '探索所有地图',
  },
  {
    id: 'title_traveler',
    name: '旅行者',
    description: '解锁所有传送点获得',
    icon: '✈️',
    color: '#DDDD00',
    statBonus: { speed: 15 },
    condition: '解锁所有传送点',
  },
  {
    id: 'title_secret_finder',
    name: '探秘者',
    description: '发现5个秘密获得',
    icon: '🗝️',
    color: '#AA00AA',
    statBonus: { critDamage: 0.1 },
    condition: '发现5个秘密',
    rare: true,
  },
  {
    id: 'title_soulmate',
    name: '知心好友',
    description: '与三位伙伴好感度满级获得',
    icon: '💖',
    color: '#FF69B4',
    statBonus: { maxHp: 100, maxMp: 50 },
    condition: '与三位伙伴好感度达到满级',
  },
  {
    id: 'title_bond_master',
    name: '羁绊之主',
    description: '解锁5个羁绊获得',
    icon: '💎',
    color: '#9932CC',
    statBonus: { damageBonus: 0.03, damageReduction: 0.03 },
    condition: '解锁5个羁绊',
  },
  {
    id: 'title_bond_legend',
    name: '羁绊传说',
    description: '将一个羁绊升到满级获得',
    icon: '🌟',
    color: '#FFD700',
    statBonus: { damageBonus: 0.05 },
    condition: '将一个羁绊升到满级',
    rare: true,
  },
];

/** 获取成就配置 */
export function getAchievement(id: string): Achievement | undefined {
  return ACHIEVEMENTS.find((a) => a.id === id);
}

/** 获取类别下的所有成就 */
export function getAchievementsByCategory(category: Achievement['category']): Achievement[] {
  return ACHIEVEMENTS.filter((a) => a.category === category).sort((a, b) => (a.order ?? 0) - (b.order ?? 0));
}

/** 获取称号配置 */
export function getTitle(id: string): Title | undefined {
  return TITLES.find((t) => t.id === id);
}

/** 获取总成就点数 */
export function getTotalAchievementPoints(): number {
  return ACHIEVEMENTS.reduce((sum, a) => sum + a.points, 0);
}

/** 获取成就数量 */
export function getAchievementCount(): number {
  return ACHIEVEMENTS.length;
}
