// 成就配置

import type { Achievement, Title } from '@/types/achievement';

/** 地图总数（根据 maps.ts 统计） */
export const TOTAL_MAPS = 55;

/** 副本总数（根据 dungeons.ts 统计） */
export const TOTAL_DUNGEONS = 3;

/** 伙伴总数（根据 companions.ts 统计） */
export const TOTAL_COMPANIONS = 3;

/** 成就类别配置 */
export const ACHIEVEMENT_CATEGORIES = {
  growth: { name: '成长', icon: '🌱', description: '角色成长相关成就' },
  combat: { name: '战斗', icon: '⚔️', description: '战斗相关成就' },
  collection: { name: '收集', icon: '📦', description: '收集相关成就' },
  explore: { name: '探索', icon: '🗺️', description: '探索相关成就' },
  social: { name: '社交', icon: '💕', description: '社交相关成就' },
} as const;

/** 成就配置列表 */
export const ACHIEVEMENTS: Achievement[] = [
  // ========== 成长类成就 ==========
  {
    id: 'growth_level_10',
    name: '初入江湖',
    description: '角色等级达到10级',
    category: 'growth',
    icon: '🌟',
    points: 5,
    condition: { type: 'reach_level', target: 10 },
    reward: { gold: 500, exp: 100 },
    order: 1,
  },
  {
    id: 'growth_level_30',
    name: '小有所成',
    description: '角色等级达到30级',
    category: 'growth',
    icon: '✨',
    points: 10,
    condition: { type: 'reach_level', target: 30 },
    prerequisiteId: 'growth_level_10',
    reward: { gold: 2000, exp: 500 },
    order: 2,
  },
  {
    id: 'growth_level_50',
    name: '独当一面',
    description: '角色等级达到50级',
    category: 'growth',
    icon: '💫',
    points: 15,
    condition: { type: 'reach_level', target: 50 },
    prerequisiteId: 'growth_level_30',
    reward: { gold: 5000, exp: 1000, titleId: 'title_veteran' },
    order: 3,
  },
  {
    id: 'growth_level_70',
    name: '名震一方',
    description: '角色等级达到70级',
    category: 'growth',
    icon: '🔥',
    points: 20,
    condition: { type: 'reach_level', target: 70 },
    prerequisiteId: 'growth_level_50',
    reward: { gold: 10000, titleId: 'title_master' },
    order: 4,
  },
  {
    id: 'growth_level_100',
    name: '登峰造极',
    description: '角色等级达到100级',
    category: 'growth',
    icon: '👑',
    points: 50,
    condition: { type: 'reach_level', target: 100 },
    prerequisiteId: 'growth_level_70',
    reward: { gold: 50000, titleId: 'title_legend' },
    order: 5,
  },
  {
    id: 'growth_realm_5',
    name: '筑基有成',
    description: '修炼境界达到第5阶',
    category: 'growth',
    icon: '🔮',
    points: 10,
    condition: { type: 'reach_realm', target: 5 },
    reward: { gold: 3000 },
    order: 6,
  },
  {
    id: 'growth_realm_10',
    name: '金丹大成',
    description: '修炼境界达到第10阶',
    category: 'growth',
    icon: '💎',
    points: 20,
    condition: { type: 'reach_realm', target: 10 },
    prerequisiteId: 'growth_realm_5',
    reward: { gold: 8000 },
    order: 7,
  },
  {
    id: 'growth_playtime_10h',
    name: '乐在其中',
    description: '累计游戏时长达到10小时',
    category: 'growth',
    icon: '⏰',
    points: 5,
    condition: { type: 'accumulate_playtime', target: 36000 }, // 秒
    reward: { gold: 1000 },
    order: 8,
  },
  {
    id: 'growth_playtime_100h',
    name: '废寝忘食',
    description: '累计游戏时长达到100小时',
    category: 'growth',
    icon: '🕐',
    points: 15,
    condition: { type: 'accumulate_playtime', target: 360000 }, // 秒
    prerequisiteId: 'growth_playtime_10h',
    reward: { gold: 5000 },
    order: 9,
  },
  {
    id: 'growth_gold_10k',
    name: '小有积蓄',
    description: '累计获得1万金币',
    category: 'growth',
    icon: '💰',
    points: 5,
    condition: { type: 'accumulate_gold', target: 10000 },
    reward: { gold: 1000 },
    order: 10,
  },
  {
    id: 'growth_gold_100k',
    name: '富甲一方',
    description: '累计获得10万金币',
    category: 'growth',
    icon: '💰',
    points: 15,
    condition: { type: 'accumulate_gold', target: 100000 },
    prerequisiteId: 'growth_gold_10k',
    reward: { gold: 10000 },
    order: 11,
  },
  {
    id: 'growth_gold_1m',
    name: '财源滚滚',
    description: '累计获得100万金币',
    category: 'growth',
    icon: '💎',
    points: 30,
    condition: { type: 'accumulate_gold', target: 1000000 },
    prerequisiteId: 'growth_gold_100k',
    reward: { gold: 50000, titleId: 'title_tycoon' },
    order: 12,
  },
  {
    id: 'growth_spend_10k',
    name: '挥金如土',
    description: '累计消费1万金币',
    category: 'growth',
    icon: '💸',
    points: 5,
    condition: { type: 'spend_gold', target: 10000 },
    reward: { gold: 500 },
    order: 13,
  },
  {
    id: 'growth_spend_100k',
    name: '一掷千金',
    description: '累计消费10万金币',
    category: 'growth',
    icon: '💵',
    points: 15,
    condition: { type: 'spend_gold', target: 100000 },
    prerequisiteId: 'growth_spend_10k',
    reward: { gold: 5000 },
    order: 14,
  },

  // ========== 战斗类成就 ==========
  {
    id: 'combat_monsters_100',
    name: '初露锋芒',
    description: '击败100只怪物',
    category: 'combat',
    icon: '🗡️',
    points: 5,
    condition: { type: 'defeat_monsters', target: 100 },
    reward: { gold: 500, exp: 200 },
    order: 1,
  },
  {
    id: 'combat_monsters_500',
    name: '斩妖除魔',
    description: '击败500只怪物',
    category: 'combat',
    icon: '⚔️',
    points: 10,
    condition: { type: 'defeat_monsters', target: 500 },
    prerequisiteId: 'combat_monsters_100',
    reward: { gold: 2000, exp: 800 },
    order: 2,
  },
  {
    id: 'combat_monsters_1000',
    name: '魔障尽除',
    description: '击败1000只怪物',
    category: 'combat',
    icon: '💀',
    points: 15,
    condition: { type: 'defeat_monsters', target: 1000 },
    prerequisiteId: 'combat_monsters_500',
    reward: { gold: 5000, titleId: 'title_demon_hunter' },
    order: 3,
  },
  {
    id: 'combat_monsters_5000',
    name: '万魔臣服',
    description: '击败5000只怪物',
    category: 'combat',
    icon: '👿',
    points: 25,
    condition: { type: 'defeat_monsters', target: 5000 },
    prerequisiteId: 'combat_monsters_1000',
    reward: { gold: 15000 },
    order: 4,
  },
  {
    id: 'combat_boss_1',
    name: '初战告捷',
    description: '首次击败Boss',
    category: 'combat',
    icon: '🏆',
    points: 10,
    condition: { type: 'defeat_bosses', target: 1 },
    reward: { gold: 1000, exp: 500 },
    order: 5,
  },
  {
    id: 'combat_boss_10',
    name: 'Boss猎手',
    description: '击败10个Boss',
    category: 'combat',
    icon: '🎯',
    points: 20,
    condition: { type: 'defeat_bosses', target: 10 },
    prerequisiteId: 'combat_boss_1',
    reward: { gold: 5000, titleId: 'title_boss_hunter' },
    order: 6,
  },
  {
    id: 'combat_boss_50',
    name: 'Boss终结者',
    description: '击败50个Boss',
    category: 'combat',
    icon: '👑',
    points: 35,
    condition: { type: 'defeat_bosses', target: 50 },
    prerequisiteId: 'combat_boss_10',
    reward: { gold: 20000, titleId: 'title_boss_slayer' },
    order: 7,
  },
  {
    id: 'combat_dungeon_first',
    name: '副本新手',
    description: '首次通关副本',
    category: 'combat',
    icon: '🏰',
    points: 10,
    condition: { type: 'clear_dungeon', target: 1 },
    reward: { gold: 1500, exp: 600 },
    order: 8,
  },
  {
    id: 'combat_dungeon_all',
    name: '副本征服者',
    description: '通关所有副本',
    category: 'combat',
    icon: '🏯',
    points: 30,
    condition: { type: 'clear_dungeon', target: TOTAL_DUNGEONS },
    prerequisiteId: 'combat_dungeon_first',
    reward: { gold: 10000, titleId: 'title_dungeon_master' },
    order: 9,
  },
  {
    id: 'combat_dungeon_hard',
    name: '困难挑战者',
    description: '通关困难难度副本',
    category: 'combat',
    icon: '💪',
    points: 20,
    condition: { type: 'clear_dungeon_hard', target: 1 },
    reward: { gold: 5000 },
    order: 10,
  },
  {
    id: 'combat_dungeon_hell',
    name: '地狱征服者',
    description: '通关地狱难度副本',
    category: 'combat',
    icon: '🔥',
    points: 30,
    condition: { type: 'clear_dungeon_hell', target: 1 },
    prerequisiteId: 'combat_dungeon_hard',
    reward: { gold: 15000, titleId: 'title_hell_conqueror' },
    order: 11,
  },
  {
    id: 'combat_dungeon_no_damage',
    name: '完美通关',
    description: '无伤通关副本',
    category: 'combat',
    icon: '✨',
    points: 25,
    condition: { type: 'clear_dungeon_no_damage', target: 1 },
    hidden: true,
    reward: { gold: 10000 },
    order: 12,
  },
  {
    id: 'combat_damage_1m',
    name: '伤害制造者',
    description: '累计造成100万伤害',
    category: 'combat',
    icon: '💥',
    points: 10,
    condition: { type: 'total_damage_dealt', target: 1000000 },
    reward: { gold: 2000 },
    order: 13,
  },
  {
    id: 'combat_damage_10m',
    name: '毁灭之力',
    description: '累计造成1000万伤害',
    category: 'combat',
    icon: '💫',
    points: 20,
    condition: { type: 'total_damage_dealt', target: 10000000 },
    prerequisiteId: 'combat_damage_1m',
    reward: { gold: 8000 },
    order: 14,
  },
  {
    id: 'combat_battles_100',
    name: '身经百战',
    description: '累计获得100场战斗胜利',
    category: 'combat',
    icon: '🎖️',
    points: 10,
    condition: { type: 'win_battles', target: 100 },
    reward: { gold: 3000 },
    order: 15,
  },
  {
    id: 'combat_battles_500',
    name: '战神降临',
    description: '累计获得500场战斗胜利',
    category: 'combat',
    icon: '⚔️',
    points: 25,
    condition: { type: 'win_battles', target: 500 },
    prerequisiteId: 'combat_battles_100',
    reward: { gold: 12000, titleId: 'title_war_god' },
    order: 16,
  },

  // ========== 收集类成就 ==========
  {
    id: 'collect_equipment_10',
    name: '装备收藏家',
    description: '收集10件装备',
    category: 'collection',
    icon: '🎒',
    points: 10,
    condition: { type: 'collect_equipment', target: 10 },
    reward: { gold: 1000 },
    order: 1,
  },
  {
    id: 'collect_equipment_50',
    name: '装备大师',
    description: '收集50件装备',
    category: 'collection',
    icon: '📦',
    points: 20,
    condition: { type: 'collect_equipment', target: 50 },
    prerequisiteId: 'collect_equipment_10',
    reward: { gold: 5000 },
    order: 2,
  },
  {
    id: 'collect_equipment_100',
    name: '装备收藏大师',
    description: '收集100件装备',
    category: 'collection',
    icon: '🎒',
    points: 30,
    condition: { type: 'collect_equipment', target: 100 },
    prerequisiteId: 'collect_equipment_50',
    reward: { gold: 10000 },
    order: 3,
  },
  {
    id: 'collect_legendary_1',
    name: '传说初现',
    description: '获得第一件传说品质装备',
    category: 'collection',
    icon: '🌟',
    points: 15,
    condition: { type: 'collect_legendary', target: 1 },
    reward: { gold: 3000 },
    order: 4,
  },
  {
    id: 'collect_legendary_5',
    name: '传说收集者',
    description: '收集5件传说品质装备',
    category: 'collection',
    icon: '✨',
    points: 25,
    condition: { type: 'collect_legendary', target: 5 },
    prerequisiteId: 'collect_legendary_1',
    reward: { gold: 10000, titleId: 'title_legendary_collector' },
    order: 5,
  },
  {
    id: 'collect_legendary_10',
    name: '传说之主',
    description: '收集10件传说品质装备',
    category: 'collection',
    icon: '💫',
    points: 40,
    condition: { type: 'collect_legendary', target: 10 },
    prerequisiteId: 'collect_legendary_5',
    reward: { gold: 25000 },
    order: 6,
  },
  {
    id: 'collect_mythic_1',
    name: '神话降临',
    description: '获得第一件神话品质装备',
    category: 'collection',
    icon: '👑',
    points: 30,
    condition: { type: 'collect_mythic', target: 1 },
    hidden: true,
    reward: { gold: 20000, titleId: 'title_mythic_owner' },
    order: 7,
  },
  {
    id: 'collect_pet_3',
    name: '宠物爱好者',
    description: '拥有3只宠物',
    category: 'collection',
    icon: '🐾',
    points: 10,
    condition: { type: 'collect_pets', target: 3 },
    reward: { gold: 1500 },
    order: 8,
  },
  {
    id: 'collect_pet_10',
    name: '宠物大师',
    description: '拥有10只宠物',
    category: 'collection',
    icon: '🐉',
    points: 20,
    condition: { type: 'collect_pets', target: 10 },
    prerequisiteId: 'collect_pet_3',
    reward: { gold: 5000, titleId: 'title_pet_master' },
    order: 9,
  },
  {
    id: 'collect_pet_30',
    name: '宠物收藏家',
    description: '拥有30只宠物',
    category: 'collection',
    icon: '🐉',
    points: 35,
    condition: { type: 'collect_pets', target: 30 },
    prerequisiteId: 'collect_pet_10',
    reward: { gold: 15000, titleId: 'title_pet_collector' },
    order: 10,
  },
  {
    id: 'pet_capture_10',
    name: '捕宠新手',
    description: '成功捕捉10只宠物',
    category: 'collection',
    icon: '🎯',
    points: 10,
    condition: { type: 'pet_capture', target: 10 },
    reward: { gold: 2000 },
    order: 11,
  },
  {
    id: 'pet_capture_50',
    name: '捕宠达人',
    description: '成功捕捉50只宠物',
    category: 'collection',
    icon: '🥅',
    points: 20,
    condition: { type: 'pet_capture', target: 50 },
    prerequisiteId: 'pet_capture_10',
    reward: { gold: 8000 },
    order: 12,
  },
  {
    id: 'pet_evolve_1',
    name: '进化的奇迹',
    description: '首次成功让宠物进化',
    category: 'collection',
    icon: '🌟',
    points: 15,
    condition: { type: 'pet_evolve', target: 1 },
    reward: { gold: 3000 },
    order: 13,
  },
  {
    id: 'pet_evolve_5',
    name: '进化大师',
    description: '成功让5只宠物进化',
    category: 'collection',
    icon: '✨',
    points: 25,
    condition: { type: 'pet_evolve', target: 5 },
    prerequisiteId: 'pet_evolve_1',
    reward: { gold: 10000 },
    order: 14,
  },
  {
    id: 'pet_level_max_1',
    name: '满级伙伴',
    description: '将一只宠物培养到满级',
    category: 'collection',
    icon: '🏆',
    points: 20,
    condition: { type: 'pet_level_max', target: 1 },
    reward: { gold: 5000 },
    order: 15,
  },
  {
    id: 'collect_companion_1',
    name: '伙伴初识',
    description: '解锁1位伙伴',
    category: 'collection',
    icon: '👥',
    points: 10,
    condition: { type: 'collect_companions', target: 1 },
    reward: { gold: 1500 },
    order: 16,
  },
  {
    id: 'collect_companion_all',
    name: '人缘不错',
    description: '解锁所有伙伴',
    category: 'collection',
    icon: '👥',
    points: 25,
    condition: { type: 'collect_companions', target: TOTAL_COMPANIONS },
    prerequisiteId: 'collect_companion_1',
    reward: { gold: 8000 },
    order: 17,
  },
  {
    id: 'socket_gems_1',
    name: '宝石镶嵌',
    description: '首次成功镶嵌宝石',
    category: 'collection',
    icon: '💎',
    points: 10,
    condition: { type: 'socket_gems', target: 1 },
    reward: { gold: 2000 },
    order: 18,
  },
  {
    id: 'socket_gems_10',
    name: '宝石工匠',
    description: '累计镶嵌10颗宝石',
    category: 'collection',
    icon: '💎',
    points: 20,
    condition: { type: 'socket_gems', target: 10 },
    prerequisiteId: 'socket_gems_1',
    reward: { gold: 6000 },
    order: 19,
  },
  {
    id: 'collect_gems_10',
    name: '宝石收藏家',
    description: '收集10颗宝石',
    category: 'collection',
    icon: '💠',
    points: 10,
    condition: { type: 'collect_gems', target: 10 },
    reward: { gold: 2000 },
    order: 20,
  },

  // ========== 探索类成就 ==========
  {
    id: 'explore_maps_10',
    name: '初识天下',
    description: '探索10个不同地图',
    category: 'explore',
    icon: '🗺️',
    points: 10,
    condition: { type: 'explore_maps', target: 10 },
    reward: { gold: 1000 },
    order: 1,
  },
  {
    id: 'explore_maps_30',
    name: '行万里路',
    description: '探索30个不同地图',
    category: 'explore',
    icon: '🚶',
    points: 20,
    condition: { type: 'explore_maps', target: 30 },
    prerequisiteId: 'explore_maps_10',
    reward: { gold: 5000 },
    order: 2,
  },
  {
    id: 'explore_maps_all',
    name: '足迹遍布',
    description: '探索所有地图',
    category: 'explore',
    icon: '🌍',
    points: 50,
    condition: { type: 'explore_maps', target: TOTAL_MAPS },
    prerequisiteId: 'explore_maps_30',
    reward: { gold: 20000, titleId: 'title_explorer' },
    order: 3,
  },
  {
    id: 'explore_region_newbie',
    name: '新手村探索者',
    description: '探索完新手村区域所有地图',
    category: 'explore',
    icon: '🏘️',
    points: 10,
    condition: { type: 'explore_region', target: 1, params: { regionId: 'newbie' } },
    reward: { gold: 1500 },
    order: 4,
  },
  {
    id: 'explore_region_changan',
    name: '长安漫步者',
    description: '探索完长安城区域所有地图',
    category: 'explore',
    icon: '🏯',
    points: 15,
    condition: { type: 'explore_region', target: 1, params: { regionId: 'changan' } },
    reward: { gold: 3000 },
    order: 5,
  },
  {
    id: 'explore_region_datang',
    name: '大唐游历者',
    description: '探索完东土大唐区域所有地图',
    category: 'explore',
    icon: '🏛️',
    points: 20,
    condition: { type: 'explore_region', target: 1, params: { regionId: 'datang' } },
    reward: { gold: 5000 },
    order: 6,
  },
  {
    id: 'explore_teleport_5',
    name: '传送网络',
    description: '解锁5个传送点',
    category: 'explore',
    icon: '🌀',
    points: 10,
    condition: { type: 'unlock_teleports', target: 5 },
    reward: { gold: 2000 },
    order: 7,
  },
  {
    id: 'explore_teleport_10',
    name: '通行无阻',
    description: '解锁10个传送点',
    category: 'explore',
    icon: '✈️',
    points: 20,
    condition: { type: 'unlock_teleports', target: 10 },
    prerequisiteId: 'explore_teleport_5',
    reward: { gold: 5000, titleId: 'title_traveler' },
    order: 8,
  },
  {
    id: 'explore_secrets_1',
    name: '好奇心',
    description: '发现第一个秘密',
    category: 'explore',
    icon: '🔍',
    points: 15,
    condition: { type: 'discover_secrets', target: 1 },
    hidden: true,
    reward: { gold: 3000 },
    order: 9,
  },
  {
    id: 'explore_secrets_5',
    name: '探秘者',
    description: '发现5个秘密',
    category: 'explore',
    icon: '🗝️',
    points: 25,
    condition: { type: 'discover_secrets', target: 5 },
    hidden: true,
    reward: { gold: 10000, titleId: 'title_secret_finder' },
    order: 10,
  },
  {
    id: 'explore_secrets_10',
    name: '秘密猎人',
    description: '发现10个秘密',
    category: 'explore',
    icon: '🔮',
    points: 40,
    condition: { type: 'discover_secrets', target: 10 },
    hidden: true,
    prerequisiteId: 'explore_secrets_5',
    reward: { gold: 25000 },
    order: 11,
  },

  // ========== 社交类成就 ==========
  {
    id: 'social_favorability_1',
    name: '情谊初结',
    description: '与一位伙伴好感度达到满级',
    category: 'social',
    icon: '💕',
    points: 15,
    condition: { type: 'max_favorability', target: 1 },
    reward: { gold: 3000 },
    order: 1,
  },
  {
    id: 'social_favorability_all',
    name: '知心好友',
    description: '与所有伙伴好感度达到满级',
    category: 'social',
    icon: '💖',
    points: 35,
    condition: { type: 'max_favorability', target: TOTAL_COMPANIONS },
    prerequisiteId: 'social_favorability_1',
    reward: { gold: 15000, titleId: 'title_soulmate' },
    order: 2,
  },
  {
    id: 'social_bond_1',
    name: '羁绊初现',
    description: '解锁第一个羁绊',
    category: 'social',
    icon: '🔗',
    points: 15,
    condition: { type: 'unlock_bonds', target: 1 },
    reward: { gold: 2000, exp: 500 },
    order: 3,
  },
  {
    id: 'social_bond_all',
    name: '羁绊之主',
    description: '解锁所有羁绊',
    category: 'social',
    icon: '💎',
    points: 30,
    condition: { type: 'unlock_bonds', target: 3 },
    prerequisiteId: 'social_bond_1',
    reward: { gold: 10000, titleId: 'title_bond_master' },
    order: 4,
  },
  {
    id: 'social_bond_max_1',
    name: '羁绊满级',
    description: '将一个羁绊升到满级',
    category: 'social',
    icon: '🌟',
    points: 20,
    condition: { type: 'max_bond_level', target: 1 },
    prerequisiteId: 'social_bond_1',
    reward: { gold: 5000, titleId: 'title_bond_legend' },
    order: 5,
  },
  {
    id: 'social_friend_5',
    name: '广交好友',
    description: '添加5位好友',
    category: 'social',
    icon: '🤝',
    points: 10,
    condition: { type: 'friend_count', target: 5 },
    reward: { gold: 1500 },
    order: 6,
  },
  {
    id: 'social_friend_20',
    name: '人脉广阔',
    description: '添加20位好友',
    category: 'social',
    icon: '👥',
    points: 20,
    condition: { type: 'friend_count', target: 20 },
    prerequisiteId: 'social_friend_5',
    reward: { gold: 5000, titleId: 'title_socialite' },
    order: 7,
  },
  {
    id: 'social_gift_send_10',
    name: '礼轻情意重',
    description: '送出10份礼物',
    category: 'social',
    icon: '🎁',
    points: 10,
    condition: { type: 'send_gifts', target: 10 },
    reward: { gold: 2000 },
    order: 8,
  },
  {
    id: 'social_gift_send_50',
    name: '慷慨解囊',
    description: '送出50份礼物',
    category: 'social',
    icon: '💝',
    points: 20,
    condition: { type: 'send_gifts', target: 50 },
    prerequisiteId: 'social_gift_send_10',
    reward: { gold: 8000 },
    order: 9,
  },
  {
    id: 'social_gift_receive_10',
    name: '人见人爱',
    description: '收到10份礼物',
    category: 'social',
    icon: '🎀',
    points: 10,
    condition: { type: 'receive_gifts', target: 10 },
    reward: { gold: 2000 },
    order: 10,
  },
  {
    id: 'social_gift_receive_50',
    name: '人气王',
    description: '收到50份礼物',
    category: 'social',
    icon: '👑',
    points: 20,
    condition: { type: 'receive_gifts', target: 50 },
    prerequisiteId: 'social_gift_receive_10',
    reward: { gold: 8000, titleId: 'title_popular' },
    order: 11,
  },
];

/** 称号配置列表 */
export const TITLES: Title[] = [
  {
    id: 'title_veteran',
    name: '资深修行者',
    description: '等级达到50级获得',
    icon: '🎖️',
    color: '#4A90D9',
    condition: '等级达到50级',
  },
  {
    id: 'title_master',
    name: '修行大师',
    description: '等级达到70级获得',
    icon: '🏆',
    color: '#A335EE',
    statBonus: { strength: 10, intelligence: 10 },
    condition: '等级达到70级',
  },
  {
    id: 'title_legend',
    name: '传说之巅',
    description: '等级达到100级获得',
    icon: '👑',
    color: '#FF8000',
    statBonus: { strength: 20, intelligence: 20, vitality: 20 },
    condition: '等级达到100级',
    rare: true,
  },
  {
    id: 'title_tycoon',
    name: '财神爷',
    description: '累计获得100万金币',
    icon: '💰',
    color: '#FFD700',
    statBonus: { goldDrop: 0.1 },
    condition: '累计获得100万金币',
  },
  {
    id: 'title_demon_hunter',
    name: '斩妖者',
    description: '击败1000只怪物获得',
    icon: '⚔️',
    color: '#00AA00',
    statBonus: { physicalAttack: 20 },
    condition: '击败1000只怪物',
  },
  {
    id: 'title_boss_hunter',
    name: 'Boss猎手',
    description: '击败10个Boss获得',
    icon: '🎯',
    color: '#FF4444',
    statBonus: { physicalAttack: 30, magicAttack: 30 },
    condition: '击败10个Boss',
  },
  {
    id: 'title_boss_slayer',
    name: 'Boss终结者',
    description: '击败50个Boss获得',
    icon: '💀',
    color: '#8B0000',
    statBonus: { physicalAttack: 50, magicAttack: 50, critRate: 0.05 },
    condition: '击败50个Boss',
    rare: true,
  },
  {
    id: 'title_dungeon_master',
    name: '副本征服者',
    description: '通关所有副本获得',
    icon: '🏯',
    color: '#9932CC',
    statBonus: { expBonus: 0.1 },
    condition: '通关所有副本',
  },
  {
    id: 'title_hell_conqueror',
    name: '地狱征服者',
    description: '通关地狱难度副本获得',
    icon: '🔥',
    color: '#FF4500',
    statBonus: { damageBonus: 0.1 },
    condition: '通关地狱难度副本',
    rare: true,
  },
  {
    id: 'title_war_god',
    name: '战神',
    description: '累计获得500场战斗胜利',
    icon: '⚔️',
    color: '#DC143C',
    statBonus: { physicalAttack: 40, magicAttack: 40 },
    condition: '累计获得500场战斗胜利',
  },
  {
    id: 'title_legendary_collector',
    name: '传说收藏家',
    description: '收集5件传说装备获得',
    icon: '✨',
    color: '#FF8000',
    statBonus: { critRate: 0.05 },
    condition: '收集5件传说装备',
  },
  {
    id: 'title_mythic_owner',
    name: '神话持有者',
    description: '获得神话品质装备',
    icon: '👑',
    color: '#E6CC80',
    statBonus: { damageBonus: 0.05 },
    condition: '获得神话装备',
    rare: true,
  },
  {
    id: 'title_pet_master',
    name: '宠物大师',
    description: '拥有10只宠物获得',
    icon: '🐉',
    color: '#44FF44',
    statBonus: { maxHp: 200 },
    condition: '拥有10只宠物',
  },
  {
    id: 'title_pet_collector',
    name: '宠物收藏家',
    description: '拥有30只宠物获得',
    icon: '🐾',
    color: '#00CED1',
    statBonus: { maxHp: 500, petDamageBonus: 0.1 },
    condition: '拥有30只宠物',
  },
  {
    id: 'title_explorer',
    name: '探险家',
    description: '探索所有地图获得',
    icon: '🗺️',
    color: '#00DDDD',
    statBonus: { speed: 10 },
    condition: '探索所有地图',
  },
  {
    id: 'title_traveler',
    name: '旅行者',
    description: '解锁10个传送点获得',
    icon: '✈️',
    color: '#DDDD00',
    statBonus: { speed: 15 },
    condition: '解锁10个传送点',
  },
  {
    id: 'title_secret_finder',
    name: '探秘者',
    description: '发现5个秘密获得',
    icon: '🗝️',
    color: '#AA00AA',
    statBonus: { critDamage: 0.1 },
    condition: '发现5个秘密',
    rare: true,
  },
  {
    id: 'title_soulmate',
    name: '知心好友',
    description: '与所有伙伴好感度满级获得',
    icon: '💖',
    color: '#FF69B4',
    statBonus: { maxHp: 100, maxMp: 50 },
    condition: '与所有伙伴好感度达到满级',
  },
  {
    id: 'title_bond_master',
    name: '羁绊之主',
    description: '解锁所有羁绊获得',
    icon: '💎',
    color: '#9932CC',
    statBonus: { damageBonus: 0.03, damageReduction: 0.03 },
    condition: '解锁所有羁绊',
  },
  {
    id: 'title_bond_legend',
    name: '羁绊传说',
    description: '将一个羁绊升到满级获得',
    icon: '🌟',
    color: '#FFD700',
    statBonus: { damageBonus: 0.05 },
    condition: '将一个羁绊升到满级',
    rare: true,
  },
  {
    id: 'title_socialite',
    name: '社交达人',
    description: '添加20位好友获得',
    icon: '👥',
    color: '#87CEEB',
    statBonus: { expBonus: 0.05 },
    condition: '添加20位好友',
  },
  {
    id: 'title_popular',
    name: '人气王',
    description: '收到50份礼物获得',
    icon: '👑',
    color: '#FF69B4',
    statBonus: { goldDrop: 0.05 },
    condition: '收到50份礼物',
  },
];

/** 获取成就配置 */
export function getAchievement(id: string): Achievement | undefined {
  return ACHIEVEMENTS.find((a) => a.id === id);
}

/** 获取类别下的所有成就 */
export function getAchievementsByCategory(category: Achievement['category']): Achievement[] {
  return ACHIEVEMENTS.filter((a) => a.category === category).sort((a, b) => (a.order ?? 0) - (b.order ?? 0));
}

/** 获取称号配置 */
export function getTitle(id: string): Title | undefined {
  return TITLES.find((t) => t.id === id);
}

/** 获取总成就点数 */
export function getTotalAchievementPoints(): number {
  return ACHIEVEMENTS.reduce((sum, a) => sum + a.points, 0);
}

/** 获取成就数量 */
export function getAchievementCount(): number {
  return ACHIEVEMENTS.length;
}
