// 门派基础技能配置 - 提供被动属性加成和解锁主动技能
// 每个门派6-7个基础技能，按技能等级提供属性加成

import type { BaseSkill } from '@/types';

// ==================== 大唐官府基础技能 ====================
export const DATANG_BASE_SKILLS: BaseSkill[] = [
  {
    id: 'base_weiguandao',
    name: '为官之道',
    description: '为官之道，修身养性',
    icon: '📜',
    factionId: 'faction_datang',
    bonusType: 'none',
    bonusPerLevel: 0,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_shaqijue', requiredLevel: 15 },
    ],
  },
  {
    id: 'base_wushuangyiji',
    name: '无双一击',
    description: '按技能等级提高命中',
    icon: '🎯',
    factionId: 'faction_datang',
    bonusType: 'hitRate',
    bonusPerLevel: 2,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_houfa', requiredLevel: 25 },
    ],
  },
  {
    id: 'base_shenbingjianshang',
    name: '神兵鉴赏',
    description: '鉴赏神兵利器，可鉴定武器和铠甲',
    icon: '⚔️',
    factionId: 'faction_datang',
    bonusType: 'none',
    bonusPerLevel: 0,
    maxLevel: 100,
    unlockSkills: [
      { skillId: 'skill_bingqipu', requiredLevel: 5 },
    ],
  },
  {
    id: 'base_jifengbu',
    name: '疾风步',
    description: '按技能等级提高躲避力',
    icon: '💨',
    factionId: 'faction_datang',
    bonusType: 'dodge',
    bonusPerLevel: 1,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_qianlishenxing', requiredLevel: 1 },
    ],
  },
  {
    id: 'base_shifangwudi',
    name: '十方无敌',
    description: '按技能等级提高伤害力',
    icon: '💪',
    factionId: 'faction_datang',
    bonusType: 'damage',
    bonusPerLevel: 3,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_hengsao', requiredLevel: 30 },
      { skillId: 'skill_pofu', requiredLevel: 120, isAscension: true },
    ],
  },
  {
    id: 'base_ziweizhishu',
    name: '紫薇之术',
    description: '按技能等级提高灵力',
    icon: '🔮',
    factionId: 'faction_datang',
    bonusType: 'magicPower',
    bonusPerLevel: 2,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_zhanlongjue', requiredLevel: 25 },
    ],
  },
  {
    id: 'base_wentaowulue',
    name: '文韬武略',
    description: '按技能等级提高防御力',
    icon: '🛡️',
    factionId: 'faction_datang',
    bonusType: 'defense',
    bonusPerLevel: 2,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_fanjianzhiji', requiredLevel: 20 },
      { skillId: 'skill_anshenjue', requiredLevel: 120, isAscension: true },
      { skillId: 'skill_shixue', requiredLevel: 35 },
    ],
  },
];

// ==================== 化生寺基础技能 ====================
export const HUASHENG_BASE_SKILLS: BaseSkill[] = [
  {
    id: 'base_xiaochengfofa',
    name: '小乘佛法',
    description: '按技能等级提高灵力',
    icon: '🙏',
    factionId: 'faction_huasheng',
    bonusType: 'magicPower',
    bonusPerLevel: 2,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_ziqidonglai', requiredLevel: 25 },
    ],
  },
  {
    id: 'base_jingangfumo',
    name: '金刚伏魔',
    description: '按技能等级提高伤害力',
    icon: '⚔️',
    factionId: 'faction_huasheng',
    bonusType: 'damage',
    bonusPerLevel: 2,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_fofa', requiredLevel: 120, isAscension: true },
    ],
  },
  {
    id: 'base_songjing',
    name: '诵经',
    description: '诵经念佛，度化众生',
    icon: '📿',
    factionId: 'faction_huasheng',
    bonusType: 'none',
    bonusPerLevel: 0,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_jijijiyuai', requiredLevel: 1 },
    ],
  },
  {
    id: 'base_foguangpuzhao',
    name: '佛光普照',
    description: '佛光普照，加持众生',
    icon: '✨',
    factionId: 'faction_huasheng',
    bonusType: 'none',
    bonusPerLevel: 0,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_damo', requiredLevel: 30 },
      { skillId: 'skill_jingang_hufa', requiredLevel: 30 },
      { skillId: 'skill_weituo', requiredLevel: 20 },
      { skillId: 'skill_jingang_huti', requiredLevel: 35 },
      { skillId: 'skill_yiweidujiang', requiredLevel: 30 },
      { skillId: 'skill_nianhuamiaozhi', requiredLevel: 35 },
    ],
  },
  {
    id: 'base_dacibeidayuan',
    name: '大慈大悲',
    description: '按技能等级提高防御力',
    icon: '🪷',
    factionId: 'faction_huasheng',
    bonusType: 'defense',
    bonusPerLevel: 2,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_foci', requiredLevel: 40 },
    ],
  },
  {
    id: 'base_qihuangzhishu',
    name: '岐黄之术',
    description: '岐黄之术，治病救人',
    icon: '💚',
    factionId: 'faction_huasheng',
    bonusType: 'none',
    bonusPerLevel: 0,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_tuina', requiredLevel: 10 },
      { skillId: 'skill_huoxue', requiredLevel: 25 },
      { skillId: 'skill_tuiqi', requiredLevel: 35 },
      { skillId: 'skill_miaoshouhuichun', requiredLevel: 40 },
      { skillId: 'skill_jiusifushang', requiredLevel: 50 },
      { skillId: 'skill_jiedu', requiredLevel: 15 },
      { skillId: 'skill_sheshengquyi', requiredLevel: 120, isAscension: true },
    ],
  },
  {
    id: 'base_dushibu',
    name: '渡世步',
    description: '按技能等级提高躲避力',
    icon: '👣',
    factionId: 'faction_huasheng',
    bonusType: 'dodge',
    bonusPerLevel: 1,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_fomenpudu', requiredLevel: 1 },
    ],
  },
];

// ==================== 方寸山基础技能 ====================
export const FANGCUN_BASE_SKILLS: BaseSkill[] = [
  {
    id: 'base_huangtingjing',
    name: '黄庭经',
    description: '黄庭经法，修道之本',
    icon: '📖',
    factionId: 'faction_fangcun',
    bonusType: 'none',
    bonusPerLevel: 0,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_sanxianmimo', requiredLevel: 25 },
    ],
  },
  {
    id: 'base_qinglongmofa',
    name: '磬龙灭法',
    description: '按技能等级提高伤害力',
    icon: '🐉',
    factionId: 'faction_fangcun',
    bonusType: 'damage',
    bonusPerLevel: 2,
    maxLevel: 160,
    unlockSkills: [],
  },
  {
    id: 'base_pilizhou',
    name: '霹雳咒',
    description: '霹雳咒法，降妖除魔',
    icon: '⚡',
    factionId: 'faction_fangcun',
    bonusType: 'none',
    bonusPerLevel: 0,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_wulei', requiredLevel: 1 },
    ],
  },
  {
    id: 'base_fuzhishu',
    name: '符之术',
    description: '符之术法，封印控制',
    icon: '📜',
    factionId: 'faction_fangcun',
    bonusType: 'none',
    bonusPerLevel: 0,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_feixingfu', requiredLevel: 21 },
      { skillId: 'skill_bingjiefu', requiredLevel: 10 },
      { skillId: 'skill_cuimian', requiredLevel: 10 },
      { skillId: 'skill_shixin', requiredLevel: 40 },
      { skillId: 'skill_luopofu', requiredLevel: 15 },
      { skillId: 'skill_shiyifu', requiredLevel: 20 },
      { skillId: 'skill_zhuishenfu', requiredLevel: 20 },
      { skillId: 'skill_lihunfu', requiredLevel: 25 },
      { skillId: 'skill_shishenfu', requiredLevel: 25 },
      { skillId: 'skill_dingshen', requiredLevel: 30 },
      { skillId: 'skill_suijiafu', requiredLevel: 120, isAscension: true },
      { skillId: 'skill_luoleifu', requiredLevel: 20 },
    ],
  },
  {
    id: 'base_guiyuanxinfa',
    name: '归元心法',
    description: '按技能等级提高防御力',
    icon: '🧘',
    factionId: 'faction_fangcun',
    bonusType: 'defense',
    bonusPerLevel: 2,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_guiyuanzhou', requiredLevel: 1 },
      { skillId: 'skill_ningshenshu', requiredLevel: 100 },
    ],
  },
  {
    id: 'base_shendaonianian',
    name: '神道无念',
    description: '按技能等级提高灵力',
    icon: '🔮',
    factionId: 'faction_fangcun',
    bonusType: 'magicPower',
    bonusPerLevel: 2,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_qiantiangangqi', requiredLevel: 30 },
      { skillId: 'skill_fenshenshu', requiredLevel: 120, isAscension: true },
      { skillId: 'skill_shenbinghufa', requiredLevel: 35 },
    ],
  },
  {
    id: 'base_xieyuebu',
    name: '斜月步',
    description: '按技能等级提高躲避力',
    icon: '🌙',
    factionId: 'faction_fangcun',
    bonusType: 'dodge',
    bonusPerLevel: 1,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_yimuxiandun', requiredLevel: 1 },
    ],
  },
];

// ==================== 女儿村基础技能 ====================
export const NVER_BASE_SKILLS: BaseSkill[] = [
  {
    id: 'base_dujing',
    name: '毒经',
    description: '按技能等级提高伤害力',
    icon: '☠️',
    factionId: 'faction_nver',
    bonusType: 'damage',
    bonusPerLevel: 2,
    maxLevel: 160,
    unlockSkills: [],
  },
  {
    id: 'base_qingguoqingcheng',
    name: '倾国倾城',
    description: '倾国倾城之美',
    icon: '💃',
    factionId: 'faction_nver',
    bonusType: 'none',
    bonusPerLevel: 0,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_hongxiutianxiang', requiredLevel: 20 },
      { skillId: 'skill_chuchukelian', requiredLevel: 10 },
      { skillId: 'skill_yixiaoqingcheng', requiredLevel: 120, isAscension: true },
    ],
  },
  {
    id: 'base_chenyuluoyan',
    name: '沉鱼落雁',
    description: '沉鱼落雁之容',
    icon: '🌸',
    factionId: 'faction_nver',
    bonusType: 'none',
    bonusPerLevel: 0,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_mantian', requiredLevel: 25 },
      { skillId: 'skill_qingtianhenhai', requiredLevel: 25 },
      { skillId: 'skill_yuluohansha', requiredLevel: 20 },
    ],
  },
  {
    id: 'base_biyuexiuhua',
    name: '闭月羞花',
    description: '闭月羞花之貌',
    icon: '🌺',
    factionId: 'faction_nver',
    bonusType: 'none',
    bonusPerLevel: 0,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_lianbuqingwu', requiredLevel: 30 },
      { skillId: 'skill_ruahuajieyu', requiredLevel: 20 },
      { skillId: 'skill_siyushengxiang', requiredLevel: 40 },
      { skillId: 'skill_pingting', requiredLevel: 25 },
    ],
  },
  {
    id: 'base_xiangpiaolanxiang',
    name: '香飘兰麝',
    description: '按技能等级提高灵力',
    icon: '💐',
    factionId: 'faction_nver',
    bonusType: 'magicPower',
    bonusPerLevel: 2,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_qingruhongmao', requiredLevel: 35 },
    ],
  },
  {
    id: 'base_yuzhibingji',
    name: '玉质冰肌',
    description: '按技能等级提高防御力',
    icon: '❄️',
    factionId: 'faction_nver',
    bonusType: 'defense',
    bonusPerLevel: 2,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_baidubuqin', requiredLevel: 10 },
    ],
  },
  {
    id: 'base_qinggemiaowu',
    name: '清歌妙舞',
    description: '按技能等级提高速度',
    icon: '🎵',
    factionId: 'faction_nver',
    bonusType: 'speed',
    bonusPerLevel: 1,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_yixinghuanying', requiredLevel: 1 },
      { skillId: 'skill_feihuazhaiye', requiredLevel: 120, isAscension: true },
    ],
  },
];

// ==================== 龙宫基础技能 ====================
export const LONGGONG_BASE_SKILLS: BaseSkill[] = [
  {
    id: 'base_jiulongjue',
    name: '九龙诀',
    description: '按技能等级提高灵力',
    icon: '🐉',
    factionId: 'faction_longgong',
    bonusType: 'magicPower',
    bonusPerLevel: 2,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_jiefeng', requiredLevel: 30 },
      { skillId: 'skill_qingxin', requiredLevel: 15 },
      { skillId: 'skill_erlongxizhu', requiredLevel: 120, isAscension: true },
    ],
  },
  {
    id: 'base_polangjue',
    name: '破浪诀',
    description: '按技能等级提高伤害力',
    icon: '🌊',
    factionId: 'faction_longgong',
    bonusType: 'damage',
    bonusPerLevel: 2,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_shenlong', requiredLevel: 120, isAscension: true },
    ],
  },
  {
    id: 'base_hufenghuanyu',
    name: '呼风唤雨',
    description: '呼风唤雨之术',
    icon: '🌧️',
    factionId: 'faction_longgong',
    bonusType: 'none',
    bonusPerLevel: 0,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_longjuan', requiredLevel: 15 },
    ],
  },
  {
    id: 'base_longteng',
    name: '龙腾',
    description: '龙腾之术，单体攻击',
    icon: '🐲',
    factionId: 'faction_longgong',
    bonusType: 'none',
    bonusPerLevel: 0,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_longteng', requiredLevel: 50 },
    ],
  },
  {
    id: 'base_youlongshu',
    name: '游龙术',
    description: '按技能等级提高躲避力',
    icon: '🐲',
    factionId: 'faction_longgong',
    bonusType: 'dodge',
    bonusPerLevel: 1,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_chengfengpolang', requiredLevel: 20 },
      { skillId: 'skill_shuidun', requiredLevel: 1 },
    ],
  },
  {
    id: 'base_longfu',
    name: '龙附',
    description: '龙附之术',
    icon: '💫',
    factionId: 'faction_longgong',
    bonusType: 'none',
    bonusPerLevel: 0,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_longyin', requiredLevel: 30 },
      { skillId: 'skill_longxiaojiutian', requiredLevel: 25 },
      { skillId: 'skill_longfu', requiredLevel: 35 },
    ],
  },
  {
    id: 'base_nilin',
    name: '逆鳞',
    description: '逆鳞之术，提升伤害',
    icon: '🔥',
    factionId: 'faction_longgong',
    bonusType: 'none',
    bonusPerLevel: 0,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_nilin', requiredLevel: 30 },
    ],
  },
];

// ==================== 天宫基础技能 ====================
export const TIANGONG_BASE_SKILLS: BaseSkill[] = [
  {
    id: 'base_tiangangqi',
    name: '天罡气',
    description: '按技能等级提高伤害力',
    icon: '⚡',
    factionId: 'faction_tiangong',
    bonusType: 'damage',
    bonusPerLevel: 2,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_tianshenhuti', requiredLevel: 30 },
      { skillId: 'skill_tianshenhufa', requiredLevel: 40 },
      { skillId: 'skill_tianzhudimi', requiredLevel: 25 },
      { skillId: 'skill_wuleihongding', requiredLevel: 35 },
      { skillId: 'skill_leiting', requiredLevel: 50 },
      { skillId: 'skill_haoranqi', requiredLevel: 35 },
    ],
  },
  {
    id: 'base_aoshijue',
    name: '傲世诀',
    description: '按技能等级提高HP上限',
    icon: '💪',
    factionId: 'faction_tiangong',
    bonusType: 'hp',
    bonusPerLevel: 5,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_tianlei', requiredLevel: 25 },
    ],
  },
  {
    id: 'base_qingmingizaizai',
    name: '清明自在',
    description: '按技能等级提高灵力',
    icon: '👁️',
    factionId: 'faction_tiangong',
    bonusType: 'magicPower',
    bonusPerLevel: 2,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_zhijizhibi', requiredLevel: 35 },
    ],
  },
  {
    id: 'base_ningqijue',
    name: '宁气诀',
    description: '按技能等级提高防御力',
    icon: '🛡️',
    factionId: 'faction_tiangong',
    bonusType: 'defense',
    bonusPerLevel: 2,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_ningxin', requiredLevel: 20 },
    ],
  },
  {
    id: 'base_qiankunta',
    name: '乾坤塔',
    description: '乾坤塔法术',
    icon: '🏯',
    factionId: 'faction_tiangong',
    bonusType: 'none',
    bonusPerLevel: 0,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_zhenyao', requiredLevel: 30 },
      { skillId: 'skill_cuoluan', requiredLevel: 50 },
      { skillId: 'skill_zhangxinlei', requiredLevel: 50 },
    ],
  },
  {
    id: 'base_huntianshu',
    name: '混天术',
    description: '混天之法',
    icon: '🌀',
    factionId: 'faction_tiangong',
    bonusType: 'none',
    bonusPerLevel: 0,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_baiwanhenbing', requiredLevel: 40 },
      { skillId: 'skill_jingangjue', requiredLevel: 120, isAscension: true },
      { skillId: 'skill_tianleiguannzhu', requiredLevel: 120, isAscension: true },
    ],
  },
  {
    id: 'base_yunxiaobu',
    name: '云霄步',
    description: '按技能等级提高躲避力',
    icon: '☁️',
    factionId: 'faction_tiangong',
    bonusType: 'dodge',
    bonusPerLevel: 1,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_tengyunjiawu', requiredLevel: 1 },
    ],
  },
];

// ==================== 普陀山基础技能 ====================
export const PUTUO_BASE_SKILLS: BaseSkill[] = [
  {
    id: 'base_lingxing',
    name: '灵性',
    description: '按技能等级提高灵力',
    icon: '🌟',
    factionId: 'faction_putuo',
    bonusType: 'magicPower',
    bonusPerLevel: 2,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_zaixinxinfa', requiredLevel: 60 },
    ],
  },
  {
    id: 'base_hufajingang',
    name: '护法金刚',
    description: '按技能等级提高伤害力',
    icon: '⚔️',
    factionId: 'faction_putuo',
    bonusType: 'damage',
    bonusPerLevel: 2,
    maxLevel: 160,
    unlockSkills: [],
  },
  {
    id: 'base_guanyinzhou',
    name: '观音咒',
    description: '观音咒法',
    icon: '🙏',
    factionId: 'faction_putuo',
    bonusType: 'none',
    bonusPerLevel: 0,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_jinguzhou', requiredLevel: 30 },
      { skillId: 'skill_yangliu', requiredLevel: 20 },
    ],
  },
  {
    id: 'base_wuxingxueshuo',
    name: '五行学说',
    description: '五行之术',
    icon: '☯️',
    factionId: 'faction_putuo',
    bonusType: 'none',
    bonusPerLevel: 0,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_riguanghua', requiredLevel: 10 },
      { skillId: 'skill_diancanghai', requiredLevel: 11 },
      { skillId: 'skill_juyanpo', requiredLevel: 12 },
      { skillId: 'skill_cangmangshu', requiredLevel: 13 },
      { skillId: 'skill_diliehuo', requiredLevel: 14 },
    ],
  },
  {
    id: 'base_jingangjing',
    name: '金刚经',
    description: '金刚经法',
    icon: '📿',
    factionId: 'faction_putuo',
    bonusType: 'none',
    bonusPerLevel: 0,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_pudu', requiredLevel: 15 },
      { skillId: 'skill_lingdongjiutian', requiredLevel: 120, isAscension: true },
      { skillId: 'skill_lianhuamiaofa', requiredLevel: 35 },
    ],
  },
  {
    id: 'base_wuxingniuzhuan',
    name: '五行扭转',
    description: '按技能等级提高防御力',
    icon: '🔄',
    factionId: 'faction_putuo',
    bonusType: 'defense',
    bonusPerLevel: 2,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_wuxingcuowei', requiredLevel: 25 },
      { skillId: 'skill_diandaowuxing', requiredLevel: 120, isAscension: true },
    ],
  },
  {
    id: 'base_lianhuabaozuo',
    name: '莲花宝座',
    description: '按技能等级提高躲避力',
    icon: '🪷',
    factionId: 'faction_putuo',
    bonusType: 'dodge',
    bonusPerLevel: 1,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_zuolian', requiredLevel: 1 },
    ],
  },
];

// ==================== 五庄观基础技能 ====================
export const WUZHUANG_BASE_SKILLS: BaseSkill[] = [
  {
    id: 'base_zhouyixue',
    name: '周易学',
    description: '按技能等级提高MP上限',
    icon: '📖',
    factionId: 'faction_wuzhuang',
    bonusType: 'mp',
    bonusPerLevel: 5,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_qumo', requiredLevel: 25 },
      { skillId: 'skill_qushi', requiredLevel: 20 },
    ],
  },
  {
    id: 'base_xiaoxiangxianyu',
    name: '潇湘仙雨',
    description: '按技能等级提高伤害力',
    icon: '🌧️',
    factionId: 'faction_wuzhuang',
    bonusType: 'damage',
    bonusPerLevel: 2,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_yanyu', requiredLevel: 25 },
      { skillId: 'skill_piaomiao', requiredLevel: 20 },
    ],
  },
  {
    id: 'base_qiankunxiu',
    name: '乾坤袖',
    description: '乾坤袖法',
    icon: '🔮',
    factionId: 'faction_wuzhuang',
    bonusType: 'none',
    bonusPerLevel: 0,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_riyue', requiredLevel: 20 },
      { skillId: 'skill_tianditongshou', requiredLevel: 120, isAscension: true },
      { skillId: 'skill_qiankunmiaofa', requiredLevel: 120, isAscension: true },
    ],
  },
  {
    id: 'base_xiuxianshu',
    name: '修仙术',
    description: '修仙之术',
    icon: '🧘',
    factionId: 'faction_wuzhuang',
    bonusType: 'none',
    bonusPerLevel: 0,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_lianqihuashen', requiredLevel: 30 },
      { skillId: 'skill_shengmingzhiquan', requiredLevel: 30 },
      { skillId: 'skill_taijishenhua', requiredLevel: 25 },
      { skillId: 'skill_yiqihuasanqing', requiredLevel: 35 },
    ],
  },
  {
    id: 'base_hunyuandaoguo',
    name: '混元道果',
    description: '按技能等级提高灵力',
    icon: '🍎',
    factionId: 'faction_wuzhuang',
    bonusType: 'magicPower',
    bonusPerLevel: 2,
    maxLevel: 160,
    unlockSkills: [],
  },
  {
    id: 'base_mingxiuxiushen',
    name: '明性修身',
    description: '按技能等级提高防御力',
    icon: '🛡️',
    factionId: 'faction_wuzhuang',
    bonusType: 'defense',
    bonusPerLevel: 2,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_sanhualjuding', requiredLevel: 30 },
    ],
  },
  {
    id: 'base_qixingdun',
    name: '七星遁',
    description: '按技能等级提高躲避力',
    icon: '⭐',
    factionId: 'faction_wuzhuang',
    bonusType: 'dodge',
    bonusPerLevel: 1,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_douzhuanyanxing', requiredLevel: 1 },
    ],
  },
];

// ==================== 狮驼岭基础技能 ====================
export const SHITUO_BASE_SKILLS: BaseSkill[] = [
  {
    id: 'base_moshoushengong',
    name: '魔兽神功',
    description: '魔兽神功',
    icon: '🦁',
    factionId: 'faction_shituo',
    bonusType: 'none',
    bonusPerLevel: 0,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_bianshen', requiredLevel: 20 },
      { skillId: 'skill_moshouxiaotian', requiredLevel: 25 },
    ],
  },
  {
    id: 'base_shengsibo',
    name: '生死搏',
    description: '按技能等级提高伤害力',
    icon: '⚔️',
    factionId: 'faction_shituo',
    bonusType: 'damage',
    bonusPerLevel: 3,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_xiangxing', requiredLevel: 20 },
      { skillId: 'skill_yingji', requiredLevel: 30 },
      { skillId: 'skill_shibo', requiredLevel: 20 },
      { skillId: 'skill_tianmojieti', requiredLevel: 120, isAscension: true },
    ],
  },
  {
    id: 'base_xunshoujue',
    name: '训兽诀',
    description: '按技能等级提高灵力',
    icon: '🐾',
    factionId: 'faction_shituo',
    bonusType: 'magicPower',
    bonusPerLevel: 2,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_weishe', requiredLevel: 15 },
    ],
  },
  {
    id: 'base_yinyangerqijue',
    name: '阴阳二气诀',
    description: '阴阳二气',
    icon: '☯️',
    factionId: 'faction_shituo',
    bonusType: 'none',
    bonusPerLevel: 0,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_dingxin', requiredLevel: 40 },
      { skillId: 'skill_moshushu', requiredLevel: 120, isAscension: true },
    ],
  },
  {
    id: 'base_kuangshoujue',
    name: '狂兽诀',
    description: '狂兽之法',
    icon: '🔥',
    factionId: 'faction_shituo',
    bonusType: 'none',
    bonusPerLevel: 0,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_lianhuji', requiredLevel: 30 },
      { skillId: 'skill_shenliwuxian', requiredLevel: 35 },
    ],
  },
  {
    id: 'base_dapengzhanqie',
    name: '大鹏展翅',
    description: '按技能等级提高躲避力',
    icon: '🦅',
    factionId: 'faction_shituo',
    bonusType: 'dodge',
    bonusPerLevel: 1,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_zhenchiqianli', requiredLevel: 1 },
    ],
  },
  {
    id: 'base_moshoufanshi',
    name: '魔兽反噬',
    description: '按技能等级提高防御力',
    icon: '🛡️',
    factionId: 'faction_shituo',
    bonusType: 'defense',
    bonusPerLevel: 2,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_jidufengkuang', requiredLevel: 20 },
    ],
  },
];

// ==================== 魔王寨基础技能 ====================
export const MOWANG_BASE_SKILLS: BaseSkill[] = [
  {
    id: 'base_niubishengong',
    name: '牛逼神功',
    description: '牛逼神功',
    icon: '💪',
    factionId: 'faction_mowang',
    bonusType: 'none',
    bonusPerLevel: 0,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_mowanghuchi', requiredLevel: 35 },
    ],
  },
  {
    id: 'base_zhentianjue',
    name: '震天诀',
    description: '按技能等级提高伤害力',
    icon: '💥',
    factionId: 'faction_mowang',
    bonusType: 'damage',
    bonusPerLevel: 2,
    maxLevel: 160,
    unlockSkills: [],
  },
  {
    id: 'base_huoyunshu',
    name: '火云术',
    description: '火云之术',
    icon: '🔥',
    factionId: 'faction_mowang',
    bonusType: 'none',
    bonusPerLevel: 0,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_feisha', requiredLevel: 30 },
      { skillId: 'skill_sanmei', requiredLevel: 20 },
      { skillId: 'skill_huojiashu', requiredLevel: 120, isAscension: true },
    ],
  },
  {
    id: 'base_huoniuzhen',
    name: '火牛阵',
    description: '按技能等级提高灵力',
    icon: '🐂',
    factionId: 'faction_mowang',
    bonusType: 'magicPower',
    bonusPerLevel: 2,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_niujin', requiredLevel: 30 },
      { skillId: 'skill_tashanlieshi', requiredLevel: 25 },
    ],
  },
  {
    id: 'base_niushizhen',
    name: '牛虱阵',
    description: '牛虱之阵',
    icon: '🐛',
    factionId: 'faction_mowang',
    bonusType: 'none',
    bonusPerLevel: 0,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_wudiniush', requiredLevel: 25 },
      { skillId: 'skill_wudiniuyao', requiredLevel: 25 },
      { skillId: 'skill_yaotoubaiwei', requiredLevel: 120, isAscension: true },
    ],
  },
  {
    id: 'base_huishenji',
    name: '回身击',
    description: '按技能等级提高防御力',
    icon: '🛡️',
    factionId: 'faction_mowang',
    bonusType: 'defense',
    bonusPerLevel: 2,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_mowanghuishou', requiredLevel: 30 },
    ],
  },
  {
    id: 'base_liesibu',
    name: '裂石步',
    description: '按技能等级提高躲避力',
    icon: '🪨',
    factionId: 'faction_mowang',
    bonusType: 'dodge',
    bonusPerLevel: 1,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_niushidun', requiredLevel: 1 },
    ],
  },
];

// ==================== 阴曹地府基础技能 ====================
export const DIFU_BASE_SKILLS: BaseSkill[] = [
  {
    id: 'base_lingtongshu',
    name: '灵通术',
    description: '灵通之术',
    icon: '👁️',
    factionId: 'faction_difu',
    bonusType: 'none',
    bonusPerLevel: 0,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_kanchaling', requiredLevel: 5 },
      { skillId: 'skill_gaoyuling', requiredLevel: 30 },
    ],
  },
  {
    id: 'base_liudalunhui',
    name: '六道轮回',
    description: '按技能等级提高伤害力',
    icon: '🔄',
    factionId: 'faction_difu',
    bonusType: 'damage',
    bonusPerLevel: 2,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_hunfeiposan', requiredLevel: 50 },
    ],
  },
  {
    id: 'base_youmingshu',
    name: '幽冥术',
    description: '幽冥之术',
    icon: '💀',
    factionId: 'faction_difu',
    bonusType: 'none',
    bonusPerLevel: 0,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_yanluo', requiredLevel: 25 },
      { skillId: 'skill_guhunshu', requiredLevel: 75 },
      { skillId: 'skill_huangquanzhixi', requiredLevel: 120, isAscension: true },
    ],
  },
  {
    id: 'base_jushenjue',
    name: '拘魂诀',
    description: '拘魂之诀',
    icon: '👻',
    factionId: 'faction_difu',
    bonusType: 'none',
    bonusPerLevel: 0,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_panguan', requiredLevel: 20 },
      { skillId: 'skill_huanyangshu', requiredLevel: 120, isAscension: true },
      { skillId: 'skill_shiqimantian', requiredLevel: 35 },
    ],
  },
  {
    id: 'base_jiuyiyouhun',
    name: '九幽阴魂',
    description: '按技能等级提高灵力',
    icon: '🌑',
    factionId: 'faction_difu',
    bonusType: 'magicPower',
    bonusPerLevel: 2,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_youmingguiyan', requiredLevel: 30 },
      { skillId: 'skill_yuanhunbusan', requiredLevel: 25 },
    ],
  },
  {
    id: 'base_shifu',
    name: '尸腐恶',
    description: '按技能等级提高防御力',
    icon: '☠️',
    factionId: 'faction_difu',
    bonusType: 'defense',
    bonusPerLevel: 2,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_shifu', requiredLevel: 20 },
      { skillId: 'skill_xiuluoyinshen', requiredLevel: 20 },
    ],
  },
  {
    id: 'base_wuchangbu',
    name: '无常步',
    description: '按技能等级提高躲避力',
    icon: '👣',
    factionId: 'faction_difu',
    bonusType: 'dodge',
    bonusPerLevel: 1,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_yaowuyinxun', requiredLevel: 1 },
    ],
  },
];

// ==================== 盘丝洞基础技能 ====================
export const PANSI_BASE_SKILLS: BaseSkill[] = [
  {
    id: 'base_zhusizhenfa',
    name: '蛛丝阵法',
    description: '按技能等级提高防御力',
    icon: '🕸️',
    factionId: 'faction_pansi',
    bonusType: 'defense',
    bonusPerLevel: 2,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_pansiwu', requiredLevel: 35 },
      { skillId: 'skill_duomingsusi', requiredLevel: 25 },
    ],
  },
  {
    id: 'base_miqingdafa',
    name: '迷情大法',
    description: '迷情之法',
    icon: '💋',
    factionId: 'faction_pansi',
    bonusType: 'none',
    bonusPerLevel: 0,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_hanqingmaimai', requiredLevel: 30 },
      { skillId: 'skill_zhangqi_pansi', requiredLevel: 120, isAscension: true },
      { skillId: 'skill_moyinshexin', requiredLevel: 45 },
    ],
  },
  {
    id: 'base_qiuboansong',
    name: '秋波暗送',
    description: '按技能等级提高命中',
    icon: '👁️',
    factionId: 'faction_pansi',
    bonusType: 'hitRate',
    bonusPerLevel: 2,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_gouhun', requiredLevel: 20 },
      { skillId: 'skill_shepo', requiredLevel: 20 },
    ],
  },
  {
    id: 'base_tianwaimoyin',
    name: '天外魔音',
    description: '按技能等级提高灵力',
    icon: '🎵',
    factionId: 'faction_pansi',
    bonusType: 'magicPower',
    bonusPerLevel: 2,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_moyinshexin', requiredLevel: 45 },
    ],
  },
  {
    id: 'base_pansidafa',
    name: '盘丝大法',
    description: '按技能等级提高伤害力',
    icon: '🕷️',
    factionId: 'faction_pansi',
    bonusType: 'damage',
    bonusPerLevel: 2,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_pansi', requiredLevel: 20 },
      { skillId: 'skill_fusu', requiredLevel: 20 },
    ],
  },
  {
    id: 'base_yixinghuanying',
    name: '移形换影',
    description: '按技能等级提高躲避力',
    icon: '🌀',
    factionId: 'faction_pansi',
    bonusType: 'dodge',
    bonusPerLevel: 1,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_tianluodiwang', requiredLevel: 15 },
      { skillId: 'skill_tiancansi', requiredLevel: 1 },
      { skillId: 'skill_huanjingshu', requiredLevel: 120, isAscension: true },
    ],
  },
  {
    id: 'base_zimeixiangsui',
    name: '姊妹相随',
    description: '姊妹相随之术',
    icon: '👭',
    factionId: 'faction_pansi',
    bonusType: 'none',
    bonusPerLevel: 0,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_jiemeitongxin', requiredLevel: 20 },
    ],
  },
];

// ==================== 神木林基础技能 ====================
export const SHENMULIN_BASE_SKILLS: BaseSkill[] = [
  {
    id: 'base_shunxiwanbian',
    name: '瞬息万变',
    description: '瞬息万变之术',
    icon: '🍃',
    factionId: 'faction_shenmulin',
    bonusType: 'none',
    bonusPerLevel: 0,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_luoyexiaoxiao', requiredLevel: 35 },
    ],
  },
  {
    id: 'base_wanlingzhunian',
    name: '万灵诸念',
    description: '按技能等级提高灵力',
    icon: '🌲',
    factionId: 'faction_shenmulin',
    bonusType: 'magicPower',
    bonusPerLevel: 2,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_jingjiwu', requiredLevel: 20 },
      { skillId: 'skill_chenturen', requiredLevel: 20 },
      { skillId: 'skill_bingchuannu', requiredLevel: 20 },
    ],
  },
  {
    id: 'base_wuzhou',
    name: '巫咒',
    description: '按技能等级提高伤害力',
    icon: '🔮',
    factionId: 'faction_shenmulin',
    bonusType: 'damage',
    bonusPerLevel: 2,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_wusha', requiredLevel: 40 },
      { skillId: 'skill_xueyu', requiredLevel: 120, isAscension: true },
    ],
  },
  {
    id: 'base_wanwulunzhuan',
    name: '万物轮转',
    description: '按技能等级提高防御力',
    icon: '🔄',
    factionId: 'faction_shenmulin',
    bonusType: 'defense',
    bonusPerLevel: 2,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_xingyuezhihui', requiredLevel: 35 },
    ],
  },
  {
    id: 'base_tianrenbihu',
    name: '天人庇护',
    description: '按技能等级提高躲避力',
    icon: '🛡️',
    factionId: 'faction_shenmulin',
    bonusType: 'dodge',
    bonusPerLevel: 1,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_yanhu', requiredLevel: 50 },
      { skillId: 'skill_yeyin', requiredLevel: 1 },
    ],
  },
  {
    id: 'base_shenmuenze',
    name: '神木恩泽',
    description: '神木恩泽',
    icon: '✨',
    factionId: 'faction_shenmulin',
    bonusType: 'none',
    bonusPerLevel: 0,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_shenmuyiyu', requiredLevel: 35 },
    ],
  },
  {
    id: 'base_yulingzhou',
    name: '驭灵咒',
    description: '按技能等级提高MP上限',
    icon: '📜',
    factionId: 'faction_shenmulin',
    bonusType: 'mp',
    bonusPerLevel: 5,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_mirun', requiredLevel: 120, isAscension: true },
      { skillId: 'skill_louyishitian', requiredLevel: 25 },
    ],
  },
];

// ==================== 天机城基础技能 ====================
export const TIANJICHENG_BASE_SKILLS: BaseSkill[] = [
  {
    id: 'base_shengongwuxing',
    name: '神工无形',
    description: '以神为意，方可御甲万里',
    icon: '⚙️',
    factionId: 'faction_tianjicheng',
    bonusType: 'none',
    bonusPerLevel: 0,
    maxLevel: 160,
    unlockSkills: [],
  },
  {
    id: 'base_gongyuyishi',
    name: '攻玉以石',
    description: '他山之石，可以攻玉',
    icon: '💎',
    factionId: 'faction_tianjicheng',
    bonusType: 'none',
    bonusPerLevel: 0,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_zhenfengxiangdui', requiredLevel: 25 },
      { skillId: 'skill_gongshouyiwei', requiredLevel: 120, isAscension: true },
    ],
  },
  {
    id: 'base_qingtianzhixie',
    name: '擎天之械',
    description: '吾有偃甲，擎天蔽日',
    icon: '🤖',
    factionId: 'faction_tianjicheng',
    bonusType: 'none',
    bonusPerLevel: 0,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_fengmangbilu', requiredLevel: 25 },
    ],
  },
  {
    id: 'base_qianjiqiqiao',
    name: '千机奇巧',
    description: '偃甲机簧精妙',
    icon: '🔧',
    factionId: 'faction_tianjicheng',
    bonusType: 'none',
    bonusPerLevel: 0,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_youxi', requiredLevel: 45 },
      { skillId: 'skill_poji', requiredLevel: 1 },
    ],
  },
  {
    id: 'base_jiangxinbuyi',
    name: '匠心不移',
    description: '按技能等级提高伤害力',
    icon: '🔨',
    factionId: 'faction_tianjicheng',
    bonusType: 'damage',
    bonusPerLevel: 2,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_jiangxin_xiaotie', requiredLevel: 120, isAscension: true },
      { skillId: 'skill_jiangxin_gujia', requiredLevel: 35 },
      { skillId: 'skill_jiangxin_xurui', requiredLevel: 25 },
    ],
  },
  {
    id: 'base_yunsirudian',
    name: '运思如电',
    description: '按技能等级提高躲避力',
    icon: '⚡',
    factionId: 'faction_tianjicheng',
    bonusType: 'dodge',
    bonusPerLevel: 1,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_tianmaxingkong_tianjicheng', requiredLevel: 1 },
    ],
  },
  {
    id: 'base_tanaosuoyin',
    name: '探奥索隐',
    description: '引首以望，吾辈意在苍穹',
    icon: '🔭',
    factionId: 'faction_tianjicheng',
    bonusType: 'none',
    bonusPerLevel: 0,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_guifushengong', requiredLevel: 35 },
      { skillId: 'skill_yishantianhai', requiredLevel: 25 },
    ],
  },
];

// ==================== 九黎城基础技能 ====================
export const JIULICHENG_BASE_SKILLS: BaseSkill[] = [
  {
    id: 'base_jiulizhange_jl',
    name: '九黎战歌',
    description: '战鼓铿锵，战魂不息，九黎之歌荡涤天地，激昂族人之志',
    icon: '📯',
    factionId: 'faction_jiulicheng',
    bonusType: 'none',
    bonusPerLevel: 0,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_lihun_jl', requiredLevel: 1 },
      { skillId: 'skill_zhangu_jl', requiredLevel: 1 },
      { skillId: 'skill_nuxiao_jl', requiredLevel: 1 },
      { skillId: 'skill_yanhun_jl', requiredLevel: 1 },
    ],
  },
  {
    id: 'base_hunfengzhanwu_jl',
    name: '魂枫战舞',
    description: '按技能等级提高伤害',
    icon: '🍁',
    factionId: 'faction_jiulicheng',
    bonusType: 'damage',
    bonusPerLevel: 3,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_fengyingerre_jl', requiredLevel: 1 },
    ],
  },
  {
    id: 'base_bingzhuqiankun_jl',
    name: '兵铸乾坤',
    description: '按技能等级提高灵力',
    icon: '⚔️',
    factionId: 'faction_jiulicheng',
    bonusType: 'magicPower',
    bonusPerLevel: 2,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_yifukaitian_jl', requiredLevel: 30 },
    ],
  },
  {
    id: 'base_rantiefeihua_jl',
    name: '燃铁飞花',
    description: '按技能等级提高命中',
    icon: '🔥',
    factionId: 'faction_jiulicheng',
    bonusType: 'hitRate',
    bonusPerLevel: 2,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_sanhuangjinmie_jl', requiredLevel: 30 },
    ],
  },
  {
    id: 'base_zhanhuoxionghun_jl',
    name: '战火雄魂',
    description: '按技能等级提高防御',
    icon: '🛡️',
    factionId: 'faction_jiulicheng',
    bonusType: 'defense',
    bonusPerLevel: 2,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_tiexueshengfeng_jl', requiredLevel: 30 },
    ],
  },
  {
    id: 'base_moshenjiangshi_jl',
    name: '魔神降世',
    description: '聆听兵主密命，得赐魔神之力，战无不胜，天地可征',
    icon: '👹',
    factionId: 'faction_jiulicheng',
    bonusType: 'none',
    bonusPerLevel: 0,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_libicangqiong_jl', requiredLevel: 30 },
    ],
  },
  {
    id: 'base_fengxingjiuli_jl',
    name: '风行九黎',
    description: '按技能等级提高躲避',
    icon: '💨',
    factionId: 'faction_jiulicheng',
    bonusType: 'dodge',
    bonusPerLevel: 1,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_guraiguixin_jl', requiredLevel: 1 },
    ],
  },
];

// ==================== 东海渊基础技能 ====================
export const DONGHAIYUAN_BASE_SKILLS: BaseSkill[] = [
  {
    id: 'base_shenhaiyiyu_dh',
    name: '深海呓语',
    description: '深海潮汐，暗涌之力，沉睡之时，梦魇将至',
    icon: '🌊',
    factionId: 'faction_donghaiyuan',
    bonusType: 'none',
    bonusPerLevel: 0,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_lingyin_dh', requiredLevel: 1 },
      { skillId: 'skill_chenmo_dh', requiredLevel: 1 },
      { skillId: 'skill_xiongyong_dh', requiredLevel: 1 },
    ],
  },
  {
    id: 'base_hundunzhimi_dh',
    name: '混沌之谜',
    description: '按技能等级提高伤害',
    icon: '🌀',
    factionId: 'faction_donghaiyuan',
    bonusType: 'damage',
    bonusPerLevel: 3,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_wazhiying_dh', requiredLevel: 1 },
    ],
  },
  {
    id: 'base_yuanguzhijing_dh',
    name: '远古之境',
    description: '按技能等级提高防御',
    icon: '🏛️',
    factionId: 'faction_donghaiyuan',
    bonusType: 'defense',
    bonusPerLevel: 2,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_chongzhishi_dh', requiredLevel: 1 },
    ],
  },
  {
    id: 'base_changshengzisi_dh',
    name: '长生之祀',
    description: '按技能等级提高法防',
    icon: '🐢',
    factionId: 'faction_donghaiyuan',
    bonusType: 'defense',
    bonusPerLevel: 2,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_guizhixiang_dh', requiredLevel: 1 },
    ],
  },
  {
    id: 'base_chaoxizhizhou_dh',
    name: '潮汐之咒',
    description: '按技能等级提高魔法',
    icon: '💧',
    factionId: 'faction_donghaiyuan',
    bonusType: 'mp',
    bonusPerLevel: 10,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_senluowanxiang_dh', requiredLevel: 30 },
      { skillId: 'skill_haishishenlou_dh', requiredLevel: 60 },
      { skillId: 'skill_shenyouwuwai_dh', requiredLevel: 30 },
    ],
  },
  {
    id: 'base_chengxinzilan_dh',
    name: '澄心之浪',
    description: '按技能等级提高法伤',
    icon: '💙',
    factionId: 'faction_donghaiyuan',
    bonusType: 'magicPower',
    bonusPerLevel: 2,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_wanliyanbo_dh', requiredLevel: 30 },
      { skillId: 'skill_didang_dh', requiredLevel: 1 },
      { skillId: 'skill_anyong_dh', requiredLevel: 60 },
    ],
  },
  {
    id: 'base_aoyou_dh',
    name: '遨游',
    description: '按技能等级提高躲避',
    icon: '🐠',
    factionId: 'faction_donghaiyuan',
    bonusType: 'dodge',
    bonusPerLevel: 1,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_suibosuilang_dh', requiredLevel: 1 },
    ],
  },
];

// ==================== 凌波城基础技能 ====================
export const LINGBOCHENG_BASE_SKILLS: BaseSkill[] = [
  {
    id: 'base_tiandiwuji',
    name: '天地无极',
    description: '战意之源，用于发动门派法术',
    icon: '⚡',
    factionId: 'faction_lingbocheng',
    bonusType: 'none',
    bonusPerLevel: 0,
    maxLevel: 160,
    unlockSkills: [],
  },
  {
    id: 'base_jiuzhuanxuangong',
    name: '九转玄功',
    description: '九转玄功',
    icon: '🌀',
    factionId: 'faction_lingbocheng',
    bonusType: 'none',
    bonusPerLevel: 0,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_budongrushan', requiredLevel: 25 },
    ],
  },
  {
    id: 'base_wushenxiansheng',
    name: '武神显圣',
    description: '武神显圣',
    icon: '⚔️',
    factionId: 'faction_lingbocheng',
    bonusType: 'none',
    bonusPerLevel: 0,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_suixingjue', requiredLevel: 30 },
      { skillId: 'skill_zhenhunjue', requiredLevel: 120, isAscension: true },
    ],
  },
  {
    id: 'base_xiaoao',
    name: '啸傲',
    description: '按技能等级提高灵力',
    icon: '🌊',
    factionId: 'faction_lingbocheng',
    bonusType: 'magicPower',
    bonusPerLevel: 2,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_chuanyunpokong', requiredLevel: 35 },
    ],
  },
  {
    id: 'base_qitunshanhe',
    name: '气吞山河',
    description: '按技能等级提高伤害力',
    icon: '🏔️',
    factionId: 'faction_lingbocheng',
    bonusType: 'damage',
    bonusPerLevel: 3,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_lieshi', requiredLevel: 25 },
      { skillId: 'skill_langyong', requiredLevel: 25 },
      { skillId: 'skill_duanyueshi', requiredLevel: 35 },
      { skillId: 'skill_jingtaonnu', requiredLevel: 35 },
      { skillId: 'skill_tianbengdilie', requiredLevel: 45 },
      { skillId: 'skill_fanjiangjiaohai', requiredLevel: 45 },
    ],
  },
  {
    id: 'base_zhumo',
    name: '诛魔',
    description: '按技能等级提高防御力',
    icon: '🛡️',
    factionId: 'faction_lingbocheng',
    bonusType: 'defense',
    bonusPerLevel: 2,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_tenglei', requiredLevel: 120, isAscension: true },
      { skillId: 'skill_zhidichenggang', requiredLevel: 25 },
    ],
  },
  {
    id: 'base_fatianxiangdi',
    name: '法天象地',
    description: '按技能等级提高命中',
    icon: '👁️',
    factionId: 'faction_lingbocheng',
    bonusType: 'hitRate',
    bonusPerLevel: 2,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_wuqiongmiaodao', requiredLevel: 30 },
      { skillId: 'skill_zongdijinguang', requiredLevel: 1 },
    ],
  },
];

// ==================== 花果山基础技能 ====================
export const HUAGUOSHAN_BASE_SKILLS: BaseSkill[] = [
  {
    id: 'base_shentongguangda',
    name: '神通广大',
    description: '齐天大圣法术之高，神通广大',
    icon: '🐵',
    factionId: 'faction_huaguoshan',
    bonusType: 'none',
    bonusPerLevel: 0,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_weizhenlingxiao', requiredLevel: 120, isAscension: true },
      { skillId: 'skill_qishetianjun', requiredLevel: 120, isAscension: true },
    ],
  },
  {
    id: 'base_ruyijingu',
    name: '如意金箍',
    description: '定海神针棒法',
    icon: '🏏',
    factionId: 'faction_huaguoshan',
    bonusType: 'damage',
    bonusPerLevel: 3,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_dangtouyibang', requiredLevel: 1 },
      { skillId: 'skill_shenzhenhanhai', requiredLevel: 1 },
      { skillId: 'skill_shaweitiebang', requiredLevel: 1 },
      { skillId: 'skill_potianluanbang', requiredLevel: 1 },
    ],
  },
  {
    id: 'base_qitianchengsheng',
    name: '齐天逞胜',
    description: '齐天大圣之威仪',
    icon: '👑',
    factionId: 'faction_huaguoshan',
    bonusType: 'none',
    bonusPerLevel: 0,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_jiuyouchuming', requiredLevel: 1 },
      { skillId: 'skill_yixinghuandou', requiredLevel: 15 },
      { skillId: 'skill_yunantianhun', requiredLevel: 1 },
    ],
  },
  {
    id: 'base_jingangzhiqu',
    name: '金刚之躯',
    description: '按技能等级提高防御力',
    icon: '🗿',
    factionId: 'faction_huaguoshan',
    bonusType: 'defense',
    bonusPerLevel: 2,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_danshanganyue', requiredLevel: 35 },
      { skillId: 'skill_tongtoutiebi', requiredLevel: 1 },
    ],
  },
  {
    id: 'base_linghoujiuqiao',
    name: '灵猴九窍',
    description: '按技能等级提高命中',
    icon: '🎯',
    factionId: 'faction_huaguoshan',
    bonusType: 'hitRate',
    bonusPerLevel: 2,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_wusuodunxing', requiredLevel: 1 },
      { skillId: 'skill_chuguangxiyan', requiredLevel: 25 },
    ],
  },
  {
    id: 'base_qishierbian',
    name: '七十二变',
    description: '地煞七十二般变化',
    icon: '🎭',
    factionId: 'faction_huaguoshan',
    bonusType: 'magicPower',
    bonusPerLevel: 2,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_huzihunsun', requiredLevel: 10 },
      { skillId: 'skill_bajieshangshen', requiredLevel: 45 },
    ],
  },
  {
    id: 'base_tengyunjiawu',
    name: '腾云驾雾',
    description: '按技能等级提高躲避力',
    icon: '☁️',
    factionId: 'faction_huaguoshan',
    bonusType: 'dodge',
    bonusPerLevel: 1,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_jindouyun', requiredLevel: 1 },
    ],
  },
];

// ==================== 无底洞基础技能 ====================
export const WUDIDONG_BASE_SKILLS: BaseSkill[] = [
  {
    id: 'base_kuguxinfa',
    name: '枯骨心法',
    description: '枯骨心法',
    icon: '💀',
    factionId: 'faction_wudidong',
    bonusType: 'none',
    bonusPerLevel: 0,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_yihunhuagu', requiredLevel: 20 },
    ],
  },
  {
    id: 'base_yinfengjuezhang',
    name: '阴风绝章',
    description: '阴风绝章',
    icon: '🌀',
    factionId: 'faction_wudidong',
    bonusType: 'none',
    bonusPerLevel: 0,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_duopoling', requiredLevel: 25 },
      { skillId: 'skill_shaqijue_wdd', requiredLevel: 30 },
      { skillId: 'skill_jinghunzhang', requiredLevel: 50 },
      { skillId: 'skill_cuixinshu', requiredLevel: 120, isAscension: true },
    ],
  },
  {
    id: 'base_guigulingyun',
    name: '鬼蛊灵蕴',
    description: '按技能等级提高灵力',
    icon: '👻',
    factionId: 'faction_wudidong',
    bonusType: 'magicPower',
    bonusPerLevel: 2,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_duomingzhou', requiredLevel: 35 },
    ],
  },
  {
    id: 'base_randenglingbao',
    name: '燃灯灵宝',
    description: '按技能等级提高防御力',
    icon: '🏮',
    factionId: 'faction_wudidong',
    bonusType: 'defense',
    bonusPerLevel: 2,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_mingguangbaozhu', requiredLevel: 35 },
      { skillId: 'skill_jinshensheli', requiredLevel: 120, isAscension: true },
    ],
  },
  {
    id: 'base_dimingmiaofa',
    name: '地冥妙法',
    description: '地冥妙法',
    icon: '🌍',
    factionId: 'faction_wudidong',
    bonusType: 'none',
    bonusPerLevel: 0,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_diyongjinlian', requiredLevel: 20 },
      { skillId: 'skill_wanmutiaoku', requiredLevel: 25 },
    ],
  },
  {
    id: 'base_hunyuanshengong',
    name: '混元神功',
    description: '按技能等级提高伤害力',
    icon: '💫',
    factionId: 'faction_wudidong',
    bonusType: 'damage',
    bonusPerLevel: 2,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_yuanyanghuti', requiredLevel: 35 },
    ],
  },
  {
    id: 'base_miyingmizong',
    name: '秘影迷踪',
    description: '按技能等级提高速度',
    icon: '👤',
    factionId: 'faction_wudidong',
    bonusType: 'speed',
    bonusPerLevel: 1,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_dundishu', requiredLevel: 1 },
    ],
  },
];

// ==================== 女魃墓基础技能 ====================
export const NVBAOMU_BASE_SKILLS: BaseSkill[] = [
  {
    id: 'base_tianhuoxianshi',
    name: '天火献誓',
    description: '天女魃操纵天火的神力',
    icon: '🔥',
    factionId: 'faction_nvbaomu',
    bonusType: 'none',
    bonusPerLevel: 0,
    maxLevel: 160,
    unlockSkills: [],
  },
  {
    id: 'base_tianfaizhiyan',
    name: '天罚之焰',
    description: '按技能等级提高灵力',
    icon: '⚡',
    factionId: 'faction_nvbaomu',
    bonusType: 'magicPower',
    bonusPerLevel: 2,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_chihuoliuli', requiredLevel: 10 },
      { skillId: 'skill_jitianlianyan', requiredLevel: 25 },
    ],
  },
  {
    id: 'base_huanghuowuming',
    name: '煌火无明',
    description: '煌火无明，魂梦成魇',
    icon: '🌑',
    factionId: 'faction_nvbaomu',
    bonusType: 'none',
    bonusPerLevel: 0,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_miduzhifu', requiredLevel: 15 },
      { skillId: 'skill_guifuzhixing', requiredLevel: 10 },
      { skillId: 'skill_yuanbuzhiki', requiredLevel: 30 },
      { skillId: 'skill_shixuezhiji', requiredLevel: 40 },
    ],
  },
  {
    id: 'base_huashenyiling',
    name: '化神以灵',
    description: '化神以灵，怨而化魔',
    icon: '👁️',
    factionId: 'faction_nvbaomu',
    bonusType: 'none',
    bonusPerLevel: 0,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_huanling_hunhuo', requiredLevel: 1 },
      { skillId: 'skill_huanmo_duoyu', requiredLevel: 20 },
      { skillId: 'skill_huanmo_dumei', requiredLevel: 120, isAscension: true },
      { skillId: 'skill_huanling_fenhun', requiredLevel: 120, isAscension: true },
    ],
  },
  {
    id: 'base_tanzhichengjin',
    name: '弹指成烬',
    description: '按技能等级提高防御力',
    icon: '💫',
    factionId: 'faction_nvbaomu',
    bonusType: 'defense',
    bonusPerLevel: 2,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_jingshihuanghuo', requiredLevel: 25 },
      { skillId: 'skill_fenmolieyan', requiredLevel: 35 },
    ],
  },
  {
    id: 'base_zaoguanglingyu',
    name: '藻光灵狱',
    description: '三珠玄木，灵光盈盈',
    icon: '🌿',
    factionId: 'faction_nvbaomu',
    bonusType: 'none',
    bonusPerLevel: 0,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_youyinglingpo', requiredLevel: 35 },
    ],
  },
  {
    id: 'base_lihun',
    name: '离魂',
    description: '按技能等级提高速度',
    icon: '💨',
    factionId: 'faction_nvbaomu',
    bonusType: 'speed',
    bonusPerLevel: 1,
    maxLevel: 160,
    unlockSkills: [
      { skillId: 'skill_hunxiguilai', requiredLevel: 1 },
    ],
  },
];

// ==================== 所有基础技能汇总 ====================
export const ALL_BASE_SKILLS: BaseSkill[] = [
  ...DATANG_BASE_SKILLS,
  ...HUASHENG_BASE_SKILLS,
  ...FANGCUN_BASE_SKILLS,
  ...NVER_BASE_SKILLS,
  ...LONGGONG_BASE_SKILLS,
  ...TIANGONG_BASE_SKILLS,
  ...PUTUO_BASE_SKILLS,
  ...WUZHUANG_BASE_SKILLS,
  ...SHITUO_BASE_SKILLS,
  ...MOWANG_BASE_SKILLS,
  ...DIFU_BASE_SKILLS,
  ...PANSI_BASE_SKILLS,
  ...SHENMULIN_BASE_SKILLS,
  ...TIANJICHENG_BASE_SKILLS,
  ...JIULICHENG_BASE_SKILLS,
  ...DONGHAIYUAN_BASE_SKILLS,
  ...LINGBOCHENG_BASE_SKILLS,
  ...HUAGUOSHAN_BASE_SKILLS,
  ...WUDIDONG_BASE_SKILLS,
  ...NVBAOMU_BASE_SKILLS,
];

/** 按门派ID获取基础技能列表 */
export function getBaseSkillsByFaction(factionId: string): BaseSkill[] {
  return ALL_BASE_SKILLS.filter(skill => skill.factionId === factionId);
}

/** 获取基础技能配置 */
export function getBaseSkill(skillId: string): BaseSkill | undefined {
  return ALL_BASE_SKILLS.find(skill => skill.id === skillId);
}

/** 获取主动技能所需的基础技能信息 */
export function getBaseSkillRequirement(skillId: string): { baseSkillId: string; requiredLevel: number } | null {
  for (const baseSkill of ALL_BASE_SKILLS) {
    for (const unlock of baseSkill.unlockSkills) {
      if (unlock.skillId === skillId) {
        return {
          baseSkillId: baseSkill.id,
          requiredLevel: unlock.requiredLevel,
        };
      }
    }
  }
  return null;
}
