// 敌人配置数据

import type { EnemyTemplate, EnemyGroup, Enemy } from '@/types';
import { generateUUID } from '@/types';

/** 敌人模板列表 */
export const ENEMY_TEMPLATES: Record<string, EnemyTemplate> = {
  // 普通怪 - 1-5级
  enemy_rabbit: {
    id: 'enemy_rabbit',
    name: '野兔',
    description: '一只普通的野兔',
    icon: '🐰',
    type: 'normal',
    baseStats: {
      physicalAttack: 8,
      physicalDefense: 5,
      magicAttack: 0,
      magicDefense: 3,
      speed: 15,
      maxHp: 30,
      maxMp: 0,
      critRate: 0.02,
      critDamage: 0.3,
      hitRate: 0.9,
      dodgeRate: 0.1,
    },
    elementResistances: { fire: 0, ice: 0, thunder: 0 },
    skills: [],
    aiBehavior: 'balanced',
    rarity: 'common',
    levelRange: { min: 1, max: 5 },
    expReward: 10,
    goldReward: 5,
    drops: [{ itemId: 'item_meat', rate: 0.3, minCount: 1, maxCount: 1 }],
    capturable: false,
  },

  enemy_wolf: {
    id: 'enemy_wolf',
    name: '野狼',
    description: '一只凶狠的野狼',
    icon: '🐺',
    type: 'normal',
    baseStats: {
      physicalAttack: 15,
      physicalDefense: 8,
      magicAttack: 0,
      magicDefense: 5,
      speed: 20,
      maxHp: 50,
      maxMp: 0,
      critRate: 0.05,
      critDamage: 0.4,
      hitRate: 0.9,
      dodgeRate: 0.05,
    },
    elementResistances: { fire: 0, ice: 0, thunder: 0 },
    skills: [],
    aiBehavior: 'aggressive',
    rarity: 'common',
    levelRange: { min: 2, max: 6 },
    expReward: 20,
    goldReward: 10,
    drops: [
      { itemId: 'item_fur', rate: 0.2, minCount: 1, maxCount: 2 },
      { itemId: 'item_meat', rate: 0.4, minCount: 1, maxCount: 1 },
    ],
    capturable: true,
    petTemplateId: 'pet_wolf',
  },

  enemy_snake: {
    id: 'enemy_snake',
    name: '竹叶青',
    description: '一条剧毒的竹叶青蛇',
    icon: '🐍',
    type: 'normal',
    baseStats: {
      physicalAttack: 18,
      physicalDefense: 5,
      magicAttack: 5,
      magicDefense: 8,
      speed: 25,
      maxHp: 40,
      maxMp: 20,
      critRate: 0.08,
      critDamage: 0.5,
      hitRate: 0.92,
      dodgeRate: 0.08,
    },
    elementResistances: { fire: -10, ice: 10, thunder: 0 },
    skills: [],
    aiBehavior: 'aggressive',
    rarity: 'common',
    levelRange: { min: 3, max: 8 },
    expReward: 25,
    goldReward: 15,
    drops: [{ itemId: 'item_snake_skin', rate: 0.15, minCount: 1, maxCount: 1 }],
    capturable: false,
  },

  enemy_boar: {
    id: 'enemy_boar',
    name: '野猪',
    description: '一头凶猛的野猪',
    icon: '🐗',
    type: 'normal',
    baseStats: {
      physicalAttack: 25,
      physicalDefense: 20,
      magicAttack: 0,
      magicDefense: 10,
      speed: 12,
      maxHp: 100,
      maxMp: 0,
      critRate: 0.03,
      critDamage: 0.35,
      hitRate: 0.85,
      dodgeRate: 0.02,
    },
    elementResistances: { fire: 0, ice: 0, thunder: 0 },
    skills: [],
    aiBehavior: 'defensive',
    rarity: 'common',
    levelRange: { min: 5, max: 10 },
    expReward: 35,
    goldReward: 20,
    drops: [
      { itemId: 'item_tusk', rate: 0.1, minCount: 1, maxCount: 2 },
      { itemId: 'item_meat', rate: 0.5, minCount: 1, maxCount: 2 },
    ],
    capturable: false,
  },

  enemy_monkey: {
    id: 'enemy_monkey',
    name: '猕猴',
    description: '一只顽皮的猕猴',
    icon: '🐒',
    type: 'normal',
    baseStats: {
      physicalAttack: 20,
      physicalDefense: 10,
      magicAttack: 5,
      magicDefense: 12,
      speed: 30,
      maxHp: 60,
      maxMp: 30,
      critRate: 0.1,
      critDamage: 0.45,
      hitRate: 0.92,
      dodgeRate: 0.1,
    },
    elementResistances: { fire: 0, ice: 0, thunder: 0 },
    skills: [],
    aiBehavior: 'balanced',
    rarity: 'common',
    levelRange: { min: 6, max: 12 },
    expReward: 40,
    goldReward: 25,
    drops: [{ itemId: 'item_banana', rate: 0.3, minCount: 1, maxCount: 2 }],
    capturable: false,
  },

  // 精英怪
  enemy_tiger: {
    id: 'enemy_tiger',
    name: '猛虎',
    description: '一只威猛的老虎',
    icon: '🐯',
    type: 'elite',
    baseStats: {
      physicalAttack: 45,
      physicalDefense: 25,
      magicAttack: 0,
      magicDefense: 15,
      speed: 28,
      maxHp: 200,
      maxMp: 0,
      critRate: 0.12,
      critDamage: 0.6,
      hitRate: 0.92,
      dodgeRate: 0.06,
    },
    elementResistances: { fire: 0, ice: 0, thunder: 0 },
    skills: [],
    aiBehavior: 'aggressive',
    rarity: 'rare',
    levelRange: { min: 8, max: 15 },
    expReward: 100,
    goldReward: 80,
    drops: [
      { itemId: 'item_tiger_fur', rate: 0.2, minCount: 1, maxCount: 1 },
      { itemId: 'item_tiger_bone', rate: 0.1, minCount: 1, maxCount: 1 },
    ],
    capturable: true,
    petTemplateId: 'pet_tiger',
  },

  // Boss
  enemy_monkey_king: {
    id: 'enemy_monkey_king',
    name: '美猴王',
    description: '花果山的美猴王，实力强大',
    icon: '👑',
    type: 'boss',
    baseStats: {
      physicalAttack: 80,
      physicalDefense: 40,
      magicAttack: 30,
      magicDefense: 35,
      speed: 50,
      maxHp: 500,
      maxMp: 200,
      critRate: 0.15,
      critDamage: 0.7,
      hitRate: 0.95,
      dodgeRate: 0.12,
    },
    elementResistances: { fire: 20, ice: 20, thunder: 20 },
    skills: [],
    aiBehavior: 'aggressive',
    rarity: 'legendary',
    levelRange: { min: 12, max: 12 },
    expReward: 500,
    goldReward: 300,
    drops: [
      { itemId: 'item_golden_fur', rate: 0.3, minCount: 1, maxCount: 1 },
      { itemId: 'equip_staff', rate: 0.1, minCount: 1, maxCount: 1 },
    ],
    capturable: false,
  },

  // ========== 东土大唐区域怪物 ==========

  // 普通怪 - 10-15级
  enemy_fox: {
    id: 'enemy_fox',
    name: '野狐',
    description: '一只狡猾的野狐',
    icon: '🦊',
    type: 'normal',
    baseStats: {
      physicalAttack: 25,
      physicalDefense: 12,
      magicAttack: 8,
      magicDefense: 15,
      speed: 35,
      maxHp: 80,
      maxMp: 30,
      critRate: 0.1,
      critDamage: 0.5,
      hitRate: 0.92,
      dodgeRate: 0.12,
    },
    elementResistances: { fire: 0, ice: 0, thunder: 0 },
    skills: [],
    aiBehavior: 'balanced',
    rarity: 'common',
    levelRange: { min: 10, max: 14 },
    expReward: 50,
    goldReward: 35,
    drops: [{ itemId: 'item_fox_fur', rate: 0.2, minCount: 1, maxCount: 1 }],
    capturable: false,
  },

  enemy_deer: {
    id: 'enemy_deer',
    name: '灵鹿',
    description: '一只敏捷的灵鹿',
    icon: '🦌',
    type: 'normal',
    baseStats: {
      physicalAttack: 20,
      physicalDefense: 15,
      magicAttack: 10,
      magicDefense: 18,
      speed: 28,
      maxHp: 100,
      maxMp: 40,
      critRate: 0.05,
      critDamage: 0.4,
      hitRate: 0.9,
      dodgeRate: 0.08,
    },
    elementResistances: { fire: 0, ice: 10, thunder: 0 },
    skills: [],
    aiBehavior: 'defensive',
    rarity: 'common',
    levelRange: { min: 10, max: 13 },
    expReward: 45,
    goldReward: 30,
    drops: [{ itemId: 'item_deer_antler', rate: 0.1, minCount: 1, maxCount: 1 }],
    capturable: false,
  },

  enemy_bandit: {
    id: 'enemy_bandit',
    name: '山贼',
    description: '拦路抢劫的山贼',
    icon: '🗡️',
    type: 'normal',
    baseStats: {
      physicalAttack: 35,
      physicalDefense: 20,
      magicAttack: 0,
      magicDefense: 10,
      speed: 22,
      maxHp: 120,
      maxMp: 0,
      critRate: 0.08,
      critDamage: 0.5,
      hitRate: 0.88,
      dodgeRate: 0.05,
    },
    elementResistances: { fire: 0, ice: 0, thunder: 0 },
    skills: [],
    aiBehavior: 'aggressive',
    rarity: 'common',
    levelRange: { min: 11, max: 16 },
    expReward: 55,
    goldReward: 50,
    drops: [
      { itemId: 'item_bandit_badge', rate: 0.15, minCount: 1, maxCount: 1 },
      { itemId: 'item_gold', rate: 0.3, minCount: 1, maxCount: 3 },
    ],
    capturable: false,
  },

  enemy_wild_dog: {
    id: 'enemy_wild_dog',
    name: '野狗',
    description: '成群结队的野狗',
    icon: '🐕',
    type: 'normal',
    baseStats: {
      physicalAttack: 28,
      physicalDefense: 12,
      magicAttack: 0,
      magicDefense: 8,
      speed: 30,
      maxHp: 70,
      maxMp: 0,
      critRate: 0.1,
      critDamage: 0.45,
      hitRate: 0.9,
      dodgeRate: 0.08,
    },
    elementResistances: { fire: 0, ice: 0, thunder: 0 },
    skills: [],
    aiBehavior: 'aggressive',
    rarity: 'common',
    levelRange: { min: 10, max: 14 },
    expReward: 40,
    goldReward: 25,
    drops: [{ itemId: 'item_dog_fang', rate: 0.15, minCount: 1, maxCount: 1 }],
    capturable: false,
  },

  // 普通怪 - 15-20级
  enemy_spider_small: {
    id: 'enemy_spider_small',
    name: '小蜘蛛',
    description: '一只小型毒蜘蛛',
    icon: '🕷️',
    type: 'normal',
    baseStats: {
      physicalAttack: 30,
      physicalDefense: 10,
      magicAttack: 15,
      magicDefense: 12,
      speed: 25,
      maxHp: 60,
      maxMp: 30,
      critRate: 0.08,
      critDamage: 0.4,
      hitRate: 0.9,
      dodgeRate: 0.1,
    },
    elementResistances: { fire: -10, ice: 10, thunder: 0 },
    skills: [],
    aiBehavior: 'aggressive',
    rarity: 'common',
    levelRange: { min: 14, max: 18 },
    expReward: 60,
    goldReward: 40,
    drops: [{ itemId: 'item_spider_silk', rate: 0.2, minCount: 1, maxCount: 2 }],
    capturable: false,
  },

  enemy_spider_poison: {
    id: 'enemy_spider_poison',
    name: '毒蛛',
    description: '一只剧毒蜘蛛',
    icon: '🕷️',
    type: 'normal',
    baseStats: {
      physicalAttack: 35,
      physicalDefense: 12,
      magicAttack: 25,
      magicDefense: 15,
      speed: 28,
      maxHp: 80,
      maxMp: 50,
      critRate: 0.1,
      critDamage: 0.5,
      hitRate: 0.92,
      dodgeRate: 0.08,
    },
    elementResistances: { fire: -10, ice: 15, thunder: 0 },
    skills: [],
    aiBehavior: 'aggressive',
    rarity: 'common',
    levelRange: { min: 16, max: 20 },
    expReward: 75,
    goldReward: 55,
    drops: [
      { itemId: 'item_spider_silk', rate: 0.25, minCount: 1, maxCount: 2 },
      { itemId: 'item_poison_gland', rate: 0.15, minCount: 1, maxCount: 1 },
    ],
    capturable: false,
  },

  enemy_ghost: {
    id: 'enemy_ghost',
    name: '游魂',
    description: '一缕游荡的鬼魂',
    icon: '👻',
    type: 'normal',
    baseStats: {
      physicalAttack: 15,
      physicalDefense: 5,
      magicAttack: 40,
      magicDefense: 30,
      speed: 35,
      maxHp: 70,
      maxMp: 80,
      critRate: 0.12,
      critDamage: 0.55,
      hitRate: 0.9,
      dodgeRate: 0.15,
    },
    elementResistances: { fire: -20, ice: 20, thunder: 0 },
    skills: [],
    aiBehavior: 'balanced',
    rarity: 'common',
    levelRange: { min: 13, max: 18 },
    expReward: 65,
    goldReward: 45,
    drops: [{ itemId: 'item_ghost_essence', rate: 0.15, minCount: 1, maxCount: 1 }],
    capturable: false,
  },

  enemy_water_demon: {
    id: 'enemy_water_demon',
    name: '水妖',
    description: '河流中的水妖',
    icon: '🌊',
    type: 'normal',
    baseStats: {
      physicalAttack: 32,
      physicalDefense: 18,
      magicAttack: 28,
      magicDefense: 25,
      speed: 22,
      maxHp: 110,
      maxMp: 60,
      critRate: 0.08,
      critDamage: 0.45,
      hitRate: 0.88,
      dodgeRate: 0.06,
    },
    elementResistances: { fire: -15, ice: 25, thunder: -10 },
    skills: [],
    aiBehavior: 'balanced',
    rarity: 'common',
    levelRange: { min: 12, max: 17 },
    expReward: 70,
    goldReward: 50,
    drops: [{ itemId: 'item_water_gem', rate: 0.1, minCount: 1, maxCount: 1 }],
    capturable: false,
  },

  enemy_fishman: {
    id: 'enemy_fishman',
    name: '鱼人',
    description: '半人半鱼的生物',
    icon: '🐟',
    type: 'normal',
    baseStats: {
      physicalAttack: 38,
      physicalDefense: 22,
      magicAttack: 10,
      magicDefense: 18,
      speed: 25,
      maxHp: 130,
      maxMp: 30,
      critRate: 0.06,
      critDamage: 0.4,
      hitRate: 0.85,
      dodgeRate: 0.05,
    },
    elementResistances: { fire: -10, ice: 20, thunder: -5 },
    skills: [],
    aiBehavior: 'aggressive',
    rarity: 'common',
    levelRange: { min: 11, max: 16 },
    expReward: 60,
    goldReward: 42,
    drops: [{ itemId: 'item_fish_scale', rate: 0.2, minCount: 1, maxCount: 2 }],
    capturable: false,
  },

  // 精英怪 - 15-25级
  enemy_fox_spirit: {
    id: 'enemy_fox_spirit',
    name: '狐妖',
    description: '修炼成精的狐狸',
    icon: '🦊',
    type: 'elite',
    baseStats: {
      physicalAttack: 55,
      physicalDefense: 25,
      magicAttack: 45,
      magicDefense: 35,
      speed: 40,
      maxHp: 250,
      maxMp: 150,
      critRate: 0.15,
      critDamage: 0.6,
      hitRate: 0.92,
      dodgeRate: 0.12,
    },
    elementResistances: { fire: 10, ice: 10, thunder: 0 },
    skills: [],
    aiBehavior: 'balanced',
    rarity: 'rare',
    levelRange: { min: 15, max: 22 },
    expReward: 150,
    goldReward: 120,
    drops: [
      { itemId: 'item_fox_fur', rate: 0.3, minCount: 1, maxCount: 2 },
      { itemId: 'item_fox_pearl', rate: 0.1, minCount: 1, maxCount: 1 },
    ],
    capturable: true,
    petTemplateId: 'pet_fox_spirit',
  },

  enemy_spider_elite: {
    id: 'enemy_spider_elite',
    name: '巨蛛',
    description: '体型巨大的蜘蛛',
    icon: '🕷️',
    type: 'elite',
    baseStats: {
      physicalAttack: 60,
      physicalDefense: 30,
      magicAttack: 35,
      magicDefense: 25,
      speed: 28,
      maxHp: 300,
      maxMp: 100,
      critRate: 0.12,
      critDamage: 0.55,
      hitRate: 0.9,
      dodgeRate: 0.08,
    },
    elementResistances: { fire: -15, ice: 15, thunder: 0 },
    skills: [],
    aiBehavior: 'aggressive',
    rarity: 'rare',
    levelRange: { min: 17, max: 23 },
    expReward: 180,
    goldReward: 140,
    drops: [
      { itemId: 'item_spider_silk', rate: 0.4, minCount: 2, maxCount: 4 },
      { itemId: 'item_poison_gland', rate: 0.25, minCount: 1, maxCount: 2 },
    ],
    capturable: false,
  },

  enemy_bandit_elite: {
    id: 'enemy_bandit_elite',
    name: '山贼头目',
    description: '山贼中的精英头目',
    icon: '⚔️',
    type: 'elite',
    baseStats: {
      physicalAttack: 65,
      physicalDefense: 40,
      magicAttack: 5,
      magicDefense: 20,
      speed: 30,
      maxHp: 350,
      maxMp: 50,
      critRate: 0.15,
      critDamage: 0.6,
      hitRate: 0.9,
      dodgeRate: 0.06,
    },
    elementResistances: { fire: 0, ice: 0, thunder: 0 },
    skills: [],
    aiBehavior: 'aggressive',
    rarity: 'rare',
    levelRange: { min: 18, max: 24 },
    expReward: 200,
    goldReward: 180,
    drops: [
      { itemId: 'item_bandit_badge', rate: 0.3, minCount: 1, maxCount: 2 },
      { itemId: 'item_gold', rate: 0.5, minCount: 3, maxCount: 5 },
    ],
    capturable: false,
  },

  enemy_tiger_datang: {
    id: 'enemy_tiger_datang',
    name: '大唐猛虎',
    description: '大唐境内凶猛的老虎',
    icon: '🐯',
    type: 'elite',
    baseStats: {
      physicalAttack: 70,
      physicalDefense: 35,
      magicAttack: 0,
      magicDefense: 22,
      speed: 35,
      maxHp: 320,
      maxMp: 0,
      critRate: 0.18,
      critDamage: 0.65,
      hitRate: 0.92,
      dodgeRate: 0.08,
    },
    elementResistances: { fire: 0, ice: 0, thunder: 0 },
    skills: [],
    aiBehavior: 'aggressive',
    rarity: 'rare',
    levelRange: { min: 16, max: 22 },
    expReward: 170,
    goldReward: 130,
    drops: [
      { itemId: 'item_tiger_fur', rate: 0.25, minCount: 1, maxCount: 1 },
      { itemId: 'item_tiger_bone', rate: 0.15, minCount: 1, maxCount: 1 },
    ],
    capturable: true,
    petTemplateId: 'pet_tiger',
  },

  enemy_fox_illusion: {
    id: 'enemy_fox_illusion',
    name: '狐妖幻影',
    description: '狐妖制造的幻影分身',
    icon: '✨',
    type: 'elite',
    baseStats: {
      physicalAttack: 40,
      physicalDefense: 15,
      magicAttack: 55,
      magicDefense: 40,
      speed: 45,
      maxHp: 180,
      maxMp: 200,
      critRate: 0.2,
      critDamage: 0.7,
      hitRate: 0.95,
      dodgeRate: 0.2,
    },
    elementResistances: { fire: 15, ice: 15, thunder: 15 },
    skills: [],
    aiBehavior: 'balanced',
    rarity: 'rare',
    levelRange: { min: 18, max: 26 },
    expReward: 160,
    goldReward: 100,
    drops: [{ itemId: 'item_illusion_crystal', rate: 0.15, minCount: 1, maxCount: 1 }],
    capturable: false,
  },

  enemy_skeleton_warrior: {
    id: 'enemy_skeleton_warrior',
    name: '骷髅战士',
    description: '被诅咒的骷髅战士',
    icon: '💀',
    type: 'elite',
    baseStats: {
      physicalAttack: 58,
      physicalDefense: 32,
      magicAttack: 20,
      magicDefense: 28,
      speed: 25,
      maxHp: 280,
      maxMp: 50,
      critRate: 0.12,
      critDamage: 0.55,
      hitRate: 0.88,
      dodgeRate: 0.05,
    },
    elementResistances: { fire: 0, ice: 10, thunder: -20 },
    skills: [],
    aiBehavior: 'aggressive',
    rarity: 'rare',
    levelRange: { min: 19, max: 25 },
    expReward: 190,
    goldReward: 150,
    drops: [
      { itemId: 'item_bone', rate: 0.3, minCount: 1, maxCount: 2 },
      { itemId: 'item_cursed_gem', rate: 0.08, minCount: 1, maxCount: 1 },
    ],
    capturable: false,
  },

  enemy_fairy_beast: {
    id: 'enemy_fairy_beast',
    name: '仙兽',
    description: '山中修炼的仙兽',
    icon: '🦄',
    type: 'elite',
    baseStats: {
      physicalAttack: 65,
      physicalDefense: 38,
      magicAttack: 50,
      magicDefense: 45,
      speed: 38,
      maxHp: 350,
      maxMp: 180,
      critRate: 0.15,
      critDamage: 0.6,
      hitRate: 0.92,
      dodgeRate: 0.1,
    },
    elementResistances: { fire: 20, ice: 20, thunder: 20 },
    skills: [],
    aiBehavior: 'balanced',
    rarity: 'rare',
    levelRange: { min: 20, max: 25 },
    expReward: 220,
    goldReward: 180,
    drops: [
      { itemId: 'item_fairy_dust', rate: 0.2, minCount: 1, maxCount: 2 },
      { itemId: 'item_immortal_herb', rate: 0.1, minCount: 1, maxCount: 1 },
    ],
    capturable: true,
    petTemplateId: 'pet_fairy_beast',
  },

  // Boss - 大唐区域
  boss_spider_queen: {
    id: 'boss_spider_queen',
    name: '蛛后',
    description: '蜘蛛巢穴的统治者，拥有剧毒和蛛网的力量',
    icon: '🕷️',
    type: 'boss',
    baseStats: {
      physicalAttack: 90,
      physicalDefense: 50,
      magicAttack: 80,
      magicDefense: 60,
      speed: 35,
      maxHp: 1200,
      maxMp: 400,
      critRate: 0.18,
      critDamage: 0.7,
      hitRate: 0.95,
      dodgeRate: 0.1,
    },
    elementResistances: { fire: -20, ice: 30, thunder: 0 },
    skills: [],
    aiBehavior: 'aggressive',
    rarity: 'legendary',
    levelRange: { min: 18, max: 18 },
    expReward: 800,
    goldReward: 500,
    drops: [
      { itemId: 'item_spider_queen_gem', rate: 0.3, minCount: 1, maxCount: 1 },
      { itemId: 'item_poison_essence', rate: 0.4, minCount: 1, maxCount: 2 },
      { itemId: 'equip_spider_ring', rate: 0.1, minCount: 1, maxCount: 1 },
    ],
    capturable: false,
  },

  boss_nine_tailed_fox: {
    id: 'boss_nine_tailed_fox',
    name: '九尾妖狐',
    description: '传说中的九尾妖狐，精通幻术和魅惑',
    icon: '🦊',
    type: 'boss',
    baseStats: {
      physicalAttack: 100,
      physicalDefense: 45,
      magicAttack: 120,
      magicDefense: 80,
      speed: 55,
      maxHp: 1500,
      maxMp: 600,
      critRate: 0.2,
      critDamage: 0.8,
      hitRate: 0.96,
      dodgeRate: 0.15,
    },
    elementResistances: { fire: 30, ice: 30, thunder: 30 },
    skills: [],
    aiBehavior: 'balanced',
    rarity: 'legendary',
    levelRange: { min: 25, max: 25 },
    expReward: 1500,
    goldReward: 1000,
    drops: [
      { itemId: 'item_nine_tails_essence', rate: 0.3, minCount: 1, maxCount: 1 },
      { itemId: 'item_illusion_crystal', rate: 0.5, minCount: 2, maxCount: 3 },
      { itemId: 'equip_fox_charm', rate: 0.15, minCount: 1, maxCount: 1 },
      { itemId: 'equip_nine_tails_fan', rate: 0.05, minCount: 1, maxCount: 1 },
    ],
    capturable: false,
  },
};

/** 敌人组配置 */
export const ENEMY_GROUPS: Record<string, EnemyGroup> = {
  // 新手村敌人组
  enemy_group_wolves: {
    id: 'enemy_group_wolves',
    name: '狼群',
    enemies: [
      { templateId: 'enemy_wolf', level: 3, position: 0 },
      { templateId: 'enemy_wolf', level: 3, position: 1 },
    ],
  },
  enemy_group_rabbits: {
    id: 'enemy_group_rabbits',
    name: '野兔群',
    enemies: [
      { templateId: 'enemy_rabbit', level: 2, position: 0 },
      { templateId: 'enemy_rabbit', level: 2, position: 1 },
      { templateId: 'enemy_rabbit', level: 2, position: 2 },
    ],
  },
  enemy_group_bamboo: {
    id: 'enemy_group_bamboo',
    name: '竹林生物',
    enemies: [
      { templateId: 'enemy_snake', level: 5, position: 0 },
      { templateId: 'enemy_snake', level: 5, position: 1 },
    ],
  },
  enemy_group_snakes: {
    id: 'enemy_group_snakes',
    name: '蛇群',
    enemies: [
      { templateId: 'enemy_snake', level: 6, position: 0 },
      { templateId: 'enemy_snake', level: 6, position: 1 },
      { templateId: 'enemy_snake', level: 5, position: 2 },
    ],
  },
  enemy_group_boars: {
    id: 'enemy_group_boars',
    name: '野猪群',
    enemies: [
      { templateId: 'enemy_boar', level: 8, position: 0 },
      { templateId: 'enemy_boar', level: 7, position: 1 },
    ],
  },
  enemy_group_monkeys: {
    id: 'enemy_group_monkeys',
    name: '猴群',
    enemies: [
      { templateId: 'enemy_monkey', level: 9, position: 0 },
      { templateId: 'enemy_monkey', level: 9, position: 1 },
      { templateId: 'enemy_monkey', level: 8, position: 2 },
    ],
  },
  enemy_group_tigers: {
    id: 'enemy_group_tigers',
    name: '猛虎',
    enemies: [
      { templateId: 'enemy_tiger', level: 12, position: 0 },
    ],
  },
  enemy_group_boss_monkey: {
    id: 'enemy_group_boss_monkey',
    name: '美猴王',
    enemies: [
      { templateId: 'enemy_monkey_king', level: 12, position: 0 },
    ],
    formationBonus: { stat: 'physicalAttack', value: 10, isPercent: true },
  },

  // 东土大唐敌人组 - 普通怪
  enemy_group_foxes: {
    id: 'enemy_group_foxes',
    name: '野狐群',
    enemies: [
      { templateId: 'enemy_fox', level: 11, position: 0 },
      { templateId: 'enemy_fox', level: 11, position: 1 },
    ],
  },
  enemy_group_deer: {
    id: 'enemy_group_deer',
    name: '灵鹿群',
    enemies: [
      { templateId: 'enemy_deer', level: 11, position: 0 },
      { templateId: 'enemy_deer', level: 10, position: 1 },
    ],
  },
  enemy_group_bandits: {
    id: 'enemy_group_bandits',
    name: '山贼帮',
    enemies: [
      { templateId: 'enemy_bandit', level: 12, position: 0 },
      { templateId: 'enemy_bandit', level: 11, position: 1 },
      { templateId: 'enemy_bandit', level: 11, position: 2 },
    ],
  },
  enemy_group_wild_dogs: {
    id: 'enemy_group_wild_dogs',
    name: '野狗群',
    enemies: [
      { templateId: 'enemy_wild_dog', level: 11, position: 0 },
      { templateId: 'enemy_wild_dog', level: 11, position: 1 },
      { templateId: 'enemy_wild_dog', level: 10, position: 2 },
    ],
  },
  enemy_group_spiders: {
    id: 'enemy_group_spiders',
    name: '蜘蛛群',
    enemies: [
      { templateId: 'enemy_spider_small', level: 15, position: 0 },
      { templateId: 'enemy_spider_small', level: 15, position: 1 },
      { templateId: 'enemy_spider_small', level: 14, position: 2 },
    ],
  },
  enemy_group_poison_spiders: {
    id: 'enemy_group_poison_spiders',
    name: '毒蛛群',
    enemies: [
      { templateId: 'enemy_spider_poison', level: 17, position: 0 },
      { templateId: 'enemy_spider_poison', level: 16, position: 1 },
    ],
  },
  enemy_group_ghosts: {
    id: 'enemy_group_ghosts',
    name: '游魂群',
    enemies: [
      { templateId: 'enemy_ghost', level: 14, position: 0 },
      { templateId: 'enemy_ghost', level: 14, position: 1 },
    ],
  },
  enemy_group_ghosts_datang: {
    id: 'enemy_group_ghosts_datang',
    name: '鬼城游魂',
    enemies: [
      { templateId: 'enemy_ghost', level: 20, position: 0 },
      { templateId: 'enemy_ghost', level: 19, position: 1 },
      { templateId: 'enemy_ghost', level: 19, position: 2 },
    ],
  },
  enemy_group_temple_guardians: {
    id: 'enemy_group_temple_guardians',
    name: '古庙守卫',
    enemies: [
      { templateId: 'enemy_ghost', level: 15, position: 0 },
      { templateId: 'enemy_ghost', level: 15, position: 1 },
    ],
  },
  enemy_group_water_demons: {
    id: 'enemy_group_water_demons',
    name: '水妖群',
    enemies: [
      { templateId: 'enemy_water_demon', level: 13, position: 0 },
      { templateId: 'enemy_water_demon', level: 12, position: 1 },
    ],
  },
  enemy_group_fishmen: {
    id: 'enemy_group_fishmen',
    name: '鱼人群',
    enemies: [
      { templateId: 'enemy_fishman', level: 13, position: 0 },
      { templateId: 'enemy_fishman', level: 12, position: 1 },
      { templateId: 'enemy_fishman', level: 12, position: 2 },
    ],
  },
  enemy_group_wild_wolves: {
    id: 'enemy_group_wild_wolves',
    name: '北方狼群',
    enemies: [
      { templateId: 'enemy_wolf', level: 14, position: 0 },
      { templateId: 'enemy_wolf', level: 13, position: 1 },
      { templateId: 'enemy_wolf', level: 13, position: 2 },
    ],
  },
  enemy_group_bears_datang: {
    id: 'enemy_group_bears_datang',
    name: '北方熊群',
    enemies: [
      { templateId: 'enemy_boar', level: 15, position: 0 },
      { templateId: 'enemy_boar', level: 14, position: 1 },
    ],
  },
  enemy_group_skeleton_warriors: {
    id: 'enemy_group_skeleton_warriors',
    name: '骷髅战士',
    enemies: [
      { templateId: 'enemy_skeleton_warrior', level: 22, position: 0 },
      { templateId: 'enemy_skeleton_warrior', level: 21, position: 1 },
    ],
  },
  enemy_group_swamp_creatures: {
    id: 'enemy_group_swamp_creatures',
    name: '沼泽生物',
    enemies: [
      { templateId: 'enemy_water_demon', level: 18, position: 0 },
      { templateId: 'enemy_ghost', level: 17, position: 1 },
    ],
  },
  enemy_group_poison_toads: {
    id: 'enemy_group_poison_toads',
    name: '毒蟾蜍',
    enemies: [
      { templateId: 'enemy_spider_poison', level: 18, position: 0 },
      { templateId: 'enemy_spider_small', level: 17, position: 1 },
      { templateId: 'enemy_spider_small', level: 17, position: 2 },
    ],
  },
  enemy_group_water_dragons: {
    id: 'enemy_group_water_dragons',
    name: '幼龙群',
    enemies: [
      { templateId: 'enemy_water_demon', level: 20, position: 0 },
      { templateId: 'enemy_water_demon', level: 19, position: 1 },
    ],
  },
  enemy_group_dragon_fish: {
    id: 'enemy_group_dragon_fish',
    name: '龙鱼群',
    enemies: [
      { templateId: 'enemy_fishman', level: 19, position: 0 },
      { templateId: 'enemy_fishman', level: 18, position: 1 },
      { templateId: 'enemy_fishman', level: 18, position: 2 },
    ],
  },
  enemy_group_tigers_datang: {
    id: 'enemy_group_tigers_datang',
    name: '大唐猛虎',
    enemies: [
      { templateId: 'enemy_tiger_datang', level: 18, position: 0 },
      { templateId: 'enemy_tiger_datang', level: 17, position: 1 },
    ],
  },
  enemy_group_tiger_king: {
    id: 'enemy_group_tiger_king',
    name: '虎王',
    enemies: [
      { templateId: 'enemy_tiger_datang', level: 20, position: 0 },
    ],
    formationBonus: { stat: 'physicalAttack', value: 15, isPercent: true },
  },
  enemy_group_fox_spirits: {
    id: 'enemy_group_fox_spirits',
    name: '狐妖群',
    enemies: [
      { templateId: 'enemy_fox_spirit', level: 18, position: 0 },
      { templateId: 'enemy_fox_spirit', level: 17, position: 1 },
    ],
  },
  enemy_group_fairy_beasts: {
    id: 'enemy_group_fairy_beasts',
    name: '仙兽群',
    enemies: [
      { templateId: 'enemy_fairy_beast', level: 22, position: 0 },
      { templateId: 'enemy_fairy_beast', level: 21, position: 1 },
    ],
  },
  enemy_group_cloud_spirits: {
    id: 'enemy_group_cloud_spirits',
    name: '云灵',
    enemies: [
      { templateId: 'enemy_ghost', level: 22, position: 0 },
      { templateId: 'enemy_ghost', level: 21, position: 1 },
      { templateId: 'enemy_ghost', level: 21, position: 2 },
    ],
  },
  enemy_group_bandit_elites: {
    id: 'enemy_group_bandit_elites',
    name: '山贼精英',
    enemies: [
      { templateId: 'enemy_bandit_elite', level: 20, position: 0 },
      { templateId: 'enemy_bandit', level: 19, position: 1 },
      { templateId: 'enemy_bandit', level: 19, position: 2 },
    ],
  },
  enemy_group_spider_queen: {
    id: 'enemy_group_spider_queen',
    name: '蛛后守卫',
    enemies: [
      { templateId: 'enemy_spider_elite', level: 17, position: 0 },
      { templateId: 'enemy_spider_poison', level: 16, position: 1 },
      { templateId: 'enemy_spider_poison', level: 16, position: 2 },
    ],
  },
};

/** 创建敌人实例 */
export function createEnemy(templateId: string, level: number): Enemy | null {
  const template = ENEMY_TEMPLATES[templateId];
  if (!template) return null;

  const levelFactor = 1 + (level - template.levelRange.min) * 0.1;

  return {
    id: generateUUID(),
    templateId,
    name: template.name,
    type: template.type,
    level,
    stats: {
      physicalAttack: Math.floor(template.baseStats.physicalAttack * levelFactor),
      physicalDefense: Math.floor(template.baseStats.physicalDefense * levelFactor),
      magicAttack: Math.floor(template.baseStats.magicAttack * levelFactor),
      magicDefense: Math.floor(template.baseStats.magicDefense * levelFactor),
      speed: Math.floor(template.baseStats.speed * levelFactor),
      maxHp: Math.floor(template.baseStats.maxHp * levelFactor),
      maxMp: Math.floor(template.baseStats.maxMp * levelFactor),
      critRate: template.baseStats.critRate,
      critDamage: template.baseStats.critDamage,
      hitRate: template.baseStats.hitRate,
      dodgeRate: template.baseStats.dodgeRate,
    },
    elementResistances: { ...template.elementResistances },
    element: template.element,
    skills: [...template.skills],
    hp: Math.floor(template.baseStats.maxHp * levelFactor),
    maxHp: Math.floor(template.baseStats.maxHp * levelFactor),
    mp: Math.floor(template.baseStats.maxMp * levelFactor),
    maxMp: Math.floor(template.baseStats.maxMp * levelFactor),
    statusEffects: [],
    expReward: Math.floor(template.expReward * levelFactor),
    goldReward: Math.floor(template.goldReward * levelFactor),
    drops: template.drops.map(d => ({
      itemId: d.itemId,
      count: Math.floor(Math.random() * (d.maxCount - d.minCount + 1)) + d.minCount,
    })),
    capturable: template.capturable,
    petTemplateId: template.petTemplateId,
  };
}

/** 获取敌人模板 */
export function getEnemyTemplate(id: string): EnemyTemplate | undefined {
  return ENEMY_TEMPLATES[id];
}

/** 获取敌人组 */
export function getEnemyGroup(id: string): EnemyGroup | undefined {
  return ENEMY_GROUPS[id];
}
