// 装备模板数据 - 梦幻西游经典装备

import type { EquipmentTemplate, EquipmentSlot, WeaponType, FactionId } from '@/types';

// ==================== 武器模板 ====================

/** 剑类武器 - 大唐官府、方寸山、五庄观、阴曹地府 */
const SWORD_WEAPONS: EquipmentTemplate[] = [
  // 0-10级
  {
    id: 'equip_sword_1',
    name: '青铜剑',
    description: '青铜铸造的剑，初学者的武器。',
    icon: '🗡️',
    slot: 'weapon',
    weaponType: 'sword',
    restrictedFactions: ['faction_datang', 'faction_fangcun', 'faction_wuzhuang', 'faction_difu'] as FactionId[],
    baseQuality: 'common',
    baseStats: { physicalAttack: 12 },
    gemSlots: 1,
    maxEnhance: 10,
    levelRequirement: 1,
    allowedGems: ['ruby', 'diamond'],
  },
  {
    id: 'equip_sword_2',
    name: '铁剑',
    description: '铁匠打造的剑，锋利度一般。',
    icon: '⚔️',
    slot: 'weapon',
    weaponType: 'sword',
    restrictedFactions: ['faction_datang', 'faction_fangcun', 'faction_wuzhuang', 'faction_difu'] as FactionId[],
    baseQuality: 'common',
    baseStats: { physicalAttack: 25, critRate: 0.02 },
    gemSlots: 1,
    maxEnhance: 10,
    levelRequirement: 10,
    allowedGems: ['ruby', 'topaz', 'diamond'],
  },
  // 11-30级
  {
    id: 'equip_sword_3',
    name: '精钢剑',
    description: '由精钢锻造的利剑，锋利无比。',
    icon: '🔪',
    slot: 'weapon',
    weaponType: 'sword',
    restrictedFactions: ['faction_datang', 'faction_fangcun', 'faction_wuzhuang', 'faction_difu'] as FactionId[],
    baseQuality: 'rare',
    baseStats: { physicalAttack: 45, critRate: 0.03 },
    gemSlots: 2,
    maxEnhance: 12,
    levelRequirement: 20,
    allowedGems: ['ruby', 'topaz', 'diamond'],
  },
  {
    id: 'equip_sword_4',
    name: '玄铁剑',
    description: '由玄铁打造，重剑无锋大巧不工。',
    icon: '🪓',
    slot: 'weapon',
    weaponType: 'sword',
    restrictedFactions: ['faction_datang', 'faction_fangcun', 'faction_wuzhuang', 'faction_difu'] as FactionId[],
    baseQuality: 'rare',
    baseStats: { physicalAttack: 68, critRate: 0.04, critDamage: 0.1 },
    gemSlots: 2,
    maxEnhance: 12,
    levelRequirement: 30,
    allowedGems: ['ruby', 'topaz', 'diamond'],
  },
  // 31-50级
  {
    id: 'equip_sword_5',
    name: '七星剑',
    description: '剑身刻有北斗七星，蕴含神秘力量。',
    icon: '✨',
    slot: 'weapon',
    weaponType: 'sword',
    restrictedFactions: ['faction_datang', 'faction_fangcun', 'faction_wuzhuang', 'faction_difu'] as FactionId[],
    baseQuality: 'epic',
    baseStats: { physicalAttack: 95, critRate: 0.05, critDamage: 0.15 },
    gemSlots: 2,
    maxEnhance: 14,
    levelRequirement: 40,
    allowedGems: ['ruby', 'topaz', 'amethyst', 'diamond'],
  },
  {
    id: 'equip_sword_6',
    name: '龙渊剑',
    description: '传说由龙族铸造，剑气纵横。',
    icon: '🐉',
    slot: 'weapon',
    weaponType: 'sword',
    restrictedFactions: ['faction_datang', 'faction_fangcun', 'faction_wuzhuang', 'faction_difu'] as FactionId[],
    baseQuality: 'epic',
    baseStats: { physicalAttack: 125, critRate: 0.06, critDamage: 0.2 },
    gemSlots: 3,
    maxEnhance: 14,
    levelRequirement: 50,
    allowedGems: ['ruby', 'topaz', 'amethyst', 'diamond'],
  },
  // 51-70级
  {
    id: 'equip_sword_7',
    name: '倚天剑',
    description: '武林至尊，宝刀屠龙，号令天下，莫敢不从。',
    icon: '👑',
    slot: 'weapon',
    weaponType: 'sword',
    restrictedFactions: ['faction_datang', 'faction_fangcun', 'faction_wuzhuang', 'faction_difu'] as FactionId[],
    baseQuality: 'legendary',
    baseStats: { physicalAttack: 165, critRate: 0.08, critDamage: 0.25 },
    gemSlots: 3,
    maxEnhance: 16,
    levelRequirement: 60,
    allowedGems: ['ruby', 'topaz', 'amethyst', 'diamond'],
  },
  {
    id: 'equip_sword_8',
    name: '干将莫邪',
    description: '传说中的神剑，拥有毁天灭地的力量。',
    icon: '⚡',
    slot: 'weapon',
    weaponType: 'sword',
    restrictedFactions: ['faction_datang', 'faction_fangcun', 'faction_wuzhuang', 'faction_difu'] as FactionId[],
    baseQuality: 'legendary',
    baseStats: { physicalAttack: 210, critRate: 0.1, critDamage: 0.35 },
    gemSlots: 3,
    maxEnhance: 18,
    levelRequirement: 70,
    allowedGems: ['ruby', 'topaz', 'amethyst', 'diamond'],
  },
  // 71+级
  {
    id: 'equip_sword_9',
    name: '轩辕剑',
    description: '上古神剑，蕴含圣皇之力。',
    icon: '🌟',
    slot: 'weapon',
    weaponType: 'sword',
    restrictedFactions: ['faction_datang', 'faction_fangcun', 'faction_wuzhuang', 'faction_difu'] as FactionId[],
    baseQuality: 'mythic',
    baseStats: { physicalAttack: 280, critRate: 0.12, critDamage: 0.45, hitRate: 0.05 },
    gemSlots: 4,
    maxEnhance: 20,
    levelRequirement: 80,
    allowedGems: ['ruby', 'topaz', 'amethyst', 'diamond'],
  },
];

/** 扇类武器 - 化生寺、方寸山、女儿村、龙宫、魔王寨、五庄观、盘丝洞 */
const FAN_WEAPONS: EquipmentTemplate[] = [
  {
    id: 'equip_fan_1',
    name: '纸扇',
    description: '普通的纸扇，轻巧便携。',
    icon: '🪭',
    slot: 'weapon',
    weaponType: 'fan',
    restrictedFactions: ['faction_huasheng', 'faction_fangcun', 'faction_nver', 'faction_longgong', 'faction_mowang', 'faction_wuzhuang', 'faction_pansi'] as FactionId[],
    baseQuality: 'common',
    baseStats: { physicalAttack: 10, speed: 3 },
    gemSlots: 1,
    maxEnhance: 10,
    levelRequirement: 1,
    allowedGems: ['topaz', 'diamond'],
  },
  {
    id: 'equip_fan_2',
    name: '铁骨扇',
    description: '扇骨为铁制，可攻可守。',
    icon: '🪭',
    slot: 'weapon',
    weaponType: 'fan',
    restrictedFactions: ['faction_huasheng', 'faction_fangcun', 'faction_nver', 'faction_longgong', 'faction_mowang', 'faction_wuzhuang', 'faction_pansi'] as FactionId[],
    baseQuality: 'common',
    baseStats: { physicalAttack: 22, speed: 5 },
    gemSlots: 1,
    maxEnhance: 10,
    levelRequirement: 10,
    allowedGems: ['topaz', 'ruby', 'diamond'],
  },
  {
    id: 'equip_fan_3',
    name: '玉面扇',
    description: '玉制扇面，散发着灵气。',
    icon: '🪭',
    slot: 'weapon',
    weaponType: 'fan',
    restrictedFactions: ['faction_huasheng', 'faction_fangcun', 'faction_nver', 'faction_longgong', 'faction_mowang', 'faction_wuzhuang', 'faction_pansi'] as FactionId[],
    baseQuality: 'rare',
    baseStats: { physicalAttack: 42, speed: 8, dodgeRate: 0.03 },
    gemSlots: 2,
    maxEnhance: 12,
    levelRequirement: 20,
    allowedGems: ['topaz', 'ruby', 'diamond'],
  },
  {
    id: 'equip_fan_4',
    name: '逍遥扇',
    description: '逍遥自在，扇动间风生水起。',
    icon: '💨',
    slot: 'weapon',
    weaponType: 'fan',
    restrictedFactions: ['faction_huasheng', 'faction_fangcun', 'faction_nver', 'faction_longgong', 'faction_mowang', 'faction_wuzhuang', 'faction_pansi'] as FactionId[],
    baseQuality: 'rare',
    baseStats: { physicalAttack: 65, speed: 12, dodgeRate: 0.05 },
    gemSlots: 2,
    maxEnhance: 12,
    levelRequirement: 30,
    allowedGems: ['topaz', 'ruby', 'diamond'],
  },
  {
    id: 'equip_fan_5',
    name: '阴阳扇',
    description: '一面阴一面阳，蕴含天地至理。',
    icon: '☯️',
    slot: 'weapon',
    weaponType: 'fan',
    restrictedFactions: ['faction_huasheng', 'faction_fangcun', 'faction_nver', 'faction_longgong', 'faction_mowang', 'faction_wuzhuang', 'faction_pansi'] as FactionId[],
    baseQuality: 'epic',
    baseStats: { physicalAttack: 90, speed: 16, dodgeRate: 0.06, critRate: 0.04 },
    gemSlots: 2,
    maxEnhance: 14,
    levelRequirement: 40,
    allowedGems: ['topaz', 'ruby', 'amethyst', 'diamond'],
  },
  {
    id: 'equip_fan_6',
    name: '乾坤扇',
    description: '扇中自有乾坤，挥动间移山填海。',
    icon: '🌌',
    slot: 'weapon',
    weaponType: 'fan',
    restrictedFactions: ['faction_huasheng', 'faction_fangcun', 'faction_nver', 'faction_longgong', 'faction_mowang', 'faction_wuzhuang', 'faction_pansi'] as FactionId[],
    baseQuality: 'epic',
    baseStats: { physicalAttack: 120, speed: 20, dodgeRate: 0.08, critRate: 0.05 },
    gemSlots: 3,
    maxEnhance: 14,
    levelRequirement: 50,
    allowedGems: ['topaz', 'ruby', 'amethyst', 'diamond'],
  },
  {
    id: 'equip_fan_7',
    name: '神火扇',
    description: '扇动间可引动三昧真火。',
    icon: '🔥',
    slot: 'weapon',
    weaponType: 'fan',
    restrictedFactions: ['faction_huasheng', 'faction_fangcun', 'faction_nver', 'faction_longgong', 'faction_mowang', 'faction_wuzhuang', 'faction_pansi'] as FactionId[],
    baseQuality: 'legendary',
    baseStats: { physicalAttack: 160, speed: 25, dodgeRate: 0.1, critRate: 0.07 },
    gemSlots: 3,
    maxEnhance: 16,
    levelRequirement: 60,
    allowedGems: ['topaz', 'ruby', 'amethyst', 'diamond'],
  },
];

/** 法杖类武器 - 化生寺、普陀山、龙宫、魔王寨 */
const STAFF_WEAPONS: EquipmentTemplate[] = [
  {
    id: 'equip_staff_1',
    name: '木杖',
    description: '普通的木杖，蕴含微弱的魔力。',
    icon: '🪄',
    slot: 'weapon',
    weaponType: 'staff',
    restrictedFactions: ['faction_huasheng', 'faction_putuo', 'faction_longgong', 'faction_mowang'] as FactionId[],
    baseQuality: 'common',
    baseStats: { magicAttack: 14 },
    gemSlots: 1,
    maxEnhance: 10,
    levelRequirement: 1,
    allowedGems: ['sapphire', 'amethyst', 'diamond'],
  },
  {
    id: 'equip_staff_2',
    name: '桃木杖',
    description: '由桃木制成的法杖，蕴含灵气。',
    icon: '🔮',
    slot: 'weapon',
    weaponType: 'staff',
    restrictedFactions: ['faction_huasheng', 'faction_putuo', 'faction_longgong', 'faction_mowang'] as FactionId[],
    baseQuality: 'common',
    baseStats: { magicAttack: 28, maxMp: 30 },
    gemSlots: 1,
    maxEnhance: 10,
    levelRequirement: 10,
    allowedGems: ['sapphire', 'amethyst', 'diamond'],
  },
  {
    id: 'equip_staff_3',
    name: '青玉杖',
    description: '由青玉打造的法杖，魔力流转。',
    icon: '💎',
    slot: 'weapon',
    weaponType: 'staff',
    restrictedFactions: ['faction_huasheng', 'faction_putuo', 'faction_longgong', 'faction_mowang'] as FactionId[],
    baseQuality: 'rare',
    baseStats: { magicAttack: 50, maxMp: 50 },
    gemSlots: 2,
    maxEnhance: 12,
    levelRequirement: 20,
    allowedGems: ['sapphire', 'amethyst', 'diamond'],
  },
  {
    id: 'equip_staff_4',
    name: '紫金杖',
    description: '紫金铸就，散发着神秘的紫光。',
    icon: '💜',
    slot: 'weapon',
    weaponType: 'staff',
    restrictedFactions: ['faction_huasheng', 'faction_putuo', 'faction_longgong', 'faction_mowang'] as FactionId[],
    baseQuality: 'rare',
    baseStats: { magicAttack: 75, maxMp: 80, magicDefense: 15 },
    gemSlots: 2,
    maxEnhance: 12,
    levelRequirement: 30,
    allowedGems: ['sapphire', 'amethyst', 'diamond'],
  },
  {
    id: 'equip_staff_5',
    name: '天师杖',
    description: '道家天师所用之法杖，法力无边。',
    icon: '☯️',
    slot: 'weapon',
    weaponType: 'staff',
    restrictedFactions: ['faction_huasheng', 'faction_putuo', 'faction_longgong', 'faction_mowang'] as FactionId[],
    baseQuality: 'epic',
    baseStats: { magicAttack: 105, maxMp: 120, magicDefense: 25 },
    gemSlots: 2,
    maxEnhance: 14,
    levelRequirement: 40,
    allowedGems: ['sapphire', 'amethyst', 'diamond'],
  },
  {
    id: 'equip_staff_6',
    name: '九环锡杖',
    description: '佛门至宝，九环相扣，法力通天。',
    icon: '📿',
    slot: 'weapon',
    weaponType: 'staff',
    restrictedFactions: ['faction_huasheng', 'faction_putuo', 'faction_longgong', 'faction_mowang'] as FactionId[],
    baseQuality: 'epic',
    baseStats: { magicAttack: 140, maxMp: 160, magicDefense: 35 },
    gemSlots: 3,
    maxEnhance: 14,
    levelRequirement: 50,
    allowedGems: ['sapphire', 'amethyst', 'emerald', 'diamond'],
  },
  {
    id: 'equip_staff_7',
    name: '昆仑镜杖',
    description: '镶嵌昆仑神镜的法杖，可洞察天地。',
    icon: '🪞',
    slot: 'weapon',
    weaponType: 'staff',
    restrictedFactions: ['faction_huasheng', 'faction_putuo', 'faction_longgong', 'faction_mowang'] as FactionId[],
    baseQuality: 'legendary',
    baseStats: { magicAttack: 185, maxMp: 220, magicDefense: 50, maxHp: 100 },
    gemSlots: 3,
    maxEnhance: 16,
    levelRequirement: 60,
    allowedGems: ['sapphire', 'amethyst', 'emerald', 'diamond'],
  },
  {
    id: 'equip_staff_8',
    name: '女娲石杖',
    description: '以女娲补天石为杖首，拥有创世之力。',
    icon: '🌈',
    slot: 'weapon',
    weaponType: 'staff',
    restrictedFactions: ['faction_huasheng', 'faction_putuo', 'faction_longgong', 'faction_mowang'] as FactionId[],
    baseQuality: 'mythic',
    baseStats: { magicAttack: 260, maxMp: 320, magicDefense: 70, maxHp: 150 },
    gemSlots: 4,
    maxEnhance: 20,
    levelRequirement: 80,
    allowedGems: ['sapphire', 'amethyst', 'emerald', 'diamond'],
  },
];

/** 枪类武器 - 天宫 */
const SPEAR_WEAPONS: EquipmentTemplate[] = [
  {
    id: 'equip_spear_1',
    name: '铁枪',
    description: '普通的铁枪，攻击距离远。',
    icon: '🔱',
    slot: 'weapon',
    weaponType: 'spear',
    restrictedFactions: ['faction_tiangong'] as FactionId[],
    baseQuality: 'common',
    baseStats: { physicalAttack: 13, hitRate: 0.02 },
    gemSlots: 1,
    maxEnhance: 10,
    levelRequirement: 1,
    allowedGems: ['ruby', 'topaz', 'diamond'],
  },
  {
    id: 'equip_spear_2',
    name: '精铁枪',
    description: '精铁打造的枪，锋利坚韧。',
    icon: '🔱',
    slot: 'weapon',
    weaponType: 'spear',
    restrictedFactions: ['faction_tiangong'] as FactionId[],
    baseQuality: 'common',
    baseStats: { physicalAttack: 28, hitRate: 0.03, critRate: 0.02 },
    gemSlots: 1,
    maxEnhance: 10,
    levelRequirement: 10,
    allowedGems: ['ruby', 'topaz', 'diamond'],
  },
  {
    id: 'equip_spear_3',
    name: '亮银枪',
    description: '银光闪闪的长枪，锋利无比。',
    icon: '🔱',
    slot: 'weapon',
    weaponType: 'spear',
    restrictedFactions: ['faction_tiangong'] as FactionId[],
    baseQuality: 'rare',
    baseStats: { physicalAttack: 48, hitRate: 0.04, critRate: 0.03 },
    gemSlots: 2,
    maxEnhance: 12,
    levelRequirement: 20,
    allowedGems: ['ruby', 'topaz', 'diamond'],
  },
  {
    id: 'equip_spear_4',
    name: '丈八蛇矛',
    description: '如蛇般蜿蜒的长矛，穿透力极强。',
    icon: '🐍',
    slot: 'weapon',
    weaponType: 'spear',
    restrictedFactions: ['faction_tiangong'] as FactionId[],
    baseQuality: 'rare',
    baseStats: { physicalAttack: 72, hitRate: 0.05, critDamage: 0.1 },
    gemSlots: 2,
    maxEnhance: 12,
    levelRequirement: 30,
    allowedGems: ['ruby', 'topaz', 'diamond'],
  },
  {
    id: 'equip_spear_5',
    name: '方天画戟',
    description: '传说中吕布所用神兵。',
    icon: '⚔️',
    slot: 'weapon',
    weaponType: 'spear',
    restrictedFactions: ['faction_tiangong'] as FactionId[],
    baseQuality: 'epic',
    baseStats: { physicalAttack: 100, hitRate: 0.06, critRate: 0.05, critDamage: 0.15 },
    gemSlots: 2,
    maxEnhance: 14,
    levelRequirement: 40,
    allowedGems: ['ruby', 'topaz', 'amethyst', 'diamond'],
  },
  {
    id: 'equip_spear_6',
    name: '龙胆亮银枪',
    description: '赵云所用神枪，龙胆之名响彻天下。',
    icon: '🐉',
    slot: 'weapon',
    weaponType: 'spear',
    restrictedFactions: ['faction_tiangong'] as FactionId[],
    baseQuality: 'epic',
    baseStats: { physicalAttack: 135, hitRate: 0.07, critRate: 0.06, critDamage: 0.2 },
    gemSlots: 3,
    maxEnhance: 14,
    levelRequirement: 50,
    allowedGems: ['ruby', 'topaz', 'amethyst', 'diamond'],
  },
  {
    id: 'equip_spear_7',
    name: '霸王枪',
    description: '西楚霸王项羽所用神枪。',
    icon: '👑',
    slot: 'weapon',
    weaponType: 'spear',
    restrictedFactions: ['faction_tiangong'] as FactionId[],
    baseQuality: 'legendary',
    baseStats: { physicalAttack: 180, hitRate: 0.08, critRate: 0.08, critDamage: 0.3 },
    gemSlots: 3,
    maxEnhance: 16,
    levelRequirement: 60,
    allowedGems: ['ruby', 'topaz', 'amethyst', 'diamond'],
  },
];

/** 刀类武器 - 大唐官府 */
const BLADE_WEAPONS: EquipmentTemplate[] = [
  {
    id: 'equip_blade_1',
    name: '铁刀',
    description: '普通的铁刀，厚重锋利。',
    icon: '🔪',
    slot: 'weapon',
    weaponType: 'blade',
    restrictedFactions: ['faction_datang'] as FactionId[],
    baseQuality: 'common',
    baseStats: { physicalAttack: 14, critDamage: 0.08 },
    gemSlots: 1,
    maxEnhance: 10,
    levelRequirement: 1,
    allowedGems: ['ruby', 'diamond'],
  },
  {
    id: 'equip_blade_2',
    name: '钢刀',
    description: '精钢打造的刀，劈砍有力。',
    icon: '🔪',
    slot: 'weapon',
    weaponType: 'blade',
    restrictedFactions: ['faction_datang'] as FactionId[],
    baseQuality: 'common',
    baseStats: { physicalAttack: 30, critDamage: 0.1 },
    gemSlots: 1,
    maxEnhance: 10,
    levelRequirement: 10,
    allowedGems: ['ruby', 'diamond'],
  },
  {
    id: 'equip_blade_3',
    name: '雁翎刀',
    description: '刀身如雁翎，轻便锋利。',
    icon: '🗡️',
    slot: 'weapon',
    weaponType: 'blade',
    restrictedFactions: ['faction_datang'] as FactionId[],
    baseQuality: 'rare',
    baseStats: { physicalAttack: 50, critDamage: 0.12, critRate: 0.03 },
    gemSlots: 2,
    maxEnhance: 12,
    levelRequirement: 20,
    allowedGems: ['ruby', 'topaz', 'diamond'],
  },
  {
    id: 'equip_blade_4',
    name: '鬼头刀',
    description: '刀头如鬼面，令人胆寒。',
    icon: '👻',
    slot: 'weapon',
    weaponType: 'blade',
    restrictedFactions: ['faction_datang'] as FactionId[],
    baseQuality: 'rare',
    baseStats: { physicalAttack: 76, critDamage: 0.18, critRate: 0.04 },
    gemSlots: 2,
    maxEnhance: 12,
    levelRequirement: 30,
    allowedGems: ['ruby', 'topaz', 'diamond'],
  },
  {
    id: 'equip_blade_5',
    name: '青龙偃月刀',
    description: '关公所用神刀，青龙之名威震天下。',
    icon: '🐉',
    slot: 'weapon',
    weaponType: 'blade',
    restrictedFactions: ['faction_datang'] as FactionId[],
    baseQuality: 'epic',
    baseStats: { physicalAttack: 108, critDamage: 0.25, critRate: 0.05 },
    gemSlots: 2,
    maxEnhance: 14,
    levelRequirement: 40,
    allowedGems: ['ruby', 'topaz', 'amethyst', 'diamond'],
  },
  {
    id: 'equip_blade_6',
    name: '屠龙刀',
    description: '武林至尊，号令天下，莫敢不从。',
    icon: '⚔️',
    slot: 'weapon',
    weaponType: 'blade',
    restrictedFactions: ['faction_datang'] as FactionId[],
    baseQuality: 'legendary',
    baseStats: { physicalAttack: 175, critDamage: 0.4, critRate: 0.08 },
    gemSlots: 3,
    maxEnhance: 16,
    levelRequirement: 60,
    allowedGems: ['ruby', 'topaz', 'amethyst', 'diamond'],
  },
];

/** 锤类武器 - 天宫、狮驼岭 */
const HAMMER_WEAPONS: EquipmentTemplate[] = [
  {
    id: 'equip_hammer_1',
    name: '铁锤',
    description: '沉重的铁锤，力大势沉。',
    icon: '🔨',
    slot: 'weapon',
    weaponType: 'hammer',
    restrictedFactions: ['faction_tiangong', 'faction_shituo'] as FactionId[],
    baseQuality: 'common',
    baseStats: { physicalAttack: 14, critDamage: 0.1 },
    gemSlots: 1,
    maxEnhance: 10,
    levelRequirement: 1,
    allowedGems: ['ruby', 'diamond'],
  },
  {
    id: 'equip_hammer_2',
    name: '铜锤',
    description: '铜制大锤，威力更胜一筹。',
    icon: '⚒️',
    slot: 'weapon',
    weaponType: 'hammer',
    restrictedFactions: ['faction_tiangong', 'faction_shituo'] as FactionId[],
    baseQuality: 'common',
    baseStats: { physicalAttack: 28, critDamage: 0.12 },
    gemSlots: 1,
    maxEnhance: 10,
    levelRequirement: 10,
    allowedGems: ['ruby', 'diamond'],
  },
  {
    id: 'equip_hammer_3',
    name: '金瓜锤',
    description: '锤头如金瓜，重若千钧。',
    icon: '🔨',
    slot: 'weapon',
    weaponType: 'hammer',
    restrictedFactions: ['faction_tiangong', 'faction_shituo'] as FactionId[],
    baseQuality: 'rare',
    baseStats: { physicalAttack: 52, critDamage: 0.15, critRate: 0.03 },
    gemSlots: 2,
    maxEnhance: 12,
    levelRequirement: 20,
    allowedGems: ['ruby', 'topaz', 'diamond'],
  },
  {
    id: 'equip_hammer_4',
    name: '破甲锤',
    description: '专破护甲的重锤。',
    icon: '⚒️',
    slot: 'weapon',
    weaponType: 'hammer',
    restrictedFactions: ['faction_tiangong', 'faction_shituo'] as FactionId[],
    baseQuality: 'rare',
    baseStats: { physicalAttack: 78, critDamage: 0.2, critRate: 0.04 },
    gemSlots: 2,
    maxEnhance: 12,
    levelRequirement: 30,
    allowedGems: ['ruby', 'topaz', 'diamond'],
  },
  {
    id: 'equip_hammer_5',
    name: '雷霆锤',
    description: '蕴含雷霆之力的神锤。',
    icon: '⚡',
    slot: 'weapon',
    weaponType: 'hammer',
    restrictedFactions: ['faction_tiangong', 'faction_shituo'] as FactionId[],
    baseQuality: 'epic',
    baseStats: { physicalAttack: 110, critDamage: 0.28, critRate: 0.05 },
    gemSlots: 2,
    maxEnhance: 14,
    levelRequirement: 40,
    allowedGems: ['ruby', 'topaz', 'amethyst', 'diamond'],
  },
  {
    id: 'equip_hammer_6',
    name: '巨灵锤',
    description: '上古巨灵神所用之锤。',
    icon: '🏔️',
    slot: 'weapon',
    weaponType: 'hammer',
    restrictedFactions: ['faction_tiangong', 'faction_shituo'] as FactionId[],
    baseQuality: 'epic',
    baseStats: { physicalAttack: 145, critDamage: 0.35, critRate: 0.06 },
    gemSlots: 3,
    maxEnhance: 14,
    levelRequirement: 50,
    allowedGems: ['ruby', 'topaz', 'amethyst', 'diamond'],
  },
];

/** 飘带类武器 - 女儿村、普陀山、盘丝洞 */
const RIBBON_WEAPONS: EquipmentTemplate[] = [
  {
    id: 'equip_ribbon_1',
    name: '丝带',
    description: '柔软的丝带，暗藏玄机。',
    icon: '🎀',
    slot: 'weapon',
    weaponType: 'ribbon',
    restrictedFactions: ['faction_nver', 'faction_putuo', 'faction_pansi'] as FactionId[],
    baseQuality: 'common',
    baseStats: { magicAttack: 12, speed: 3 },
    gemSlots: 1,
    maxEnhance: 10,
    levelRequirement: 1,
    allowedGems: ['sapphire', 'topaz', 'diamond'],
  },
  {
    id: 'equip_ribbon_2',
    name: '彩带',
    description: '五彩斑斓的丝带。',
    icon: '🌈',
    slot: 'weapon',
    weaponType: 'ribbon',
    restrictedFactions: ['faction_nver', 'faction_putuo', 'faction_pansi'] as FactionId[],
    baseQuality: 'common',
    baseStats: { magicAttack: 26, speed: 5 },
    gemSlots: 1,
    maxEnhance: 10,
    levelRequirement: 10,
    allowedGems: ['sapphire', 'topaz', 'diamond'],
  },
  {
    id: 'equip_ribbon_3',
    name: '天蚕丝带',
    description: '由天蚕丝编织，柔韧无比。',
    icon: '✨',
    slot: 'weapon',
    weaponType: 'ribbon',
    restrictedFactions: ['faction_nver', 'faction_putuo', 'faction_pansi'] as FactionId[],
    baseQuality: 'rare',
    baseStats: { magicAttack: 48, speed: 10, dodgeRate: 0.03 },
    gemSlots: 2,
    maxEnhance: 12,
    levelRequirement: 20,
    allowedGems: ['sapphire', 'topaz', 'diamond'],
  },
  {
    id: 'equip_ribbon_4',
    name: '盘丝带',
    description: '盘丝洞秘传的丝带。',
    icon: '🕸️',
    slot: 'weapon',
    weaponType: 'ribbon',
    restrictedFactions: ['faction_nver', 'faction_putuo', 'faction_pansi'] as FactionId[],
    baseQuality: 'rare',
    baseStats: { magicAttack: 72, speed: 15, dodgeRate: 0.05 },
    gemSlots: 2,
    maxEnhance: 12,
    levelRequirement: 30,
    allowedGems: ['sapphire', 'topaz', 'amethyst', 'diamond'],
  },
  {
    id: 'equip_ribbon_5',
    name: '霓裳带',
    description: '仙子霓裳所化，流光溢彩。',
    icon: '💃',
    slot: 'weapon',
    weaponType: 'ribbon',
    restrictedFactions: ['faction_nver', 'faction_putuo', 'faction_pansi'] as FactionId[],
    baseQuality: 'epic',
    baseStats: { magicAttack: 102, speed: 20, dodgeRate: 0.07, maxMp: 80 },
    gemSlots: 2,
    maxEnhance: 14,
    levelRequirement: 40,
    allowedGems: ['sapphire', 'topaz', 'amethyst', 'diamond'],
  },
];

/** 爪类武器 - 狮驼岭、阴曹地府 */
const CLAW_WEAPONS: EquipmentTemplate[] = [
  {
    id: 'equip_claw_1',
    name: '铁爪',
    description: '简单的铁爪，锋利轻便。',
    icon: '🦅',
    slot: 'weapon',
    weaponType: 'claw',
    restrictedFactions: ['faction_shituo', 'faction_difu'] as FactionId[],
    baseQuality: 'common',
    baseStats: { physicalAttack: 11, critRate: 0.02 },
    gemSlots: 1,
    maxEnhance: 10,
    levelRequirement: 1,
    allowedGems: ['ruby', 'topaz', 'diamond'],
  },
  {
    id: 'equip_claw_2',
    name: '钢爪',
    description: '精钢打造的爪，锋锐无比。',
    icon: '🦅',
    slot: 'weapon',
    weaponType: 'claw',
    restrictedFactions: ['faction_shituo', 'faction_difu'] as FactionId[],
    baseQuality: 'common',
    baseStats: { physicalAttack: 24, critRate: 0.03, speed: 3 },
    gemSlots: 1,
    maxEnhance: 10,
    levelRequirement: 10,
    allowedGems: ['ruby', 'topaz', 'diamond'],
  },
  {
    id: 'equip_claw_3',
    name: '虎爪',
    description: '仿猛虎之爪，凶猛异常。',
    icon: '🐯',
    slot: 'weapon',
    weaponType: 'claw',
    restrictedFactions: ['faction_shituo', 'faction_difu'] as FactionId[],
    baseQuality: 'rare',
    baseStats: { physicalAttack: 46, critRate: 0.04, speed: 6, critDamage: 0.1 },
    gemSlots: 2,
    maxEnhance: 12,
    levelRequirement: 20,
    allowedGems: ['ruby', 'topaz', 'diamond'],
  },
  {
    id: 'equip_claw_4',
    name: '龙爪',
    description: '仿龙爪而制，威猛霸气。',
    icon: '🐲',
    slot: 'weapon',
    weaponType: 'claw',
    restrictedFactions: ['faction_shituo', 'faction_difu'] as FactionId[],
    baseQuality: 'rare',
    baseStats: { physicalAttack: 70, critRate: 0.05, speed: 10, critDamage: 0.15 },
    gemSlots: 2,
    maxEnhance: 12,
    levelRequirement: 30,
    allowedGems: ['ruby', 'topaz', 'amethyst', 'diamond'],
  },
  {
    id: 'equip_claw_5',
    name: '修罗爪',
    description: '蕴含修罗之力的神爪。',
    icon: '👹',
    slot: 'weapon',
    weaponType: 'claw',
    restrictedFactions: ['faction_shituo', 'faction_difu'] as FactionId[],
    baseQuality: 'epic',
    baseStats: { physicalAttack: 100, critRate: 0.07, speed: 15, critDamage: 0.22 },
    gemSlots: 2,
    maxEnhance: 14,
    levelRequirement: 40,
    allowedGems: ['ruby', 'topaz', 'amethyst', 'diamond'],
  },
  {
    id: 'equip_claw_6',
    name: '幽冥爪',
    description: '来自幽冥界的神爪，令人闻风丧胆。',
    icon: '💀',
    slot: 'weapon',
    weaponType: 'claw',
    restrictedFactions: ['faction_shituo', 'faction_difu'] as FactionId[],
    baseQuality: 'legendary',
    baseStats: { physicalAttack: 155, critRate: 0.1, speed: 22, critDamage: 0.35 },
    gemSlots: 3,
    maxEnhance: 16,
    levelRequirement: 60,
    allowedGems: ['ruby', 'topaz', 'amethyst', 'diamond'],
  },
];

export const WEAPON_TEMPLATES: EquipmentTemplate[] = [
  ...SWORD_WEAPONS,
  ...STAFF_WEAPONS,
  ...FAN_WEAPONS,
  ...HAMMER_WEAPONS,
  ...SPEAR_WEAPONS,
  ...BLADE_WEAPONS,
  ...RIBBON_WEAPONS,
  ...CLAW_WEAPONS,
];

// ==================== 防具模板 ====================

/** 头盔模板 */
const HELMET_TEMPLATES: EquipmentTemplate[] = [
  // 0-10级
  {
    id: 'equip_helmet_1',
    name: '布帽',
    description: '普通的布帽，提供微弱的防护。',
    icon: '🧢',
    slot: 'helmet',
    baseQuality: 'common',
    baseStats: { physicalDefense: 5, maxHp: 20 },
    gemSlots: 1,
    maxEnhance: 10,
    levelRequirement: 1,
    allowedGems: ['emerald', 'diamond'],
  },
  {
    id: 'equip_helmet_2',
    name: '皮帽',
    description: '皮革制成的帽子，坚韧耐用。',
    icon: '🧢',
    slot: 'helmet',
    baseQuality: 'common',
    baseStats: { physicalDefense: 12, maxHp: 45 },
    gemSlots: 1,
    maxEnhance: 10,
    levelRequirement: 10,
    allowedGems: ['emerald', 'ruby', 'diamond'],
  },
  // 11-30级
  {
    id: 'equip_helmet_3',
    name: '铁盔',
    description: '铁制的头盔，防护力更强。',
    icon: '⛑️',
    slot: 'helmet',
    baseQuality: 'rare',
    baseStats: { physicalDefense: 25, magicDefense: 10, maxHp: 80 },
    gemSlots: 2,
    maxEnhance: 12,
    levelRequirement: 20,
    allowedGems: ['emerald', 'sapphire', 'diamond'],
  },
  {
    id: 'equip_helmet_4',
    name: '精铁盔',
    description: '精铁锻造的头盔，坚固异常。',
    icon: '⛑️',
    slot: 'helmet',
    baseQuality: 'rare',
    baseStats: { physicalDefense: 38, magicDefense: 18, maxHp: 120 },
    gemSlots: 2,
    maxEnhance: 12,
    levelRequirement: 30,
    allowedGems: ['emerald', 'sapphire', 'diamond'],
  },
  // 31-50级
  {
    id: 'equip_helmet_5',
    name: '玄铁盔',
    description: '玄铁打造，刀枪不入。',
    icon: '🪖',
    slot: 'helmet',
    baseQuality: 'epic',
    baseStats: { physicalDefense: 55, magicDefense: 28, maxHp: 180 },
    gemSlots: 2,
    maxEnhance: 14,
    levelRequirement: 40,
    allowedGems: ['emerald', 'sapphire', 'amethyst', 'diamond'],
  },
  {
    id: 'equip_helmet_6',
    name: '金缕盔',
    description: '以金丝缠绕的精钢头盔。',
    icon: '👑',
    slot: 'helmet',
    baseQuality: 'epic',
    baseStats: { physicalDefense: 72, magicDefense: 38, maxHp: 240 },
    gemSlots: 3,
    maxEnhance: 14,
    levelRequirement: 50,
    allowedGems: ['emerald', 'sapphire', 'amethyst', 'diamond'],
  },
  // 51-70级
  {
    id: 'equip_helmet_7',
    name: '龙鳞盔',
    description: '镶嵌龙鳞的神盔。',
    icon: '🐉',
    slot: 'helmet',
    baseQuality: 'legendary',
    baseStats: { physicalDefense: 95, magicDefense: 52, maxHp: 320, speed: 8 },
    gemSlots: 3,
    maxEnhance: 16,
    levelRequirement: 60,
    allowedGems: ['emerald', 'sapphire', 'amethyst', 'diamond'],
  },
  {
    id: 'equip_helmet_8',
    name: '凤羽盔',
    description: '以凤凰羽毛装饰的神盔。',
    icon: '🦅',
    slot: 'helmet',
    baseQuality: 'legendary',
    baseStats: { physicalDefense: 125, magicDefense: 68, maxHp: 420, speed: 12 },
    gemSlots: 3,
    maxEnhance: 18,
    levelRequirement: 70,
    allowedGems: ['emerald', 'sapphire', 'amethyst', 'diamond'],
  },
  // 71+级
  {
    id: 'equip_helmet_9',
    name: '紫金冠',
    description: '紫金铸造的帝王之冠。',
    icon: '👑',
    slot: 'helmet',
    baseQuality: 'mythic',
    baseStats: { physicalDefense: 165, magicDefense: 90, maxHp: 560, speed: 18 },
    gemSlots: 4,
    maxEnhance: 20,
    levelRequirement: 80,
    allowedGems: ['emerald', 'sapphire', 'amethyst', 'diamond'],
  },
];

/** 衣服模板 */
const ARMOR_BODY_TEMPLATES: EquipmentTemplate[] = [
  // 0-10级
  {
    id: 'equip_armor_1',
    name: '布衣',
    description: '简单的布衣，聊胜于无。',
    icon: '👕',
    slot: 'armor',
    baseQuality: 'common',
    baseStats: { physicalDefense: 8, magicDefense: 5, maxHp: 30 },
    gemSlots: 2,
    maxEnhance: 10,
    levelRequirement: 1,
    allowedGems: ['emerald', 'sapphire', 'diamond'],
  },
  {
    id: 'equip_armor_2',
    name: '皮甲',
    description: '皮革制成的护甲，坚韧轻便。',
    icon: '🦺',
    slot: 'armor',
    baseQuality: 'common',
    baseStats: { physicalDefense: 18, magicDefense: 10, maxHp: 65 },
    gemSlots: 2,
    maxEnhance: 10,
    levelRequirement: 10,
    allowedGems: ['emerald', 'sapphire', 'ruby', 'diamond'],
  },
  // 11-30级
  {
    id: 'equip_armor_3',
    name: '锁子甲',
    description: '由铁环扣连而成的护甲。',
    icon: '⛓️',
    slot: 'armor',
    baseQuality: 'rare',
    baseStats: { physicalDefense: 35, magicDefense: 18, maxHp: 120 },
    gemSlots: 2,
    maxEnhance: 12,
    levelRequirement: 20,
    allowedGems: ['emerald', 'sapphire', 'ruby', 'diamond'],
  },
  {
    id: 'equip_armor_4',
    name: '铁甲',
    description: '铁板打造的护甲，坚固厚重。',
    icon: '🛡️',
    slot: 'armor',
    baseQuality: 'rare',
    baseStats: { physicalDefense: 52, magicDefense: 28, maxHp: 180 },
    gemSlots: 2,
    maxEnhance: 12,
    levelRequirement: 30,
    allowedGems: ['emerald', 'sapphire', 'ruby', 'diamond'],
  },
  // 31-50级
  {
    id: 'equip_armor_5',
    name: '精铁甲',
    description: '精铁锻造的护甲，防护力极佳。',
    icon: '🛡️',
    slot: 'armor',
    baseQuality: 'epic',
    baseStats: { physicalDefense: 75, magicDefense: 42, maxHp: 260 },
    gemSlots: 2,
    maxEnhance: 14,
    levelRequirement: 40,
    allowedGems: ['emerald', 'sapphire', 'ruby', 'amethyst', 'diamond'],
  },
  {
    id: 'equip_armor_6',
    name: '金丝甲',
    description: '以金丝编织的华丽护甲。',
    icon: '✨',
    slot: 'armor',
    baseQuality: 'epic',
    baseStats: { physicalDefense: 98, magicDefense: 56, maxHp: 340 },
    gemSlots: 3,
    maxEnhance: 14,
    levelRequirement: 50,
    allowedGems: ['emerald', 'sapphire', 'ruby', 'amethyst', 'diamond'],
  },
  // 51-70级
  {
    id: 'equip_armor_7',
    name: '龙鳞甲',
    description: '以龙鳞打造的护甲，刀枪不入。',
    icon: '🐉',
    slot: 'armor',
    baseQuality: 'legendary',
    baseStats: { physicalDefense: 130, magicDefense: 75, maxHp: 450, dodgeRate: 0.03 },
    gemSlots: 3,
    maxEnhance: 16,
    levelRequirement: 60,
    allowedGems: ['emerald', 'sapphire', 'ruby', 'amethyst', 'diamond'],
  },
  {
    id: 'equip_armor_8',
    name: '凤凰甲',
    description: '蕴含凤凰之力的神甲。',
    icon: '🔥',
    slot: 'armor',
    baseQuality: 'legendary',
    baseStats: { physicalDefense: 170, magicDefense: 98, maxHp: 580, dodgeRate: 0.05 },
    gemSlots: 3,
    maxEnhance: 18,
    levelRequirement: 70,
    allowedGems: ['emerald', 'sapphire', 'ruby', 'amethyst', 'diamond'],
  },
  // 71+级
  {
    id: 'equip_armor_9',
    name: '天神甲',
    description: '天神遗落人间的神甲。',
    icon: '👼',
    slot: 'armor',
    baseQuality: 'mythic',
    baseStats: { physicalDefense: 220, magicDefense: 130, maxHp: 750, dodgeRate: 0.08 },
    gemSlots: 4,
    maxEnhance: 20,
    levelRequirement: 80,
    allowedGems: ['emerald', 'sapphire', 'ruby', 'amethyst', 'diamond'],
  },
];

/** 鞋子模板 */
const BOOTS_TEMPLATES: EquipmentTemplate[] = [
  // 0-10级
  {
    id: 'equip_boots_1',
    name: '布鞋',
    description: '轻便的布鞋，行走无声。',
    icon: '👟',
    slot: 'boots',
    baseQuality: 'common',
    baseStats: { speed: 5, dodgeRate: 0.01 },
    gemSlots: 1,
    maxEnhance: 10,
    levelRequirement: 1,
    allowedGems: ['topaz', 'diamond'],
  },
  {
    id: 'equip_boots_2',
    name: '皮靴',
    description: '皮革制成的靴子，结实耐用。',
    icon: '👢',
    slot: 'boots',
    baseQuality: 'common',
    baseStats: { speed: 10, dodgeRate: 0.02, physicalDefense: 3 },
    gemSlots: 1,
    maxEnhance: 10,
    levelRequirement: 10,
    allowedGems: ['topaz', 'emerald', 'diamond'],
  },
  // 11-30级
  {
    id: 'equip_boots_3',
    name: '追风靴',
    description: '穿戴轻盈，如追风逐电。',
    icon: '💨',
    slot: 'boots',
    baseQuality: 'rare',
    baseStats: { speed: 18, dodgeRate: 0.04, physicalDefense: 8 },
    gemSlots: 2,
    maxEnhance: 12,
    levelRequirement: 20,
    allowedGems: ['topaz', 'emerald', 'diamond'],
  },
  {
    id: 'equip_boots_4',
    name: '疾风靴',
    description: '穿上后身轻如燕，疾如闪电。',
    icon: '⚡',
    slot: 'boots',
    baseQuality: 'rare',
    baseStats: { speed: 26, dodgeRate: 0.05, physicalDefense: 12 },
    gemSlots: 2,
    maxEnhance: 12,
    levelRequirement: 30,
    allowedGems: ['topaz', 'emerald', 'diamond'],
  },
  // 31-50级
  {
    id: 'equip_boots_5',
    name: '踏云靴',
    description: '传说可踏云而行的神靴。',
    icon: '☁️',
    slot: 'boots',
    baseQuality: 'epic',
    baseStats: { speed: 36, dodgeRate: 0.07, physicalDefense: 18 },
    gemSlots: 2,
    maxEnhance: 14,
    levelRequirement: 40,
    allowedGems: ['topaz', 'emerald', 'amethyst', 'diamond'],
  },
  {
    id: 'equip_boots_6',
    name: '缩地靴',
    description: '穿上后可缩地成寸，瞬息千里。',
    icon: '🌟',
    slot: 'boots',
    baseQuality: 'epic',
    baseStats: { speed: 48, dodgeRate: 0.09, physicalDefense: 25 },
    gemSlots: 3,
    maxEnhance: 14,
    levelRequirement: 50,
    allowedGems: ['topaz', 'emerald', 'amethyst', 'diamond'],
  },
  // 51-70级
  {
    id: 'equip_boots_7',
    name: '步云履',
    description: '可平步青云的神靴。',
    icon: '🌙',
    slot: 'boots',
    baseQuality: 'legendary',
    baseStats: { speed: 62, dodgeRate: 0.12, physicalDefense: 32 },
    gemSlots: 3,
    maxEnhance: 16,
    levelRequirement: 60,
    allowedGems: ['topaz', 'emerald', 'amethyst', 'diamond'],
  },
  {
    id: 'equip_boots_8',
    name: '七星履',
    description: '以北斗七星之力加持的神靴。',
    icon: '⭐',
    slot: 'boots',
    baseQuality: 'legendary',
    baseStats: { speed: 80, dodgeRate: 0.15, physicalDefense: 42 },
    gemSlots: 3,
    maxEnhance: 18,
    levelRequirement: 70,
    allowedGems: ['topaz', 'emerald', 'amethyst', 'diamond'],
  },
  // 71+级
  {
    id: 'equip_boots_9',
    name: '风火轮',
    description: '哪吒所用神靴，脚踏风火。',
    icon: '🔥',
    slot: 'boots',
    baseQuality: 'mythic',
    baseStats: { speed: 105, dodgeRate: 0.2, physicalDefense: 55 },
    gemSlots: 4,
    maxEnhance: 20,
    levelRequirement: 80,
    allowedGems: ['topaz', 'emerald', 'amethyst', 'diamond'],
  },
];

/** 腰带模板 */
const BELT_TEMPLATES: EquipmentTemplate[] = [
  // 0-10级
  {
    id: 'equip_belt_1',
    name: '皮带',
    description: '普通的皮带，可以挂载物品。',
    icon: '👙',
    slot: 'belt',
    baseQuality: 'common',
    baseStats: { maxHp: 25 },
    gemSlots: 1,
    maxEnhance: 10,
    levelRequirement: 1,
    allowedGems: ['emerald', 'diamond'],
  },
  {
    id: 'equip_belt_2',
    name: '牛皮带',
    description: '由牛皮制成的腰带，结实耐用。',
    icon: '🎽',
    slot: 'belt',
    baseQuality: 'common',
    baseStats: { maxHp: 55, physicalDefense: 3 },
    gemSlots: 1,
    maxEnhance: 10,
    levelRequirement: 10,
    allowedGems: ['emerald', 'ruby', 'diamond'],
  },
  // 11-30级
  {
    id: 'equip_belt_3',
    name: '玄铁带',
    description: '镶嵌玄铁片的腰带。',
    icon: '⛓️',
    slot: 'belt',
    baseQuality: 'rare',
    baseStats: { maxHp: 100, physicalDefense: 8 },
    gemSlots: 2,
    maxEnhance: 12,
    levelRequirement: 20,
    allowedGems: ['emerald', 'ruby', 'diamond'],
  },
  {
    id: 'equip_belt_4',
    name: '金丝带',
    description: '以金丝编织的华丽腰带。',
    icon: '✨',
    slot: 'belt',
    baseQuality: 'rare',
    baseStats: { maxHp: 155, physicalDefense: 14, magicDefense: 8 },
    gemSlots: 2,
    maxEnhance: 12,
    levelRequirement: 30,
    allowedGems: ['emerald', 'ruby', 'sapphire', 'diamond'],
  },
  // 31-50级
  {
    id: 'equip_belt_5',
    name: '龙鳞带',
    description: '以龙鳞装饰的腰带。',
    icon: '🐉',
    slot: 'belt',
    baseQuality: 'epic',
    baseStats: { maxHp: 225, physicalDefense: 22, magicDefense: 14 },
    gemSlots: 2,
    maxEnhance: 14,
    levelRequirement: 40,
    allowedGems: ['emerald', 'ruby', 'sapphire', 'amethyst', 'diamond'],
  },
  {
    id: 'equip_belt_6',
    name: '圣兽带',
    description: '蕴含圣兽之力的腰带。',
    icon: '🦁',
    slot: 'belt',
    baseQuality: 'epic',
    baseStats: { maxHp: 310, physicalDefense: 30, magicDefense: 22 },
    gemSlots: 3,
    maxEnhance: 14,
    levelRequirement: 50,
    allowedGems: ['emerald', 'ruby', 'sapphire', 'amethyst', 'diamond'],
  },
  // 51-70级
  {
    id: 'equip_belt_7',
    name: '天神带',
    description: '天神遗落的腰带。',
    icon: '👼',
    slot: 'belt',
    baseQuality: 'legendary',
    baseStats: { maxHp: 420, physicalDefense: 42, magicDefense: 32, maxMp: 80 },
    gemSlots: 3,
    maxEnhance: 16,
    levelRequirement: 60,
    allowedGems: ['emerald', 'ruby', 'sapphire', 'amethyst', 'diamond'],
  },
  {
    id: 'equip_belt_8',
    name: '乾坤带',
    description: '内蕴乾坤的神奇腰带。',
    icon: '☯️',
    slot: 'belt',
    baseQuality: 'legendary',
    baseStats: { maxHp: 550, physicalDefense: 55, magicDefense: 42, maxMp: 120 },
    gemSlots: 3,
    maxEnhance: 18,
    levelRequirement: 70,
    allowedGems: ['emerald', 'ruby', 'sapphire', 'amethyst', 'diamond'],
  },
  // 71+级
  {
    id: 'equip_belt_9',
    name: '混沌带',
    description: '混沌之力凝聚的腰带。',
    icon: '🌌',
    slot: 'belt',
    baseQuality: 'mythic',
    baseStats: { maxHp: 720, physicalDefense: 72, magicDefense: 55, maxMp: 180 },
    gemSlots: 4,
    maxEnhance: 20,
    levelRequirement: 80,
    allowedGems: ['emerald', 'ruby', 'sapphire', 'amethyst', 'diamond'],
  },
];

export const ARMOR_TEMPLATES: EquipmentTemplate[] = [
  ...HELMET_TEMPLATES,
  ...ARMOR_BODY_TEMPLATES,
  ...BOOTS_TEMPLATES,
  ...BELT_TEMPLATES,
];

// ==================== 饰品模板 ====================

/** 项链模板 */
const NECKLACE_TEMPLATES: EquipmentTemplate[] = [
  {
    id: 'equip_necklace_1',
    name: '铜项链',
    description: '简单的铜制项链。',
    icon: '📿',
    slot: 'necklace',
    baseQuality: 'common',
    baseStats: { magicDefense: 5, maxMp: 20 },
    gemSlots: 1,
    maxEnhance: 10,
    levelRequirement: 1,
    allowedGems: ['sapphire', 'amethyst', 'diamond'],
  },
  {
    id: 'equip_necklace_2',
    name: '银项链',
    description: '银制的项链，光洁如新。',
    icon: '📿',
    slot: 'necklace',
    baseQuality: 'common',
    baseStats: { magicDefense: 12, maxMp: 45 },
    gemSlots: 1,
    maxEnhance: 10,
    levelRequirement: 10,
    allowedGems: ['sapphire', 'amethyst', 'diamond'],
  },
  {
    id: 'equip_necklace_3',
    name: '金项链',
    description: '纯金打造的项链。',
    icon: '📿',
    slot: 'necklace',
    baseQuality: 'rare',
    baseStats: { magicDefense: 22, maxMp: 85 },
    gemSlots: 2,
    maxEnhance: 12,
    levelRequirement: 20,
    allowedGems: ['sapphire', 'amethyst', 'diamond'],
  },
  {
    id: 'equip_necklace_4',
    name: '翡翠项链',
    description: '镶嵌翡翠的贵重项链。',
    icon: '💚',
    slot: 'necklace',
    baseQuality: 'rare',
    baseStats: { magicDefense: 35, maxMp: 130, maxHp: 40 },
    gemSlots: 2,
    maxEnhance: 12,
    levelRequirement: 30,
    allowedGems: ['sapphire', 'amethyst', 'emerald', 'diamond'],
  },
  {
    id: 'equip_necklace_5',
    name: '琥珀项链',
    description: '由古老琥珀制成的项链。',
    icon: '🧡',
    slot: 'necklace',
    baseQuality: 'epic',
    baseStats: { magicDefense: 52, maxMp: 190, maxHp: 70 },
    gemSlots: 2,
    maxEnhance: 14,
    levelRequirement: 40,
    allowedGems: ['sapphire', 'amethyst', 'emerald', 'diamond'],
  },
  {
    id: 'equip_necklace_6',
    name: '珍珠项链',
    description: '由东海珍珠串成的项链。',
    icon: '🤍',
    slot: 'necklace',
    baseQuality: 'epic',
    baseStats: { magicDefense: 72, maxMp: 260, maxHp: 100 },
    gemSlots: 3,
    maxEnhance: 14,
    levelRequirement: 50,
    allowedGems: ['sapphire', 'amethyst', 'emerald', 'diamond'],
  },
  {
    id: 'equip_necklace_7',
    name: '龙珠项链',
    description: '以龙珠为核心的项链。',
    icon: '🐉',
    slot: 'necklace',
    baseQuality: 'legendary',
    baseStats: { magicDefense: 98, maxMp: 350, maxHp: 150, magicAttack: 25 },
    gemSlots: 3,
    maxEnhance: 16,
    levelRequirement: 60,
    allowedGems: ['sapphire', 'amethyst', 'emerald', 'diamond'],
  },
  {
    id: 'equip_necklace_8',
    name: '凤凰心',
    description: '传说由凤凰之心化作的项链。',
    icon: '🔥',
    slot: 'necklace',
    baseQuality: 'legendary',
    baseStats: { magicDefense: 130, maxMp: 460, maxHp: 200, magicAttack: 40 },
    gemSlots: 3,
    maxEnhance: 18,
    levelRequirement: 70,
    allowedGems: ['sapphire', 'amethyst', 'emerald', 'diamond'],
  },
  {
    id: 'equip_necklace_9',
    name: '女娲石',
    description: '女娲补天所遗神石。',
    icon: '🌈',
    slot: 'necklace',
    baseQuality: 'mythic',
    baseStats: { magicDefense: 175, maxMp: 600, maxHp: 280, magicAttack: 60 },
    gemSlots: 4,
    maxEnhance: 20,
    levelRequirement: 80,
    allowedGems: ['sapphire', 'amethyst', 'emerald', 'diamond'],
  },
];

/** 护符模板 */
const CHARM_TEMPLATES: EquipmentTemplate[] = [
  {
    id: 'equip_charm_1',
    name: '护身符',
    description: '据说能带来好运的护身符。',
    icon: '🔱',
    slot: 'charm',
    baseQuality: 'common',
    baseStats: { critRate: 0.01, dodgeRate: 0.01 },
    gemSlots: 1,
    maxEnhance: 10,
    levelRequirement: 1,
    allowedGems: ['topaz', 'amethyst', 'diamond'],
  },
  {
    id: 'equip_charm_2',
    name: '幸运符',
    description: '能带来好运的符咒。',
    icon: '🍀',
    slot: 'charm',
    baseQuality: 'common',
    baseStats: { critRate: 0.02, dodgeRate: 0.02, hitRate: 0.02 },
    gemSlots: 1,
    maxEnhance: 10,
    levelRequirement: 10,
    allowedGems: ['topaz', 'amethyst', 'diamond'],
  },
  {
    id: 'equip_charm_3',
    name: '驱邪符',
    description: '可驱邪避凶的符咒。',
    icon: '📜',
    slot: 'charm',
    baseQuality: 'rare',
    baseStats: { critRate: 0.03, dodgeRate: 0.03, hitRate: 0.03, magicDefense: 8 },
    gemSlots: 2,
    maxEnhance: 12,
    levelRequirement: 20,
    allowedGems: ['topaz', 'amethyst', 'diamond'],
  },
  {
    id: 'equip_charm_4',
    name: '天师符',
    description: '道家天师所绘的符咒。',
    icon: '☯️',
    slot: 'charm',
    baseQuality: 'rare',
    baseStats: { critRate: 0.04, dodgeRate: 0.04, hitRate: 0.04, magicDefense: 15 },
    gemSlots: 2,
    maxEnhance: 12,
    levelRequirement: 30,
    allowedGems: ['topaz', 'amethyst', 'sapphire', 'diamond'],
  },
  {
    id: 'equip_charm_5',
    name: '镇魔符',
    description: '可镇压妖魔的强力符咒。',
    icon: '📜',
    slot: 'charm',
    baseQuality: 'epic',
    baseStats: { critRate: 0.06, dodgeRate: 0.05, hitRate: 0.05, magicDefense: 25, maxMp: 50 },
    gemSlots: 2,
    maxEnhance: 14,
    levelRequirement: 40,
    allowedGems: ['topaz', 'amethyst', 'sapphire', 'diamond'],
  },
  {
    id: 'equip_charm_6',
    name: '神佑符',
    description: '蕴含神佑之力的符咒。',
    icon: '👼',
    slot: 'charm',
    baseQuality: 'epic',
    baseStats: { critRate: 0.08, dodgeRate: 0.07, hitRate: 0.07, magicDefense: 38, maxMp: 80 },
    gemSlots: 3,
    maxEnhance: 14,
    levelRequirement: 50,
    allowedGems: ['topaz', 'amethyst', 'sapphire', 'diamond'],
  },
  {
    id: 'equip_charm_7',
    name: '九天符',
    description: '九天玄女所传的符咒。',
    icon: '⚡',
    slot: 'charm',
    baseQuality: 'legendary',
    baseStats: { critRate: 0.1, dodgeRate: 0.09, hitRate: 0.09, magicDefense: 52, maxMp: 120 },
    gemSlots: 3,
    maxEnhance: 16,
    levelRequirement: 60,
    allowedGems: ['topaz', 'amethyst', 'sapphire', 'diamond'],
  },
  {
    id: 'equip_charm_8',
    name: '天命符',
    description: '蕴含天命的终极符咒。',
    icon: '🌟',
    slot: 'charm',
    baseQuality: 'legendary',
    baseStats: { critRate: 0.13, dodgeRate: 0.12, hitRate: 0.12, magicDefense: 70, maxMp: 160 },
    gemSlots: 3,
    maxEnhance: 18,
    levelRequirement: 70,
    allowedGems: ['topaz', 'amethyst', 'sapphire', 'diamond'],
  },
];

/** 戒指模板 */
const RING_TEMPLATES: EquipmentTemplate[] = [
  {
    id: 'equip_ring_1',
    name: '铜戒指',
    description: '普通的铜戒指。',
    icon: '💍',
    slot: 'ring1',
    baseQuality: 'common',
    baseStats: { physicalAttack: 3, magicAttack: 3 },
    gemSlots: 1,
    maxEnhance: 10,
    levelRequirement: 1,
    allowedGems: ['ruby', 'sapphire', 'diamond'],
  },
  {
    id: 'equip_ring_2',
    name: '银戒指',
    description: '银制的戒指。',
    icon: '💍',
    slot: 'ring1',
    baseQuality: 'common',
    baseStats: { physicalAttack: 6, magicAttack: 6, maxMp: 15 },
    gemSlots: 1,
    maxEnhance: 10,
    levelRequirement: 10,
    allowedGems: ['ruby', 'sapphire', 'diamond'],
  },
  {
    id: 'equip_ring_3',
    name: '金戒指',
    description: '纯金打造的戒指。',
    icon: '💍',
    slot: 'ring1',
    baseQuality: 'rare',
    baseStats: { physicalAttack: 12, magicAttack: 12, maxMp: 35, critRate: 0.01 },
    gemSlots: 2,
    maxEnhance: 12,
    levelRequirement: 20,
    allowedGems: ['ruby', 'sapphire', 'diamond'],
  },
  {
    id: 'equip_ring_4',
    name: '红宝石戒指',
    description: '镶嵌红宝石的戒指。',
    icon: '❤️',
    slot: 'ring1',
    baseQuality: 'rare',
    baseStats: { physicalAttack: 18, magicAttack: 18, maxMp: 55, critRate: 0.02 },
    gemSlots: 2,
    maxEnhance: 12,
    levelRequirement: 30,
    allowedGems: ['ruby', 'sapphire', 'amethyst', 'diamond'],
  },
  {
    id: 'equip_ring_5',
    name: '蓝宝石戒指',
    description: '镶嵌蓝宝石的戒指。',
    icon: '💙',
    slot: 'ring1',
    baseQuality: 'epic',
    baseStats: { physicalAttack: 26, magicAttack: 26, maxMp: 85, critRate: 0.03 },
    gemSlots: 2,
    maxEnhance: 14,
    levelRequirement: 40,
    allowedGems: ['ruby', 'sapphire', 'amethyst', 'diamond'],
  },
  {
    id: 'equip_ring_6',
    name: '紫晶戒指',
    description: '镶嵌紫水晶的戒指。',
    icon: '💜',
    slot: 'ring1',
    baseQuality: 'epic',
    baseStats: { physicalAttack: 36, magicAttack: 36, maxMp: 120, critRate: 0.04, critDamage: 0.08 },
    gemSlots: 3,
    maxEnhance: 14,
    levelRequirement: 50,
    allowedGems: ['ruby', 'sapphire', 'amethyst', 'diamond'],
  },
  {
    id: 'equip_ring_7',
    name: '龙纹戒指',
    description: '刻有龙纹的神秘戒指。',
    icon: '🐉',
    slot: 'ring1',
    baseQuality: 'legendary',
    baseStats: { physicalAttack: 50, magicAttack: 50, maxMp: 165, critRate: 0.05, critDamage: 0.12 },
    gemSlots: 3,
    maxEnhance: 16,
    levelRequirement: 60,
    allowedGems: ['ruby', 'sapphire', 'amethyst', 'diamond'],
  },
  {
    id: 'equip_ring_8',
    name: '乾坤戒',
    description: '内蕴乾坤的神奇戒指。',
    icon: '☯️',
    slot: 'ring1',
    baseQuality: 'legendary',
    baseStats: { physicalAttack: 68, magicAttack: 68, maxMp: 220, critRate: 0.07, critDamage: 0.18 },
    gemSlots: 3,
    maxEnhance: 18,
    levelRequirement: 70,
    allowedGems: ['ruby', 'sapphire', 'amethyst', 'diamond'],
  },
  {
    id: 'equip_ring_9',
    name: '混沌戒',
    description: '蕴含混沌之力的戒指。',
    icon: '🌀',
    slot: 'ring1',
    baseQuality: 'mythic',
    baseStats: { physicalAttack: 92, magicAttack: 92, maxMp: 300, critRate: 0.1, critDamage: 0.25 },
    gemSlots: 4,
    maxEnhance: 20,
    levelRequirement: 80,
    allowedGems: ['ruby', 'sapphire', 'amethyst', 'diamond'],
  },
];

export const ACCESSORY_TEMPLATES: EquipmentTemplate[] = [
  ...NECKLACE_TEMPLATES,
  ...CHARM_TEMPLATES,
  ...RING_TEMPLATES,
];

/** 所有装备模板 */
export const EQUIPMENT_TEMPLATES: Record<string, EquipmentTemplate> = {};

// 初始化装备模板映射
[...WEAPON_TEMPLATES, ...ARMOR_TEMPLATES, ...ACCESSORY_TEMPLATES].forEach((template) => {
  EQUIPMENT_TEMPLATES[template.id] = template;
});

/** 获取装备模板 */
export function getEquipmentTemplate(id: string): EquipmentTemplate | undefined {
  return EQUIPMENT_TEMPLATES[id];
}

/** 获取指定槽位的装备模板列表 */
export function getEquipmentTemplatesBySlot(slot: EquipmentSlot): EquipmentTemplate[] {
  return Object.values(EQUIPMENT_TEMPLATES).filter((t) => t.slot === slot);
}

/** 获取所有装备模板 */
export function getAllEquipmentTemplates(): EquipmentTemplate[] {
  return Object.values(EQUIPMENT_TEMPLATES);
}

/** 获取指定等级范围内的装备模板 */
export function getEquipmentTemplatesByLevelRange(minLevel: number, maxLevel: number): EquipmentTemplate[] {
  return Object.values(EQUIPMENT_TEMPLATES).filter(
    (t) => t.levelRequirement >= minLevel && t.levelRequirement <= maxLevel
  );
}

/** 获取指定品质的装备模板 */
export function getEquipmentTemplatesByQuality(quality: string): EquipmentTemplate[] {
  return Object.values(EQUIPMENT_TEMPLATES).filter((t) => t.baseQuality === quality);
}

/** 根据门派获取可用武器模板 */
export function getWeaponTemplatesByFaction(factionId: FactionId): EquipmentTemplate[] {
  return WEAPON_TEMPLATES.filter((t) => {
    if (!t.restrictedFactions) return true;
    return t.restrictedFactions.includes(factionId);
  });
}

/** 检查门派是否能使用指定装备 */
export function canFactionUseEquipment(factionId: FactionId, templateId: string): boolean {
  const template = EQUIPMENT_TEMPLATES[templateId];
  if (!template) return false;
  if (!template.restrictedFactions) return true;
  return template.restrictedFactions.includes(factionId);
}

/** 获取指定武器类型的模板列表 */
export function getWeaponTemplatesByType(weaponType: WeaponType): EquipmentTemplate[] {
  return WEAPON_TEMPLATES.filter((t) => t.weaponType === weaponType);
}

/** 获取指定门派可用的武器类型 */
export function getWeaponTypesForFaction(factionId: FactionId): WeaponType[] {
  const templates = getWeaponTemplatesByFaction(factionId);
  const types = new Set<WeaponType>();
  templates.forEach((t) => {
    if (t.weaponType) {
      types.add(t.weaponType);
    }
  });
  return Array.from(types);
}
