// 物品模板数据

import type { ItemTemplate } from '@/types';
import type { GemType } from '@/types/equipment';
import { GEM_TYPE_CONFIG, GEM_LEVEL_CONFIG, getGemName, getGemSellPrice } from './gems';

/** 消耗品模板 */
export const CONSUMABLE_TEMPLATES: ItemTemplate[] = [
  {
    id: 'item_hp_potion_small',
    name: '小型生命药水',
    description: '恢复50点HP。',
    icon: '🧪',
    type: 'consumable',
    quality: 'common',
    maxStack: 99,
    usable: true,
    effects: [{ type: 'heal_hp', value: 50 }],
    useRequirements: { target: 'self' },
    buyPrice: 50,
    sellPrice: 20,
    sources: ['商店', '掉落'],
  },
  {
    id: 'item_hp_potion_medium',
    name: '中型生命药水',
    description: '恢复150点HP。',
    icon: '🧪',
    type: 'consumable',
    quality: 'rare',
    maxStack: 99,
    usable: true,
    effects: [{ type: 'heal_hp', value: 150 }],
    useRequirements: { minLevel: 10, target: 'self' },
    buyPrice: 150,
    sellPrice: 60,
    sources: ['商店', '掉落'],
  },
  {
    id: 'item_hp_potion_large',
    name: '大型生命药水',
    description: '恢复400点HP。',
    icon: '🧪',
    type: 'consumable',
    quality: 'epic',
    maxStack: 99,
    usable: true,
    effects: [{ type: 'heal_hp', value: 400 }],
    useRequirements: { minLevel: 20, target: 'self' },
    buyPrice: 400,
    sellPrice: 160,
    sources: ['商店', '副本掉落'],
  },
  {
    id: 'item_hp_potion_super',
    name: '超级生命药水',
    description: '恢复30%HP。',
    icon: '❤️',
    type: 'consumable',
    quality: 'legendary',
    maxStack: 99,
    usable: true,
    effects: [{ type: 'heal_hp_percent', value: 30 }],
    useRequirements: { minLevel: 30, target: 'self' },
    buyPrice: 1000,
    sellPrice: 400,
    sources: ['副本掉落', '活动'],
  },
  {
    id: 'item_mp_potion_small',
    name: '小型法力药水',
    description: '恢复30点MP。',
    icon: '💧',
    type: 'consumable',
    quality: 'common',
    maxStack: 99,
    usable: true,
    effects: [{ type: 'heal_mp', value: 30 }],
    useRequirements: { target: 'self' },
    buyPrice: 60,
    sellPrice: 25,
    sources: ['商店', '掉落'],
  },
  {
    id: 'item_mp_potion_medium',
    name: '中型法力药水',
    description: '恢复100点MP。',
    icon: '💧',
    type: 'consumable',
    quality: 'rare',
    maxStack: 99,
    usable: true,
    effects: [{ type: 'heal_mp', value: 100 }],
    useRequirements: { minLevel: 10, target: 'self' },
    buyPrice: 180,
    sellPrice: 75,
    sources: ['商店', '掉落'],
  },
  {
    id: 'item_mp_potion_large',
    name: '大型法力药水',
    description: '恢复250点MP。',
    icon: '💧',
    type: 'consumable',
    quality: 'epic',
    maxStack: 99,
    usable: true,
    effects: [{ type: 'heal_mp', value: 250 }],
    useRequirements: { minLevel: 20, target: 'self' },
    buyPrice: 500,
    sellPrice: 200,
    sources: ['商店', '副本掉落'],
  },
  {
    id: 'item_mp_potion_super',
    name: '超级法力药水',
    description: '恢复30%MP。',
    icon: '💙',
    type: 'consumable',
    quality: 'legendary',
    maxStack: 99,
    usable: true,
    effects: [{ type: 'heal_mp_percent', value: 30 }],
    useRequirements: { minLevel: 30, target: 'self' },
    buyPrice: 1200,
    sellPrice: 480,
    sources: ['副本掉落', '活动'],
  },
  {
    id: 'item_full_restore',
    name: '全复药',
    description: '完全恢复HP和MP。',
    icon: '⭐',
    type: 'consumable',
    quality: 'legendary',
    maxStack: 20,
    usable: true,
    effects: [
      { type: 'heal_hp_percent', value: 100 },
      { type: 'heal_mp_percent', value: 100 },
    ],
    useRequirements: { minLevel: 25, target: 'self' },
    buyPrice: 2000,
    sellPrice: 800,
    sources: ['副本掉落', '活动'],
  },
  {
    id: 'item_cure_pill',
    name: '解毒丸',
    description: '解除中毒状态。',
    icon: '💊',
    type: 'consumable',
    quality: 'common',
    maxStack: 99,
    usable: true,
    effects: [{ type: 'cure' }],
    useRequirements: { target: 'self' },
    buyPrice: 100,
    sellPrice: 40,
    sources: ['商店', '掉落'],
  },
];

/** 任务物品模板 */
export const QUEST_TEMPLATES: ItemTemplate[] = [
  // 第一章相关
  {
    id: 'item_village_letter',
    name: '村长的信',
    description: '村长写给长安城店小二的推荐信。',
    icon: '✉️',
    type: 'quest',
    quality: 'common',
    maxStack: 1,
    usable: false,
    buyPrice: 0,
    sellPrice: 0,
    sources: ['任务奖励'],
    questId: 'main_1_5',
  },
  {
    id: 'item_crab_pearl',
    name: '蟹珠',
    description: '蟹精体内的珠子，晶莹剔透。',
    icon: '🦪',
    type: 'quest',
    quality: 'rare',
    maxStack: 10,
    usable: false,
    buyPrice: 0,
    sellPrice: 100,
    sources: ['蟹精掉落'],
    questId: 'main_1_5',
  },
  // 第三章相关
  {
    id: 'item_animal_tooth',
    name: '动物碎齿',
    description: '从动物身上掉落的碎齿，可以作为药引。',
    icon: '🦷',
    type: 'quest',
    quality: 'common',
    maxStack: 99,
    usable: false,
    buyPrice: 0,
    sellPrice: 10,
    sources: ['怪物掉落'],
    questId: 'main_3_3',
  },
  {
    id: 'item_xianlu',
    name: '仙露',
    description: '仙泉中获取的神奇露水，可以解百毒。',
    icon: '💦',
    type: 'quest',
    quality: 'epic',
    maxStack: 10,
    usable: false,
    buyPrice: 0,
    sellPrice: 500,
    sources: ['仙泉'],
    questId: 'main_3_4',
  },
  // 第七章相关
  {
    id: 'item_earth_spirit_bead',
    name: '土灵珠',
    description: '传说中的土灵珠，蕴含大地的力量。',
    icon: '🔮',
    type: 'quest',
    quality: 'legendary',
    maxStack: 1,
    usable: false,
    buyPrice: 0,
    sellPrice: 0,
    sources: ['赤血龙王掉落'],
    questId: 'main_7_5',
  },
  {
    id: 'item_taoist_charm',
    name: '道家符咒',
    description: '清风道长留下的符咒。',
    icon: '📜',
    type: 'quest',
    quality: 'rare',
    maxStack: 10,
    usable: false,
    buyPrice: 0,
    sellPrice: 50,
    sources: ['任务奖励'],
    questId: 'main_7_4',
  },
  // 通用任务物品
  {
    id: 'item_herb',
    name: '草药',
    description: '普通的草药，可以用于制药。',
    icon: '🌿',
    type: 'quest',
    quality: 'common',
    maxStack: 99,
    usable: false,
    buyPrice: 0,
    sellPrice: 5,
    sources: ['采集', '掉落'],
    questId: 'side_herb_collector',
  },
  {
    id: 'item_black_badge',
    name: '黑衣人令牌',
    description: '天法国黑衣人的身份令牌。',
    icon: '🔖',
    type: 'quest',
    quality: 'rare',
    maxStack: 10,
    usable: false,
    buyPrice: 0,
    sellPrice: 100,
    sources: ['黑衣人掉落'],
    questId: 'main_4_2',
  },
  {
    id: 'item_jade_pendant',
    name: '玉佩',
    description: '萧晓月随身携带的玉佩。',
    icon: '💎',
    type: 'quest',
    quality: 'rare',
    maxStack: 1,
    usable: false,
    buyPrice: 0,
    sellPrice: 0,
    sources: ['萧晓月掉落'],
    questId: 'main_5_4',
  },
  {
    id: 'item_terracotta_shard',
    name: '兵马俑碎片',
    description: '兵马俑被打碎后的残片。',
    icon: '🏺',
    type: 'quest',
    quality: 'common',
    maxStack: 99,
    usable: false,
    buyPrice: 0,
    sellPrice: 20,
    sources: ['兵马俑掉落'],
    questId: 'main_8_2',
  },
];

/** 材料模板 */
export const MATERIAL_TEMPLATES: ItemTemplate[] = [
  // ===== 通用材料 =====
  {
    id: 'item_iron_ore',
    name: '铁矿石',
    description: '用于打造装备的基础材料。',
    icon: '🪨',
    type: 'material',
    quality: 'common',
    maxStack: 999,
    usable: false,
    buyPrice: 10,
    sellPrice: 5,
    sources: ['采集', '掉落'],
    materialSubType: 'craft',
  },
  {
    id: 'item_copper_ore',
    name: '铜矿石',
    description: '用于打造基础装备的材料。',
    icon: '🔶',
    type: 'material',
    quality: 'common',
    maxStack: 999,
    usable: false,
    buyPrice: 8,
    sellPrice: 4,
    sources: ['采集', '掉落'],
    materialSubType: 'craft',
  },
  {
    id: 'item_silver_ore',
    name: '银矿石',
    description: '用于打造高级装备的材料。',
    icon: '⬜',
    type: 'material',
    quality: 'rare',
    maxStack: 999,
    usable: false,
    buyPrice: 30,
    sellPrice: 12,
    sources: ['采集', '副本掉落'],
    materialSubType: 'craft',
  },
  {
    id: 'item_gold_ore',
    name: '金矿石',
    description: '用于打造稀有装备的珍贵材料。',
    icon: '🟡',
    type: 'material',
    quality: 'rare',
    maxStack: 999,
    usable: false,
    buyPrice: 100,
    sellPrice: 40,
    sources: ['采集', '副本掉落'],
    materialSubType: 'craft',
  },
  {
    id: 'item_pearl',
    name: '珍珠',
    description: '东海特产的珍珠，价值不菲。',
    icon: '🦪',
    type: 'material',
    quality: 'rare',
    maxStack: 99,
    usable: false,
    buyPrice: 100,
    sellPrice: 40,
    sources: ['副本掉落'],
    materialSubType: 'craft',
  },

  // ===== 怪物掉落材料 =====
  {
    id: 'item_meat',
    name: '兽肉',
    description: '从野兽身上获取的肉，可以食用或出售。',
    icon: '🥩',
    type: 'material',
    quality: 'common',
    maxStack: 999,
    usable: false,
    buyPrice: 5,
    sellPrice: 2,
    sources: ['怪物掉落'],
    materialSubType: 'general',
  },
  {
    id: 'item_fur',
    name: '兽皮',
    description: '从野兽身上剥下的皮毛。',
    icon: '🧥',
    type: 'material',
    quality: 'common',
    maxStack: 999,
    usable: false,
    buyPrice: 15,
    sellPrice: 6,
    sources: ['怪物掉落'],
    materialSubType: 'craft',
  },
  {
    id: 'item_bone',
    name: '兽骨',
    description: '从野兽身上获取的骨头，可用于制作。',
    icon: '🦴',
    type: 'material',
    quality: 'common',
    maxStack: 999,
    usable: false,
    buyPrice: 12,
    sellPrice: 5,
    sources: ['怪物掉落'],
    materialSubType: 'craft',
  },
  {
    id: 'item_feather',
    name: '羽毛',
    description: '从鸟类身上掉落的羽毛。',
    icon: '🪶',
    type: 'material',
    quality: 'common',
    maxStack: 999,
    usable: false,
    buyPrice: 20,
    sellPrice: 8,
    sources: ['怪物掉落'],
    materialSubType: 'craft',
  },
  {
    id: 'item_spider_silk',
    name: '蛛丝',
    description: '蜘蛛吐出的丝线，坚韧有弹性。',
    icon: '🕸️',
    type: 'material',
    quality: 'rare',
    maxStack: 999,
    usable: false,
    buyPrice: 30,
    sellPrice: 12,
    sources: ['蜘蛛类怪物掉落'],
    materialSubType: 'craft',
  },
  {
    id: 'item_poison_gland',
    name: '毒腺',
    description: '从毒物身上提取的腺体，可用于制毒。',
    icon: '☠️',
    type: 'material',
    quality: 'rare',
    maxStack: 99,
    usable: false,
    buyPrice: 80,
    sellPrice: 32,
    sources: ['毒物类怪物掉落'],
    materialSubType: 'craft',
  },

  // ===== 强化材料 =====
  {
    id: 'item_enhance_stone',
    name: '强化石',
    description: '用于装备强化的基础材料。',
    icon: '💎',
    type: 'material',
    quality: 'rare',
    maxStack: 999,
    usable: false,
    buyPrice: 100,
    sellPrice: 40,
    sources: ['副本掉落', '商店'],
    materialSubType: 'enhance',
  },
  {
    id: 'item_enhance_stone_advanced',
    name: '高级强化石',
    description: '用于装备强化的高级材料，成功率更高。',
    icon: '💠',
    type: 'material',
    quality: 'rare',
    maxStack: 999,
    usable: false,
    buyPrice: 300,
    sellPrice: 120,
    sources: ['副本掉落'],
    materialSubType: 'enhance',
  },
  {
    id: 'item_enhance_stone_supreme',
    name: '至尊强化石',
    description: '顶级的强化材料，大幅提高成功率。',
    icon: '🔥',
    type: 'material',
    quality: 'epic',
    maxStack: 99,
    usable: false,
    buyPrice: 800,
    sellPrice: 320,
    sources: ['Boss掉落'],
    materialSubType: 'enhance',
  },
  {
    id: 'item_protection_charm',
    name: '护符',
    description: '强化失败时保护装备不降级。',
    icon: '🛡️',
    type: 'material',
    quality: 'rare',
    maxStack: 99,
    usable: false,
    buyPrice: 500,
    sellPrice: 200,
    sources: ['商店', '副本掉落'],
    materialSubType: 'enhance',
  },
  {
    id: 'item_lucky_charm',
    name: '幸运符',
    description: '强化时提高成功率10%。',
    icon: '🍀',
    type: 'material',
    quality: 'epic',
    maxStack: 99,
    usable: false,
    buyPrice: 1000,
    sellPrice: 400,
    sources: ['活动', '商城'],
    materialSubType: 'enhance',
  },

  // ===== 洗练材料 =====
  {
    id: 'item_reforge_stone',
    name: '洗练石',
    description: '用于装备词条洗练的基础材料。',
    icon: '🔮',
    type: 'material',
    quality: 'rare',
    maxStack: 999,
    usable: false,
    buyPrice: 150,
    sellPrice: 60,
    sources: ['副本掉落', '商店'],
    materialSubType: 'reforge',
  },
  {
    id: 'item_reforge_stone_advanced',
    name: '高级洗练石',
    description: '用于装备词条洗练的高级材料。',
    icon: '🌙',
    type: 'material',
    quality: 'rare',
    maxStack: 999,
    usable: false,
    buyPrice: 400,
    sellPrice: 160,
    sources: ['副本掉落'],
    materialSubType: 'reforge',
  },
  {
    id: 'item_lock_stone',
    name: '锁定石',
    description: '洗练时锁定一条词条不被改变。',
    icon: '🔒',
    type: 'material',
    quality: 'rare',
    maxStack: 99,
    usable: false,
    buyPrice: 300,
    sellPrice: 120,
    sources: ['商店', '副本掉落'],
    materialSubType: 'reforge',
  },

  // ===== 稀有材料 =====
  {
    id: 'item_dragon_scale',
    name: '龙鳞',
    description: '龙的鳞片，可用于打造强力装备。',
    icon: '🐉',
    type: 'material',
    quality: 'epic',
    maxStack: 99,
    usable: false,
    buyPrice: 500,
    sellPrice: 200,
    sources: ['副本掉落'],
    materialSubType: 'craft',
  },
  {
    id: 'item_dragon_blood',
    name: '龙血',
    description: '龙的血液，蕴含强大的力量。',
    icon: '🩸',
    type: 'material',
    quality: 'legendary',
    maxStack: 10,
    usable: false,
    buyPrice: 2000,
    sellPrice: 800,
    sources: ['Boss掉落'],
    materialSubType: 'craft',
  },
  {
    id: 'item_fairy_dust',
    name: '仙尘',
    description: '仙兽身上的尘埃，蕴含灵气。',
    icon: '✨',
    type: 'material',
    quality: 'epic',
    maxStack: 99,
    usable: false,
    buyPrice: 400,
    sellPrice: 160,
    sources: ['仙兽掉落'],
    materialSubType: 'craft',
  },
  {
    id: 'item_immortal_herb',
    name: '仙草',
    description: '传说中的仙草，可以炼制仙丹。',
    icon: '🌱',
    type: 'material',
    quality: 'legendary',
    maxStack: 10,
    usable: false,
    buyPrice: 1500,
    sellPrice: 600,
    sources: ['仙兽掉落', '采集'],
    materialSubType: 'craft',
  },
  {
    id: 'item_illusion_crystal',
    name: '幻晶',
    description: '狐妖身上的结晶，蕴含幻术之力。',
    icon: '💫',
    type: 'material',
    quality: 'epic',
    maxStack: 99,
    usable: false,
    buyPrice: 350,
    sellPrice: 140,
    sources: ['狐妖掉落'],
    materialSubType: 'craft',
  },
  {
    id: 'item_ghost_essence',
    name: '魂精',
    description: '游魂身上的精华，冰凉刺骨。',
    icon: '👻',
    type: 'material',
    quality: 'rare',
    maxStack: 99,
    usable: false,
    buyPrice: 150,
    sellPrice: 60,
    sources: ['游魂掉落'],
    materialSubType: 'craft',
  },
  {
    id: 'item_cursed_gem',
    name: '诅咒宝石',
    description: '被诅咒的宝石，散发着不祥的气息。',
    icon: '💀',
    type: 'material',
    quality: 'epic',
    maxStack: 99,
    usable: false,
    buyPrice: 400,
    sellPrice: 160,
    sources: ['骷髅战士掉落'],
    materialSubType: 'craft',
  },

  // ===== 副本门票 =====
  {
    id: 'item_ticket_spider_cave',
    name: '蛛穴通行证',
    description: '进入蜘蛛洞穴的通行证。',
    icon: '🎫',
    type: 'material',
    quality: 'rare',
    maxStack: 10,
    usable: false,
    buyPrice: 500,
    sellPrice: 200,
    sources: ['商店', '活动'],
    materialSubType: 'ticket',
  },
  {
    id: 'item_ticket_dayan_ta',
    name: '大雁塔令牌',
    description: '进入大雁塔挑战的令牌。',
    icon: '🏯',
    type: 'material',
    quality: 'epic',
    maxStack: 10,
    usable: false,
    buyPrice: 800,
    sellPrice: 320,
    sources: ['商店', '活动'],
    materialSubType: 'ticket',
  },
  {
    id: 'item_ticket_dragon_palace',
    name: '龙宫令牌',
    description: '进入东海龙宫的令牌。',
    icon: '🐲',
    type: 'material',
    quality: 'legendary',
    maxStack: 5,
    usable: false,
    buyPrice: 2000,
    sellPrice: 800,
    sources: ['活动', '商城'],
    materialSubType: 'ticket',
  },
];

/** 生成宝石模板 */
function generateGemTemplates(): ItemTemplate[] {
  const templates: ItemTemplate[] = [];
  const gemTypes = Object.keys(GEM_TYPE_CONFIG) as GemType[];
  const qualityByLevel: Record<number, 'common' | 'rare' | 'rare' | 'epic' | 'legendary'> = {
    1: 'common',
    2: 'rare',
    3: 'rare',
    4: 'rare',
    5: 'epic',
    6: 'epic',
    7: 'legendary',
    8: 'legendary',
    9: 'legendary',
    10: 'legendary',
  };

  for (const type of gemTypes) {
    const typeConfig = GEM_TYPE_CONFIG[type];
    for (const levelConfig of GEM_LEVEL_CONFIG) {
      const level = levelConfig.level;
      const quality = qualityByLevel[level] || 'common';
      const name = getGemName(type, level);
      const sellPrice = getGemSellPrice(level);

      templates.push({
        id: `gem_${type}_${level}`,
        name,
        description: typeConfig.description,
        icon: typeConfig.icon,
        type: 'gem',
        quality,
        maxStack: 99,
        usable: false,
        buyPrice: Math.floor(sellPrice * 2),
        sellPrice,
        sources: ['副本掉落', '合成', '商店'],
        gemType: type,
        gemLevel: level,
      });
    }
  }

  return templates;
}

/** 宝石模板（自动生成） */
export const GEM_TEMPLATES = generateGemTemplates();

/** 特殊物品模板 */
export const SPECIAL_TEMPLATES: ItemTemplate[] = [
  // 经验丹
  {
    id: 'item_exp_pill_small',
    name: '小经验丹',
    description: '使用后获得100点经验值。',
    icon: '🌟',
    type: 'special',
    quality: 'common',
    maxStack: 99,
    usable: true,
    effects: [{ type: 'add_exp', value: 100 }],
    useRequirements: { target: 'self' },
    buyPrice: 100,
    sellPrice: 40,
    sources: ['副本掉落', '活动'],
  },
  {
    id: 'item_exp_pill_medium',
    name: '中经验丹',
    description: '使用后获得500点经验值。',
    icon: '🌟',
    type: 'special',
    quality: 'rare',
    maxStack: 99,
    usable: true,
    effects: [{ type: 'add_exp', value: 500 }],
    useRequirements: { target: 'self' },
    buyPrice: 400,
    sellPrice: 160,
    sources: ['副本掉落', '活动'],
  },
  {
    id: 'item_exp_pill_large',
    name: '大经验丹',
    description: '使用后获得2000点经验值。',
    icon: '⭐',
    type: 'special',
    quality: 'epic',
    maxStack: 99,
    usable: true,
    effects: [{ type: 'add_exp', value: 2000 }],
    useRequirements: { minLevel: 10, target: 'self' },
    buyPrice: 1500,
    sellPrice: 600,
    sources: ['Boss掉落', '活动'],
  },
  {
    id: 'item_exp_pill_super',
    name: '超级经验丹',
    description: '使用后获得10000点经验值。',
    icon: '💫',
    type: 'special',
    quality: 'legendary',
    maxStack: 20,
    usable: true,
    effects: [{ type: 'add_exp', value: 10000 }],
    useRequirements: { minLevel: 20, target: 'self' },
    buyPrice: 5000,
    sellPrice: 2000,
    sources: ['活动', '商城'],
  },

  // 金币袋
  {
    id: 'item_gold_bag_small',
    name: '小金币袋',
    description: '打开后获得100-300金币。',
    icon: '💰',
    type: 'special',
    quality: 'common',
    maxStack: 99,
    usable: true,
    effects: [{ type: 'add_gold', value: 200 }],
    useRequirements: { target: 'self' },
    buyPrice: 0,
    sellPrice: 50,
    sources: ['副本掉落', '活动'],
  },
  {
    id: 'item_gold_bag_medium',
    name: '中金币袋',
    description: '打开后获得500-1000金币。',
    icon: '💰',
    type: 'special',
    quality: 'rare',
    maxStack: 99,
    usable: true,
    effects: [{ type: 'add_gold', value: 750 }],
    useRequirements: { target: 'self' },
    buyPrice: 0,
    sellPrice: 200,
    sources: ['副本掉落', '活动'],
  },
  {
    id: 'item_gold_bag_large',
    name: '大金币袋',
    description: '打开后获得2000-5000金币。',
    icon: '💎',
    type: 'special',
    quality: 'epic',
    maxStack: 20,
    usable: true,
    effects: [{ type: 'add_gold', value: 3500 }],
    useRequirements: { target: 'self' },
    buyPrice: 0,
    sellPrice: 500,
    sources: ['Boss掉落', '活动'],
  },
  {
    id: 'item_gold_bag_super',
    name: '超级金币袋',
    description: '打开后获得10000-20000金币。',
    icon: '👑',
    type: 'special',
    quality: 'legendary',
    maxStack: 10,
    usable: true,
    effects: [{ type: 'add_gold', value: 15000 }],
    useRequirements: { target: 'self' },
    buyPrice: 0,
    sellPrice: 1000,
    sources: ['活动', '商城'],
  },

  // 宝箱
  {
    id: 'item_treasure_box_bronze',
    name: '铜宝箱',
    description: '普通的宝箱，可能开出各种物品。',
    icon: '📦',
    type: 'special',
    quality: 'common',
    maxStack: 20,
    usable: true,
    effects: [{ type: 'open_box', boxItems: ['item_hp_potion_small', 'item_mp_potion_small', 'item_enhance_stone', 'item_gold'] }],
    useRequirements: { target: 'self' },
    buyPrice: 200,
    sellPrice: 80,
    sources: ['副本掉落', '活动'],
  },
  {
    id: 'item_treasure_box_silver',
    name: '银宝箱',
    description: '精致的宝箱，可能开出稀有物品。',
    icon: '🎁',
    type: 'special',
    quality: 'rare',
    maxStack: 20,
    usable: true,
    effects: [{ type: 'open_box', boxItems: ['item_hp_potion_medium', 'item_mp_potion_medium', 'item_enhance_stone_advanced', 'item_reforge_stone', 'gem_ruby_2'] }],
    useRequirements: { target: 'self' },
    buyPrice: 500,
    sellPrice: 200,
    sources: ['副本掉落', '活动'],
  },
  {
    id: 'item_treasure_box_gold',
    name: '金宝箱',
    description: '珍贵的宝箱，可能开出史诗物品。',
    icon: '🏆',
    type: 'special',
    quality: 'epic',
    maxStack: 10,
    usable: true,
    effects: [{ type: 'open_box', boxItems: ['item_hp_potion_large', 'item_mp_potion_large', 'item_enhance_stone_supreme', 'item_spirit_ball', 'gem_ruby_4'] }],
    useRequirements: { target: 'self' },
    buyPrice: 1500,
    sellPrice: 600,
    sources: ['Boss掉落', '活动'],
  },
  {
    id: 'item_treasure_box_legend',
    name: '传说宝箱',
    description: '传说级别的宝箱，可能开出传说物品。',
    icon: '🌟',
    type: 'special',
    quality: 'legendary',
    maxStack: 5,
    usable: true,
    effects: [{ type: 'open_box', boxItems: ['item_full_restore', 'item_spirit_ball_golden', 'item_exp_pill_super', 'gem_diamond_5', 'item_dragon_blood'] }],
    useRequirements: { target: 'self' },
    buyPrice: 5000,
    sellPrice: 2000,
    sources: ['活动', '商城'],
  },

  // 其他特殊物品
  {
    id: 'item_appearance_change',
    name: '易容丹',
    description: '使用后可以重新设置角色外观。',
    icon: '🎭',
    type: 'special',
    quality: 'rare',
    maxStack: 10,
    usable: true,
    buyPrice: 500,
    sellPrice: 200,
    sources: ['商城', '活动'],
  },
  {
    id: 'item_name_change',
    name: '改名卡',
    description: '使用后可以修改角色名称。',
    icon: '📝',
    type: 'special',
    quality: 'rare',
    maxStack: 10,
    usable: true,
    buyPrice: 500,
    sellPrice: 200,
    sources: ['商城', '活动'],
  },

  // ==================== 宠物打书系统道具 ====================
  // 技能格解锁道具
  {
    id: 'item_golden_dew',
    name: '金柳露',
    description: '神奇的露水，可以开启宠物的隐藏技能格。最多可开启第6-8个技能格。',
    icon: '💧',
    type: 'special',
    quality: 'rare',
    maxStack: 99,
    usable: true,
    buyPrice: 50000,
    sellPrice: 20000,
    sources: ['商城', '活动', '副本掉落'],
  },
  {
    id: 'item_immortal_dew',
    name: '仙露',
    description: '仙人采集的露水，可以开启宠物的潜能技能格。可开启第9-12个技能格。',
    icon: '✨',
    type: 'special',
    quality: 'legendary',
    maxStack: 99,
    usable: true,
    buyPrice: 200000,
    sellPrice: 80000,
    sources: ['商城', '高级副本掉落'],
  },

  // 技能锁定道具
  {
    id: 'item_lock_pearl',
    name: '锁妖珠',
    description: '可以将宠物技能锁定，打书时不会被覆盖。最多同时锁定3个技能。',
    icon: '🔮',
    type: 'special',
    quality: 'epic',
    maxStack: 99,
    usable: true,
    buyPrice: 30000,
    sellPrice: 12000,
    sources: ['商城', '副本掉落'],
  },

  // ==================== 低级兽诀 ====================
  {
    id: 'scroll_combo_strike',
    name: '连击兽诀',
    description: '攻击时有30%概率连续攻击2次，每次伤害降低25%。攻击型宠物专用。',
    icon: '⚔️',
    type: 'special',
    quality: 'rare',
    maxStack: 99,
    usable: true,
    buyPrice: 4000,
    sellPrice: 1600,
    sources: ['商城', '副本掉落'],
  },
  {
    id: 'scroll_fatal_blow',
    name: '必杀兽诀',
    description: '攻击时有10%概率造成2倍暴击伤害。攻击型宠物专用。',
    icon: '💥',
    type: 'special',
    quality: 'rare',
    maxStack: 99,
    usable: true,
    buyPrice: 4000,
    sellPrice: 1600,
    sources: ['商城', '副本掉落'],
  },
  {
    id: 'scroll_life_steal',
    name: '吸血兽诀',
    description: '攻击时恢复造成伤害的15%生命值。攻击型宠物专用。',
    icon: '🩸',
    type: 'special',
    quality: 'rare',
    maxStack: 99,
    usable: true,
    buyPrice: 5000,
    sellPrice: 2000,
    sources: ['商城', '副本掉落'],
  },
  {
    id: 'scroll_sneak_attack',
    name: '偷袭兽诀',
    description: '攻击时有20%概率无视目标30%防御。攻击型宠物专用。',
    icon: '🗡️',
    type: 'special',
    quality: 'rare',
    maxStack: 99,
    usable: true,
    buyPrice: 3500,
    sellPrice: 1400,
    sources: ['商城', '副本掉落'],
  },
  {
    id: 'scroll_pursuit',
    name: '追击兽诀',
    description: '击杀目标后，有30%概率追击另一个目标。攻击型宠物专用。',
    icon: '🏃',
    type: 'special',
    quality: 'rare',
    maxStack: 99,
    usable: true,
    buyPrice: 3500,
    sellPrice: 1400,
    sources: ['商城', '副本掉落'],
  },
  {
    id: 'scroll_defense',
    name: '防御兽诀',
    description: '永久提升防御力15%。防御型宠物专用。',
    icon: '🛡️',
    type: 'special',
    quality: 'rare',
    maxStack: 99,
    usable: true,
    buyPrice: 3000,
    sellPrice: 1200,
    sources: ['商城', '副本掉落'],
  },
  {
    id: 'scroll_parry',
    name: '招架兽诀',
    description: '被攻击时有20%概率格挡，减少40%伤害。防御型宠物专用。',
    icon: '🛡️',
    type: 'special',
    quality: 'rare',
    maxStack: 99,
    usable: true,
    buyPrice: 3000,
    sellPrice: 1200,
    sources: ['商城', '副本掉落'],
  },
  {
    id: 'scroll_counter',
    name: '反震兽诀',
    description: '被攻击时有25%概率反弹20%伤害给攻击者。防御型宠物专用。',
    icon: '💫',
    type: 'special',
    quality: 'rare',
    maxStack: 99,
    usable: true,
    buyPrice: 2500,
    sellPrice: 1000,
    sources: ['商城', '副本掉落'],
  },
  {
    id: 'scroll_god_bless',
    name: '神佑兽诀',
    description: '死亡时有20%概率复活，恢复30%生命值。',
    icon: '👼',
    type: 'special',
    quality: 'epic',
    maxStack: 99,
    usable: true,
    buyPrice: 5000,
    sellPrice: 2000,
    sources: ['商城', '高级副本掉落'],
  },
  {
    id: 'scroll_ghost',
    name: '鬼魂兽诀',
    description: '死亡后3回合复活，但对治疗技能免疫。',
    icon: '👻',
    type: 'special',
    quality: 'rare',
    maxStack: 99,
    usable: true,
    buyPrice: 3500,
    sellPrice: 1400,
    sources: ['商城', '副本掉落'],
  },
  {
    id: 'scroll_agility',
    name: '敏捷兽诀',
    description: '永久提升速度15%。',
    icon: '⚡',
    type: 'special',
    quality: 'rare',
    maxStack: 99,
    usable: true,
    buyPrice: 3500,
    sellPrice: 1400,
    sources: ['商城', '副本掉落'],
  },
  {
    id: 'scroll_detection',
    name: '感知兽诀',
    description: '可以攻击隐身状态的敌人。',
    icon: '👁️',
    type: 'special',
    quality: 'rare',
    maxStack: 99,
    usable: true,
    buyPrice: 3000,
    sellPrice: 1200,
    sources: ['商城', '副本掉落'],
  },
  {
    id: 'scroll_stealth',
    name: '隐身兽诀',
    description: '战斗开始时隐身2回合，无法被普通攻击选中。',
    icon: '🌙',
    type: 'special',
    quality: 'epic',
    maxStack: 99,
    usable: true,
    buyPrice: 5000,
    sellPrice: 2000,
    sources: ['商城', '高级副本掉落'],
  },
  {
    id: 'scroll_regeneration',
    name: '再生兽诀',
    description: '每回合恢复2%最大生命值。',
    icon: '💚',
    type: 'special',
    quality: 'rare',
    maxStack: 99,
    usable: true,
    buyPrice: 4500,
    sellPrice: 1800,
    sources: ['商城', '副本掉落'],
  },
  {
    id: 'scroll_magic_combo',
    name: '法术连击兽诀',
    description: '使用法术时有25%概率连续施放2次，第二次伤害降低50%。法术型宠物专用。',
    icon: '🔮',
    type: 'special',
    quality: 'rare',
    maxStack: 99,
    usable: true,
    buyPrice: 5000,
    sellPrice: 2000,
    sources: ['商城', '副本掉落'],
  },
  {
    id: 'scroll_magic_crit',
    name: '法术暴击兽诀',
    description: '法术攻击时有8%概率造成1.8倍伤害。法术型宠物专用。',
    icon: '✨',
    type: 'special',
    quality: 'rare',
    maxStack: 99,
    usable: true,
    buyPrice: 4500,
    sellPrice: 1800,
    sources: ['商城', '副本掉落'],
  },

  // ==================== 高级兽诀 ====================
  {
    id: 'scroll_advanced_combo',
    name: '高级连击兽诀',
    description: '攻击时有45%概率连续攻击2次，每次伤害降低15%。攻击型宠物专用，需30级。',
    icon: '⚔️',
    type: 'special',
    quality: 'epic',
    maxStack: 99,
    usable: true,
    buyPrice: 80000,
    sellPrice: 32000,
    sources: ['商城', '高级副本掉落'],
  },
  {
    id: 'scroll_advanced_fatal',
    name: '高级必杀兽诀',
    description: '攻击时有20%概率造成2.5倍暴击伤害。攻击型宠物专用，需30级。',
    icon: '💥',
    type: 'special',
    quality: 'epic',
    maxStack: 99,
    usable: true,
    buyPrice: 80000,
    sellPrice: 32000,
    sources: ['商城', '高级副本掉落'],
  },
  {
    id: 'scroll_advanced_life_steal',
    name: '高级吸血兽诀',
    description: '攻击时恢复造成伤害的25%生命值。攻击型宠物专用，需30级。',
    icon: '🩸',
    type: 'special',
    quality: 'epic',
    maxStack: 99,
    usable: true,
    buyPrice: 100000,
    sellPrice: 40000,
    sources: ['商城', '高级副本掉落'],
  },
  {
    id: 'scroll_rampage',
    name: '高级狂暴兽诀',
    description: '生命值低于40%时，攻击力提升50%。攻击型宠物专用，需40级。',
    icon: '🔥',
    type: 'special',
    quality: 'legendary',
    maxStack: 99,
    usable: true,
    buyPrice: 120000,
    sellPrice: 48000,
    sources: ['商城', 'Boss掉落'],
  },
  {
    id: 'scroll_advanced_defense',
    name: '高级防御兽诀',
    description: '永久提升防御力30%。防御型宠物专用，需30级。',
    icon: '🛡️',
    type: 'special',
    quality: 'epic',
    maxStack: 99,
    usable: true,
    buyPrice: 60000,
    sellPrice: 24000,
    sources: ['商城', '高级副本掉落'],
  },
  {
    id: 'scroll_advanced_god_bless',
    name: '高级神佑兽诀',
    description: '死亡时有40%概率复活，恢复50%生命值。需40级。',
    icon: '👼',
    type: 'special',
    quality: 'legendary',
    maxStack: 99,
    usable: true,
    buyPrice: 150000,
    sellPrice: 60000,
    sources: ['商城', 'Boss掉落'],
  },
  {
    id: 'scroll_advanced_agility',
    name: '高级敏捷兽诀',
    description: '永久提升速度30%。需30级。',
    icon: '⚡',
    type: 'special',
    quality: 'epic',
    maxStack: 99,
    usable: true,
    buyPrice: 70000,
    sellPrice: 28000,
    sources: ['商城', '高级副本掉落'],
  },
  {
    id: 'scroll_advanced_stealth',
    name: '高级隐身兽诀',
    description: '战斗开始时隐身3回合，隐身期间攻击力提升20%。需40级。',
    icon: '🌙',
    type: 'special',
    quality: 'legendary',
    maxStack: 99,
    usable: true,
    buyPrice: 130000,
    sellPrice: 52000,
    sources: ['商城', 'Boss掉落'],
  },
  {
    id: 'scroll_healing_aura',
    name: '高级治愈兽诀',
    description: '每回合恢复全体友方3%最大生命值。需35级。',
    icon: '💚',
    type: 'special',
    quality: 'epic',
    maxStack: 99,
    usable: true,
    buyPrice: 100000,
    sellPrice: 40000,
    sources: ['商城', '高级副本掉落'],
  },
  {
    id: 'scroll_advanced_magic_combo',
    name: '高级法术连击兽诀',
    description: '使用法术时有40%概率连续施放2次，第二次伤害降低30%。法术型宠物专用，需30级。',
    icon: '🔮',
    type: 'special',
    quality: 'epic',
    maxStack: 99,
    usable: true,
    buyPrice: 90000,
    sellPrice: 36000,
    sources: ['商城', '高级副本掉落'],
  },
  {
    id: 'scroll_magic_power',
    name: '魔之心兽诀',
    description: '永久提升法术攻击力25%。法术型宠物专用，需40级。',
    icon: '💜',
    type: 'special',
    quality: 'legendary',
    maxStack: 99,
    usable: true,
    buyPrice: 120000,
    sellPrice: 48000,
    sources: ['商城', 'Boss掉落'],
  },
];

/** 常见掉落物品（用于敌人掉落表） */
export const COMMON_DROP_ITEMS: ItemTemplate[] = [
  {
    id: 'item_tusk',
    name: '獠牙',
    description: '野猪的獠牙，锋利无比。',
    icon: '🦷',
    type: 'material',
    quality: 'common',
    maxStack: 999,
    usable: false,
    buyPrice: 25,
    sellPrice: 10,
    sources: ['野猪掉落'],
    materialSubType: 'craft',
  },
  {
    id: 'item_banana',
    name: '香蕉',
    description: '猕猴喜欢的食物。',
    icon: '🍌',
    type: 'material',
    quality: 'common',
    maxStack: 999,
    usable: false,
    buyPrice: 10,
    sellPrice: 4,
    sources: ['猕猴掉落'],
    materialSubType: 'general',
  },
  {
    id: 'item_snake_skin',
    name: '蛇皮',
    description: '竹叶青的皮，可以入药。',
    icon: '🐍',
    type: 'material',
    quality: 'rare',
    maxStack: 999,
    usable: false,
    buyPrice: 40,
    sellPrice: 16,
    sources: ['蛇类怪物掉落'],
    materialSubType: 'craft',
  },
  {
    id: 'item_bat_wing',
    name: '蝙蝠翅膀',
    description: '蝙蝠的翅膀，可以用于制作。',
    icon: '🦇',
    type: 'material',
    quality: 'common',
    maxStack: 999,
    usable: false,
    buyPrice: 20,
    sellPrice: 8,
    sources: ['蝙蝠掉落'],
    materialSubType: 'craft',
  },
  {
    id: 'item_crab_shell',
    name: '蟹壳',
    description: '坚硬的蟹壳，可以用于制作护甲。',
    icon: '🦀',
    type: 'material',
    quality: 'common',
    maxStack: 999,
    usable: false,
    buyPrice: 15,
    sellPrice: 6,
    sources: ['螃蟹掉落'],
    materialSubType: 'craft',
  },
  {
    id: 'item_dog_fang',
    name: '犬齿',
    description: '野狗的牙齿。',
    icon: '🐕',
    type: 'material',
    quality: 'common',
    maxStack: 999,
    usable: false,
    buyPrice: 18,
    sellPrice: 7,
    sources: ['野狗掉落'],
    materialSubType: 'craft',
  },
  {
    id: 'item_fox_fur',
    name: '狐皮',
    description: '狐狸的皮毛，柔软保暖。',
    icon: '🦊',
    type: 'material',
    quality: 'rare',
    maxStack: 999,
    usable: false,
    buyPrice: 50,
    sellPrice: 20,
    sources: ['狐狸掉落'],
    materialSubType: 'craft',
  },
  {
    id: 'item_deer_antler',
    name: '鹿角',
    description: '灵鹿的角，是珍贵的药材。',
    icon: '🦌',
    type: 'material',
    quality: 'rare',
    maxStack: 99,
    usable: false,
    buyPrice: 150,
    sellPrice: 60,
    sources: ['灵鹿掉落'],
    materialSubType: 'craft',
  },
  {
    id: 'item_fish_scale',
    name: '鱼鳞',
    description: '鱼人的鳞片。',
    icon: '🐟',
    type: 'material',
    quality: 'common',
    maxStack: 999,
    usable: false,
    buyPrice: 25,
    sellPrice: 10,
    sources: ['鱼人掉落'],
    materialSubType: 'craft',
  },
  {
    id: 'item_bandit_badge_mat',
    name: '山贼徽章',
    description: '山贼的身份标识。',
    icon: '🗡️',
    type: 'material',
    quality: 'rare',
    maxStack: 999,
    usable: false,
    buyPrice: 40,
    sellPrice: 16,
    sources: ['山贼掉落'],
    materialSubType: 'general',
  },
  {
    id: 'item_gold',
    name: '金币',
    description: '闪闪发光的金币。',
    icon: '🪙',
    type: 'material',
    quality: 'common',
    maxStack: 9999,
    usable: false,
    buyPrice: 1,
    sellPrice: 1,
    sources: ['怪物掉落', '任务奖励'],
    materialSubType: 'general',
  },
  {
    id: 'item_tiger_fur',
    name: '虎皮',
    description: '老虎的皮毛，非常珍贵。',
    icon: '🐯',
    type: 'material',
    quality: 'rare',
    maxStack: 99,
    usable: false,
    buyPrice: 200,
    sellPrice: 80,
    sources: ['老虎掉落'],
    materialSubType: 'craft',
  },
  {
    id: 'item_tiger_bone',
    name: '虎骨',
    description: '老虎的骨头，是珍贵的药材。',
    icon: '🦴',
    type: 'material',
    quality: 'rare',
    maxStack: 99,
    usable: false,
    buyPrice: 250,
    sellPrice: 100,
    sources: ['老虎掉落'],
    materialSubType: 'craft',
  },
  {
    id: 'item_fox_pearl',
    name: '狐珠',
    description: '狐妖体内的珠子，蕴含灵气。',
    icon: '🦪',
    type: 'material',
    quality: 'epic',
    maxStack: 10,
    usable: false,
    buyPrice: 500,
    sellPrice: 200,
    sources: ['狐妖掉落'],
    materialSubType: 'craft',
  },
  {
    id: 'item_golden_fur',
    name: '金毛',
    description: '美猴王的金色毛发。',
    icon: '✨',
    type: 'material',
    quality: 'legendary',
    maxStack: 10,
    usable: false,
    buyPrice: 1000,
    sellPrice: 400,
    sources: ['美猴王掉落'],
    materialSubType: 'craft',
  },
  {
    id: 'item_water_gem',
    name: '水灵石',
    description: '蕴含水元素之力的宝石。',
    icon: '💧',
    type: 'material',
    quality: 'rare',
    maxStack: 99,
    usable: false,
    buyPrice: 200,
    sellPrice: 80,
    sources: ['水妖掉落'],
    materialSubType: 'craft',
  },
  {
    id: 'item_sea_gem',
    name: '海灵石',
    description: '海妖身上的宝石。',
    icon: '🌊',
    type: 'material',
    quality: 'rare',
    maxStack: 99,
    usable: false,
    buyPrice: 180,
    sellPrice: 72,
    sources: ['海妖掉落'],
    materialSubType: 'craft',
  },
  {
    id: 'item_mountain_essence',
    name: '山精元',
    description: '山精身上的精华。',
    icon: '🏔️',
    type: 'material',
    quality: 'rare',
    maxStack: 99,
    usable: false,
    buyPrice: 100,
    sellPrice: 40,
    sources: ['山精掉落'],
    materialSubType: 'craft',
  },
  {
    id: 'item_xiaofeng_essence',
    name: '晓风精华',
    description: '晓风留下的精华。',
    icon: '🍃',
    type: 'material',
    quality: 'legendary',
    maxStack: 10,
    usable: false,
    buyPrice: 1500,
    sellPrice: 600,
    sources: ['清风道长掉落'],
    materialSubType: 'craft',
  },
  {
    id: 'item_snake_pearl',
    name: '蛇珠',
    description: '蛇妖体内的珠子。',
    icon: '🐍',
    type: 'material',
    quality: 'epic',
    maxStack: 10,
    usable: false,
    buyPrice: 400,
    sellPrice: 160,
    sources: ['蛇妖掉落'],
    materialSubType: 'craft',
  },
  {
    id: 'item_spider_queen_gem',
    name: '蛛后宝石',
    description: '蛛后身上的珍贵宝石。',
    icon: '🕷️',
    type: 'material',
    quality: 'legendary',
    maxStack: 10,
    usable: false,
    buyPrice: 800,
    sellPrice: 320,
    sources: ['蛛后掉落'],
    materialSubType: 'craft',
  },
  {
    id: 'item_poison_essence',
    name: '毒精',
    description: '剧毒的精华。',
    icon: '☠️',
    type: 'material',
    quality: 'epic',
    maxStack: 20,
    usable: false,
    buyPrice: 300,
    sellPrice: 120,
    sources: ['蛛后掉落'],
    materialSubType: 'craft',
  },
  {
    id: 'item_nine_tails_essence',
    name: '九尾精华',
    description: '九尾妖狐的精华。',
    icon: '🦊',
    type: 'material',
    quality: 'legendary',
    maxStack: 5,
    usable: false,
    buyPrice: 2000,
    sellPrice: 800,
    sources: ['九尾妖狐掉落'],
    materialSubType: 'craft',
  },
];

/** 所有物品模板 */
export const ITEM_TEMPLATES: Record<string, ItemTemplate> = {};

// 初始化物品模板映射
[
  ...CONSUMABLE_TEMPLATES,
  ...QUEST_TEMPLATES,
  ...MATERIAL_TEMPLATES,
  ...GEM_TEMPLATES,
  ...SPECIAL_TEMPLATES,
  ...COMMON_DROP_ITEMS,
].forEach((template) => {
  ITEM_TEMPLATES[template.id] = template;
});

/** 获取物品模板 */
export function getItemTemplate(id: string): ItemTemplate | undefined {
  return ITEM_TEMPLATES[id];
}

/** 获取所有消耗品模板 */
export function getConsumableTemplates(): ItemTemplate[] {
  return CONSUMABLE_TEMPLATES;
}

/** 获取所有材料模板 */
export function getMaterialTemplates(): ItemTemplate[] {
  return MATERIAL_TEMPLATES;
}

/** 获取所有任务物品模板 */
export function getQuestItemTemplates(): ItemTemplate[] {
  return QUEST_TEMPLATES;
}

/** 获取所有宝石物品模板 */
export function getGemItemTemplates(): ItemTemplate[] {
  return GEM_TEMPLATES;
}

/** 获取所有特殊物品模板 */
export function getSpecialItemTemplates(): ItemTemplate[] {
  return SPECIAL_TEMPLATES;
}

/** 获取所有宝石模板 */
export function getGemTemplates(): ItemTemplate[] {
  return GEM_TEMPLATES;
}

/** 获取指定类型和等级的宝石模板 */
export function getGemTemplate(type: GemType, level: number): ItemTemplate | undefined {
  return ITEM_TEMPLATES[`gem_${type}_${level}`];
}

/** 获取指定类型的所有宝石模板 */
export function getGemTemplatesByType(type: GemType): ItemTemplate[] {
  return GEM_TEMPLATES.filter(t => t.gemType === type);
}

/** 获取指定等级的所有宝石模板 */
export function getGemTemplatesByLevel(level: number): ItemTemplate[] {
  return GEM_TEMPLATES.filter(t => t.gemLevel === level);
}

/** 按类型获取物品模板 */
export function getItemTemplatesByType(type: ItemTemplate['type']): ItemTemplate[] {
  switch (type) {
    case 'consumable':
      return CONSUMABLE_TEMPLATES;
    case 'quest':
      return QUEST_TEMPLATES;
    case 'material':
      return MATERIAL_TEMPLATES;
    case 'gem':
      return GEM_TEMPLATES;
    case 'special':
      return SPECIAL_TEMPLATES;
    default:
      return [];
  }
}

/** 获取指定任务相关的物品 */
export function getQuestItemsByQuestId(questId: string): ItemTemplate[] {
  return QUEST_TEMPLATES.filter(item => item.questId === questId);
}
