// 宠物配置数据 - 梦幻西游经典宠物

import type { PetTemplate, PetAptitude, Element } from '@/types';

/** 生成随机资质 */
function randomAptitude(prng: () => number): PetAptitude {
  return {
    attack: 0.8 + prng() * 0.7,
    defense: 0.8 + prng() * 0.7,
    magic: 0.8 + prng() * 0.7,
    speed: 0.8 + prng() * 0.7,
    hp: 0.8 + prng() * 0.7,
    mp: 0.8 + prng() * 0.7,
  };
}

// ==================== 0-15级 新手宠物 ====================

/** 新手区宠物 - 建邺城、东海湾 */
const NOVICE_PETS: PetTemplate[] = [
  {
    id: 'pet_sea_turtle',
    name: '大海龟',
    description: '东海湾常见的海龟，行动缓慢但防御力强',
    icon: '🐢',
    type: 'defense',
    baseRarity: 'common',
    element: 'water' as Element,
    baseStats: {
      physicalAttack: 18,
      physicalDefense: 48,
      magicAttack: 8,
      magicDefense: 38,
      speed: 8,
      maxHp: 350,
      maxMp: 40,
      critRate: 0.02,
      critDamage: 0.3,
      hitRate: 0.9,
      dodgeRate: 0.02,
      antiCritRate: 0,
      penetration: 0,
      lifeSteal: 0,
      reflect: 0,
      healBonus: 0,
      cooldownReduction: 0,
    },
    learnableSkills: ['pet_shell', 'pet_provoke', 'pet_iron_skin'],
    captureLocations: ['map_donghai_bay', 'map_jianye'],
  },
  {
    id: 'pet_giant_frog',
    name: '巨蛙',
    description: '体型巨大的青蛙，擅长跳跃攻击',
    icon: '🐸',
    type: 'attack',
    baseRarity: 'common',
    element: 'water' as Element,
    baseStats: {
      physicalAttack: 32,
      physicalDefense: 18,
      magicAttack: 12,
      magicDefense: 15,
      speed: 22,
      maxHp: 180,
      maxMp: 60,
      critRate: 0.06,
      critDamage: 0.4,
      hitRate: 0.92,
      dodgeRate: 0.05,
      antiCritRate: 0,
      penetration: 0,
      lifeSteal: 0,
      reflect: 0,
      healBonus: 0,
      cooldownReduction: 0,
    },
    learnableSkills: ['pet_bite', 'pet_jump', 'pet_fury'],
    captureLocations: ['map_donghai_bay', 'map_jianye'],
  },
  {
    id: 'pet_tree_monster',
    name: '树怪',
    description: '成精的老树，防御力不错',
    icon: '🌳',
    type: 'defense',
    baseRarity: 'common',
    element: 'wood' as Element,
    baseStats: {
      physicalAttack: 20,
      physicalDefense: 42,
      magicAttack: 15,
      magicDefense: 35,
      speed: 10,
      maxHp: 320,
      maxMp: 80,
      critRate: 0.03,
      critDamage: 0.35,
      hitRate: 0.9,
      dodgeRate: 0.02,
      antiCritRate: 0,
      penetration: 0,
      lifeSteal: 0,
      reflect: 0,
      healBonus: 0,
      cooldownReduction: 0,
    },
    learnableSkills: ['pet_root', 'pet_shell', 'pet_iron_skin'],
    captureLocations: ['map_jianye', 'map_forest_1'],
  },
  {
    id: 'pet_wild_boar',
    name: '野猪',
    description: '山林中的野猪，冲击力很强',
    icon: '🐗',
    type: 'attack',
    baseRarity: 'common',
    element: 'earth' as Element,
    baseStats: {
      physicalAttack: 35,
      physicalDefense: 25,
      magicAttack: 5,
      magicDefense: 18,
      speed: 15,
      maxHp: 280,
      maxMp: 40,
      critRate: 0.05,
      critDamage: 0.45,
      hitRate: 0.92,
      dodgeRate: 0.02,
      antiCritRate: 0,
      penetration: 0,
      lifeSteal: 0,
      reflect: 0,
      healBonus: 0,
      cooldownReduction: 0,
    },
    learnableSkills: ['pet_charge', 'pet_tough_skin', 'pet_fury'],
    captureLocations: ['map_jianye', 'map_changan_outskirts'],
  },
  {
    id: 'pet_sea_worm',
    name: '海毛虫',
    description: '东海湾的虫子，别看小，咬人很疼',
    icon: '🐛',
    type: 'attack',
    baseRarity: 'common',
    element: 'water' as Element,
    baseStats: {
      physicalAttack: 38,
      physicalDefense: 12,
      magicAttack: 8,
      magicDefense: 10,
      speed: 25,
      maxHp: 150,
      maxMp: 50,
      critRate: 0.08,
      critDamage: 0.5,
      hitRate: 0.93,
      dodgeRate: 0.06,
      antiCritRate: 0,
      penetration: 0,
      lifeSteal: 0,
      reflect: 0,
      healBonus: 0,
      cooldownReduction: 0,
    },
    learnableSkills: ['pet_bite', 'pet_poison', 'pet_fury'],
    captureLocations: ['map_donghai_bay'],
  },
];

/** 江南野外宠物 - 5-20级 */
const JIANGNAN_PETS: PetTemplate[] = [
  {
    id: 'pet_bandit',
    name: '强盗',
    description: '江南野外的强盗，攻击力不错',
    icon: '🗡️',
    type: 'attack',
    baseRarity: 'common',
    element: 'metal' as Element,
    baseStats: {
      physicalAttack: 42,
      physicalDefense: 20,
      magicAttack: 8,
      magicDefense: 15,
      speed: 22,
      maxHp: 240,
      maxMp: 55,
      critRate: 0.07,
      critDamage: 0.5,
      hitRate: 0.94,
      dodgeRate: 0.04,
      antiCritRate: 0,
      penetration: 0,
      lifeSteal: 0,
      reflect: 0,
      healBonus: 0,
      cooldownReduction: 0,
    },
    learnableSkills: ['pet_slash', 'pet_steal', 'pet_fury'],
    captureLocations: ['map_jiangnan', 'map_changan_outskirts'],
  },
  {
    id: 'pet_bat',
    name: '蝙蝠',
    description: '夜间出没的蝙蝠，速度很快',
    icon: '🦇',
    type: 'attack',
    baseRarity: 'common',
    element: 'wood' as Element,
    baseStats: {
      physicalAttack: 35,
      physicalDefense: 15,
      magicAttack: 20,
      magicDefense: 20,
      speed: 35,
      maxHp: 180,
      maxMp: 100,
      critRate: 0.08,
      critDamage: 0.45,
      hitRate: 0.95,
      dodgeRate: 0.08,
      antiCritRate: 0,
      penetration: 0,
      lifeSteal: 0,
      reflect: 0,
      healBonus: 0,
      cooldownReduction: 0,
    },
    learnableSkills: ['pet_bite', 'pet_suck_blood', 'pet_speed_up'],
    captureLocations: ['map_jiangnan', 'map_cave_1'],
  },
  {
    id: 'pet_mountain_bandit',
    name: '山贼',
    description: '占山为王的山贼，比强盗更强',
    icon: '🥷',
    type: 'attack',
    baseRarity: 'common',
    element: 'metal' as Element,
    baseStats: {
      physicalAttack: 48,
      physicalDefense: 25,
      magicAttack: 10,
      magicDefense: 18,
      speed: 20,
      maxHp: 280,
      maxMp: 60,
      critRate: 0.06,
      critDamage: 0.55,
      hitRate: 0.93,
      dodgeRate: 0.04,
      antiCritRate: 0,
      penetration: 0,
      lifeSteal: 0,
      reflect: 0,
      healBonus: 0,
      cooldownReduction: 0,
    },
    learnableSkills: ['pet_slash', 'pet_taunt', 'pet_crit_up'],
    captureLocations: ['map_jiangnan', 'map_mountain_1'],
  },
  {
    id: 'pet_skeleton',
    name: '骷髅',
    description: '大雁塔中的骷髅，不死的亡灵',
    icon: '💀',
    type: 'attack',
    baseRarity: 'common',
    element: 'earth' as Element,
    baseStats: {
      physicalAttack: 45,
      physicalDefense: 18,
      magicAttack: 25,
      magicDefense: 22,
      speed: 28,
      maxHp: 200,
      maxMp: 120,
      critRate: 0.07,
      critDamage: 0.5,
      hitRate: 0.94,
      dodgeRate: 0.05,
      antiCritRate: 0,
      penetration: 0,
      lifeSteal: 0,
      reflect: 0,
      healBonus: 0,
      cooldownReduction: 0,
    },
    learnableSkills: ['pet_bone_strike', 'pet_curse', 'pet_fear'],
    captureLocations: ['map_dayan_tower', 'map_cemetery'],
  },
  {
    id: 'pet_goat_head',
    name: '羊头怪',
    description: '长着羊头的怪物，会使用法术',
    icon: '🐐',
    type: 'magic',
    baseRarity: 'common',
    element: 'fire' as Element,
    baseStats: {
      physicalAttack: 22,
      physicalDefense: 18,
      magicAttack: 42,
      magicDefense: 28,
      speed: 20,
      maxHp: 220,
      maxMp: 150,
      critRate: 0.05,
      critDamage: 0.4,
      hitRate: 0.93,
      dodgeRate: 0.03,
      antiCritRate: 0,
      penetration: 0,
      lifeSteal: 0,
      reflect: 0,
      healBonus: 0,
      cooldownReduction: 0,
    },
    learnableSkills: ['pet_magic_missile', 'pet_fireball', 'pet_heal'],
    captureLocations: ['map_jiangnan', 'map_mountain_1'],
  },
];

// ==================== 15-35级 长安城周边宠物 ====================

/** 长安周边宠物 */
const CHANGAN_PETS: PetTemplate[] = [
  {
    id: 'pet_tiger',
    name: '老虎',
    description: '森林中的猛虎，百兽之王',
    icon: '🐯',
    type: 'attack',
    baseRarity: 'rare',
    element: 'metal' as Element,
    baseStats: {
      physicalAttack: 58,
      physicalDefense: 30,
      magicAttack: 12,
      magicDefense: 20,
      speed: 28,
      maxHp: 320,
      maxMp: 65,
      critRate: 0.1,
      critDamage: 0.6,
      hitRate: 0.95,
      dodgeRate: 0.04,
    },
    learnableSkills: ['pet_bite', 'pet_claw', 'pet_roar', 'pet_fury'],
    captureLocations: ['map_forest_2', 'map_mountain_2'],
  },
  {
    id: 'pet_black_bear',
    name: '黑熊',
    description: '森林中的黑熊，皮糙肉厚',
    icon: '🐻',
    type: 'defense',
    baseRarity: 'rare',
    element: 'earth' as Element,
    baseStats: {
      physicalAttack: 40,
      physicalDefense: 55,
      magicAttack: 8,
      magicDefense: 35,
      speed: 12,
      maxHp: 450,
      maxMp: 50,
      critRate: 0.03,
      critDamage: 0.35,
      hitRate: 0.9,
      dodgeRate: 0.02,
      antiCritRate: 0,
      penetration: 0,
      lifeSteal: 0,
      reflect: 0,
      healBonus: 0,
      cooldownReduction: 0,
    },
    learnableSkills: ['pet_taunt', 'pet_shell', 'pet_counter', 'pet_fury'],
    captureLocations: ['map_forest_2', 'map_mountain_1'],
  },
  {
    id: 'pet_flower_fairy',
    name: '花妖',
    description: '花丛中诞生的妖精，擅长法术',
    icon: '🌸',
    type: 'magic',
    baseRarity: 'rare',
    element: 'wood' as Element,
    baseStats: {
      physicalAttack: 15,
      physicalDefense: 18,
      magicAttack: 55,
      magicDefense: 38,
      speed: 30,
      maxHp: 200,
      maxMp: 220,
      critRate: 0.07,
      critDamage: 0.45,
      hitRate: 0.95,
      dodgeRate: 0.06,
      antiCritRate: 0,
      penetration: 0,
      lifeSteal: 0,
      reflect: 0,
      healBonus: 0,
      cooldownReduction: 0,
    },
    learnableSkills: ['pet_magic_missile', 'pet_heal', 'pet_ice_arrow', 'pet_charm'],
    captureLocations: ['map_flower_valley', 'map_fairy_spring'],
  },
  {
    id: 'pet_fox',
    name: '狐狸',
    description: '狡猾的狐狸，擅长迷惑敌人',
    icon: '🦊',
    type: 'control',
    baseRarity: 'rare',
    element: 'fire' as Element,
    baseStats: {
      physicalAttack: 35,
      physicalDefense: 22,
      magicAttack: 45,
      magicDefense: 35,
      speed: 35,
      maxHp: 240,
      maxMp: 180,
      critRate: 0.08,
      critDamage: 0.5,
      hitRate: 0.95,
      dodgeRate: 0.08,
      antiCritRate: 0,
      penetration: 0,
      lifeSteal: 0,
      reflect: 0,
      healBonus: 0,
      cooldownReduction: 0,
    },
    learnableSkills: ['pet_charm', 'pet_illusion', 'pet_fireball', 'pet_sleep'],
    captureLocations: ['map_fox_valley', 'map_fairy_spring'],
  },
  {
    id: 'pet_toad',
    name: '蛤蟆精',
    description: '成精的蛤蟆，会喷吐毒液',
    icon: '🐸',
    type: 'magic',
    baseRarity: 'rare',
    element: 'water' as Element,
    baseStats: {
      physicalAttack: 28,
      physicalDefense: 32,
      magicAttack: 52,
      magicDefense: 40,
      speed: 18,
      maxHp: 280,
      maxMp: 200,
      critRate: 0.05,
      critDamage: 0.4,
      hitRate: 0.93,
      dodgeRate: 0.03,
      antiCritRate: 0,
      penetration: 0,
      lifeSteal: 0,
      reflect: 0,
      healBonus: 0,
      cooldownReduction: 0,
    },
    learnableSkills: ['pet_poison', 'pet_acid', 'pet_heal', 'pet_web'],
    captureLocations: ['map_swamp', 'map_river'],
  },
];

/** 大雁塔宠物 - 20-40级 */
const TOWER_PETS: PetTemplate[] = [
  {
    id: 'pet_bull_head',
    name: '牛头',
    description: '地府的牛头，力大无穷',
    icon: '🐂',
    type: 'attack',
    baseRarity: 'rare',
    element: 'metal' as Element,
    baseStats: {
      physicalAttack: 65,
      physicalDefense: 38,
      magicAttack: 15,
      magicDefense: 25,
      speed: 22,
      maxHp: 380,
      maxMp: 80,
      critRate: 0.08,
      critDamage: 0.55,
      hitRate: 0.94,
      dodgeRate: 0.03,
      antiCritRate: 0,
      penetration: 0,
      lifeSteal: 0,
      reflect: 0,
      healBonus: 0,
      cooldownReduction: 0,
    },
    learnableSkills: ['pet_slash', 'pet_taunt', 'pet_fury', 'pet_crit_up'],
    captureLocations: ['map_dayan_tower', 'map_underworld'],
  },
  {
    id: 'pet_horse_face',
    name: '马面',
    description: '地府的马面，速度极快',
    icon: '🐴',
    type: 'attack',
    baseRarity: 'rare',
    element: 'fire' as Element,
    baseStats: {
      physicalAttack: 60,
      physicalDefense: 30,
      magicAttack: 20,
      magicDefense: 28,
      speed: 38,
      maxHp: 340,
      maxMp: 100,
      critRate: 0.1,
      critDamage: 0.6,
      hitRate: 0.95,
      dodgeRate: 0.05,
    },
    learnableSkills: ['pet_charge', 'pet_speed_up', 'pet_fury', 'pet_multi_strike'],
    captureLocations: ['map_dayan_tower', 'map_underworld'],
  },
  {
    id: 'pet_zombie',
    name: '僵尸',
    description: '不死的僵尸，力大皮厚',
    icon: '🧟',
    type: 'defense',
    baseRarity: 'rare',
    element: 'earth' as Element,
    baseStats: {
      physicalAttack: 45,
      physicalDefense: 52,
      magicAttack: 10,
      magicDefense: 30,
      speed: 12,
      maxHp: 500,
      maxMp: 40,
      critRate: 0.03,
      critDamage: 0.35,
      hitRate: 0.9,
      dodgeRate: 0.02,
      antiCritRate: 0,
      penetration: 0,
      lifeSteal: 0,
      reflect: 0,
      healBonus: 0,
      cooldownReduction: 0,
    },
    learnableSkills: ['pet_bite', 'pet_taunt', 'pet_counter', 'pet_curse'],
    captureLocations: ['map_cemetery', 'map_underworld'],
  },
  {
    id: 'pet_ghost',
    name: '幽灵',
    description: '飘荡的幽灵，难以捉摸',
    icon: '👻',
    type: 'magic',
    baseRarity: 'rare',
    element: 'water' as Element,
    baseStats: {
      physicalAttack: 20,
      physicalDefense: 25,
      magicAttack: 60,
      magicDefense: 45,
      speed: 35,
      maxHp: 260,
      maxMp: 250,
      critRate: 0.1,
      critDamage: 0.5,
      hitRate: 0.95,
      dodgeRate: 0.1,
      antiCritRate: 0,
      penetration: 0,
      lifeSteal: 0,
      reflect: 0,
      healBonus: 0,
      cooldownReduction: 0,
    },
    learnableSkills: ['pet_curse', 'pet_fear', 'pet_invisibility', 'pet_magic_boost'],
    captureLocations: ['map_cemetery', 'map_underworld'],
  },
];

// ==================== 35-55级 中级宠物 ====================

/** 普陀山/五庄观宠物 */
const PUTUO_PETS: PetTemplate[] = [
  {
    id: 'pet_thunder_bird',
    name: '雷鸟人',
    description: '能操控雷电的鸟人，法术强大',
    icon: '⚡',
    type: 'magic',
    baseRarity: 'epic',
    element: 'metal' as Element,
    baseStats: {
      physicalAttack: 25,
      physicalDefense: 28,
      magicAttack: 78,
      magicDefense: 48,
      speed: 42,
      maxHp: 320,
      maxMp: 280,
      critRate: 0.12,
      critDamage: 0.6,
      hitRate: 0.96,
      dodgeRate: 0.08,
      antiCritRate: 0,
      penetration: 0,
      lifeSteal: 0,
      reflect: 0,
      healBonus: 0,
      cooldownReduction: 0,
    },
    learnableSkills: ['pet_thunder_strike', 'pet_thunder_breath', 'pet_paralyze', 'pet_magic_boost'],
    captureLocations: ['map_putuo', 'map_wuzhuang'],
  },
  {
    id: 'pet_butterfly_fairy',
    name: '蝴蝶仙子',
    description: '美丽的蝴蝶仙子，擅长辅助',
    icon: '🦋',
    type: 'support',
    baseRarity: 'epic',
    element: 'wood' as Element,
    baseStats: {
      physicalAttack: 22,
      physicalDefense: 25,
      magicAttack: 55,
      magicDefense: 50,
      speed: 45,
      maxHp: 280,
      maxMp: 300,
      critRate: 0.08,
      critDamage: 0.45,
      hitRate: 0.96,
      dodgeRate: 0.12,
      antiCritRate: 0,
      penetration: 0,
      lifeSteal: 0,
      reflect: 0,
      healBonus: 0,
      cooldownReduction: 0,
    },
    learnableSkills: ['pet_heal', 'pet_buff', 'pet_cleanse', 'pet_charm'],
    captureLocations: ['map_flower_valley', 'map_fairy_spring'],
  },
  {
    id: 'pet_ancient_beast',
    name: '古代瑞兽',
    description: '上古遗留下来的瑞兽，能力全面',
    icon: '🦁',
    type: 'attack',
    baseRarity: 'epic',
    element: 'fire' as Element,
    baseStats: {
      physicalAttack: 75,
      physicalDefense: 45,
      magicAttack: 40,
      magicDefense: 40,
      speed: 35,
      maxHp: 480,
      maxMp: 150,
      critRate: 0.1,
      critDamage: 0.65,
      hitRate: 0.95,
      dodgeRate: 0.05,
    },
    learnableSkills: ['pet_king_roar', 'pet_fury_claw', 'pet_brave', 'pet_crit_up'],
    captureLocations: ['map_wuzhuang', 'map_celestial'],
  },
];

/** 北俱芦洲/龙窟宠物 */
const ADVANCED_PETS: PetTemplate[] = [
  {
    id: 'pet_white_bear',
    name: '白熊',
    description: '北方雪原的白熊，力大无穷',
    icon: '🐻‍❄️',
    type: 'attack',
    baseRarity: 'epic',
    element: 'water' as Element,
    baseStats: {
      physicalAttack: 82,
      physicalDefense: 50,
      magicAttack: 15,
      magicDefense: 35,
      speed: 22,
      maxHp: 550,
      maxMp: 80,
      critRate: 0.1,
      critDamage: 0.7,
      hitRate: 0.94,
      dodgeRate: 0.03,
      antiCritRate: 0,
      penetration: 0,
      lifeSteal: 0,
      reflect: 0,
      healBonus: 0,
      cooldownReduction: 0,
    },
    learnableSkills: ['pet_slash', 'pet_taunt', 'pet_fury', 'pet_iron_skin'],
    captureLocations: ['map_north_sea', 'map_snow_valley'],
  },
  {
    id: 'pet_black_demon',
    name: '黑山老妖',
    description: '修炼千年的老妖，法力深厚',
    icon: '👹',
    type: 'magic',
    baseRarity: 'epic',
    element: 'earth' as Element,
    baseStats: {
      physicalAttack: 30,
      physicalDefense: 35,
      magicAttack: 85,
      magicDefense: 55,
      speed: 30,
      maxHp: 400,
      maxMp: 350,
      critRate: 0.12,
      critDamage: 0.6,
      hitRate: 0.96,
      dodgeRate: 0.05,
    },
    learnableSkills: ['pet_dark_magic', 'pet_curse', 'pet_fear', 'pet_magic_boost'],
    captureLocations: ['map_black_mountain', 'map_demon_cave'],
  },
  {
    id: 'pet_heaven_guard',
    name: '天将',
    description: '天界的守卫，武艺高强',
    icon: '🛡️',
    type: 'attack',
    baseRarity: 'epic',
    element: 'metal' as Element,
    baseStats: {
      physicalAttack: 88,
      physicalDefense: 55,
      magicAttack: 25,
      magicDefense: 45,
      speed: 38,
      maxHp: 500,
      maxMp: 120,
      critRate: 0.12,
      critDamage: 0.7,
      hitRate: 0.96,
      dodgeRate: 0.06,
    },
    learnableSkills: ['pet_slash', 'pet_divine_strike', 'pet_brave', 'pet_crit_up'],
    captureLocations: ['map_heaven', 'map_celestial'],
  },
];

// ==================== 55-75级 高级宠物 ====================

/** 龙窟/凤巢宠物 */
const DRAGON_PHOENIX_PETS: PetTemplate[] = [
  {
    id: 'pet_dragon',
    name: '蛟龙',
    description: '修炼成精的蛟龙，拥有龙族血脉',
    icon: '🐉',
    type: 'magic',
    baseRarity: 'legendary',
    element: 'water' as Element,
    baseStats: {
      physicalAttack: 70,
      physicalDefense: 55,
      magicAttack: 110,
      magicDefense: 70,
      speed: 45,
      maxHp: 680,
      maxMp: 380,
      critRate: 0.15,
      critDamage: 0.8,
      hitRate: 0.97,
      dodgeRate: 0.08,
      antiCritRate: 0,
      penetration: 0,
      lifeSteal: 0,
      reflect: 0,
      healBonus: 0,
      cooldownReduction: 0,
    },
    learnableSkills: ['pet_dragon_breath', 'pet_ice_storm', 'pet_dragon_roar', 'pet_magic_boost'],
    captureLocations: ['map_dragon_cave', 'map_dragon_palace'],
    evolution: {
      targetId: 'pet_azure_dragon',
      level: 80,
      requirements: ['dragon_scale', 'dragon_pearl'],
    },
  },
  {
    id: 'pet_phoenix',
    name: '凤凰',
    description: '传说中的不死鸟，浴火重生',
    icon: '🔥',
    type: 'magic',
    baseRarity: 'legendary',
    element: 'fire' as Element,
    baseStats: {
      physicalAttack: 55,
      physicalDefense: 50,
      magicAttack: 125,
      magicDefense: 85,
      speed: 52,
      maxHp: 600,
      maxMp: 420,
      critRate: 0.18,
      critDamage: 0.9,
      hitRate: 0.98,
      dodgeRate: 0.1,
    },
    learnableSkills: ['pet_fire_storm', 'pet_rebirth', 'pet_phoenix_tears', 'pet_magic_boost'],
    captureLocations: ['map_phoenix_nest', 'map_fire_realm'],
    evolution: {
      targetId: 'pet_divine_phoenix',
      level: 80,
      requirements: ['phoenix_feather', 'phoenix_heart'],
    },
  },
  {
    id: 'pet_vampire',
    name: '吸血鬼',
    description: '嗜血的吸血鬼，攻击可以恢复自身',
    icon: '🧛',
    type: 'attack',
    baseRarity: 'legendary',
    element: 'wood' as Element,
    baseStats: {
      physicalAttack: 120,
      physicalDefense: 45,
      magicAttack: 35,
      magicDefense: 50,
      speed: 55,
      maxHp: 650,
      maxMp: 200,
      critRate: 0.15,
      critDamage: 0.85,
      hitRate: 0.97,
      dodgeRate: 0.1,
    },
    learnableSkills: ['pet_suck_blood', 'pet_blood_fury', 'pet_dark_strike', 'pet_invisibility'],
    captureLocations: ['map_castle', 'map_dark_realm'],
  },
];

/** 地府/魔王寨宠物 */
const DEMON_PETS: PetTemplate[] = [
  {
    id: 'pet_hell_warrior',
    name: '地狱战神',
    description: '来自地狱的战神，力大无穷',
    icon: '😈',
    type: 'attack',
    baseRarity: 'legendary',
    element: 'fire' as Element,
    baseStats: {
      physicalAttack: 135,
      physicalDefense: 60,
      magicAttack: 30,
      magicDefense: 55,
      speed: 42,
      maxHp: 720,
      maxMp: 150,
      critRate: 0.15,
      critDamage: 0.9,
      hitRate: 0.97,
      dodgeRate: 0.06,
    },
    learnableSkills: ['pet_hell_strike', 'pet_fury', 'pet_brave', 'pet_crit_up'],
    captureLocations: ['map_underworld', 'map_hell'],
  },
  {
    id: 'pet_night_rakshasa',
    name: '夜罗刹',
    description: '夜间的罗刹女，速度极快',
    icon: '🌙',
    type: 'attack',
    baseRarity: 'legendary',
    element: 'water' as Element,
    baseStats: {
      physicalAttack: 115,
      physicalDefense: 40,
      magicAttack: 55,
      magicDefense: 60,
      speed: 65,
      maxHp: 580,
      maxMp: 280,
      critRate: 0.18,
      critDamage: 0.95,
      hitRate: 0.98,
      dodgeRate: 0.12,
      antiCritRate: 0,
      penetration: 0,
      lifeSteal: 0,
      reflect: 0,
      healBonus: 0,
      cooldownReduction: 0,
    },
    learnableSkills: ['pet_dance', 'pet_charm', 'pet_multi_strike', 'pet_speed_up'],
    captureLocations: ['map_demon_realm', 'map_dark_castle'],
  },
  {
    id: 'pet_spirit_nuwa',
    name: '灵符女娲',
    description: '女娲的后裔，精通符咒之术',
    icon: '🧝',
    type: 'magic',
    baseRarity: 'legendary',
    element: 'earth' as Element,
    baseStats: {
      physicalAttack: 40,
      physicalDefense: 55,
      magicAttack: 130,
      magicDefense: 90,
      speed: 48,
      maxHp: 620,
      maxMp: 450,
      critRate: 0.15,
      critDamage: 0.75,
      hitRate: 0.97,
      dodgeRate: 0.08,
      antiCritRate: 0,
      penetration: 0,
      lifeSteal: 0,
      reflect: 0,
      healBonus: 0,
      cooldownReduction: 0,
    },
    learnableSkills: ['pet_talisman', 'pet_heal', 'pet_buff', 'pet_resurrect'],
    captureLocations: ['map_nuwa_temple', 'map_celestial'],
  },
];

// ==================== 75+级 神兽/特殊宠物 ====================

/** 神兽宠物 */
const DIVINE_PETS: PetTemplate[] = [
  {
    id: 'pet_azure_dragon',
    name: '青龙',
    description: '四象神兽之一，东方守护神',
    icon: '🐲',
    type: 'magic',
    baseRarity: 'mythic',
    element: 'wood' as Element,
    baseStats: {
      physicalAttack: 100,
      physicalDefense: 90,
      magicAttack: 180,
      magicDefense: 110,
      speed: 70,
      maxHp: 1000,
      maxMp: 500,
      critRate: 0.2,
      critDamage: 1.1,
      hitRate: 0.99,
      dodgeRate: 0.12,
    },
    learnableSkills: ['pet_dragon_breath', 'pet_thunder_storm', 'pet_dragon_roar', 'pet_immortal'],
    captureLocations: ['map_celestial_palace'],
  },
  {
    id: 'pet_white_tiger',
    name: '白虎',
    description: '四象神兽之一，西方守护神',
    icon: '🐯',
    type: 'attack',
    baseRarity: 'mythic',
    element: 'metal' as Element,
    baseStats: {
      physicalAttack: 200,
      physicalDefense: 100,
      magicAttack: 50,
      magicDefense: 80,
      speed: 75,
      maxHp: 950,
      maxMp: 250,
      critRate: 0.22,
      critDamage: 1.2,
      hitRate: 0.99,
      dodgeRate: 0.1,
    },
    learnableSkills: ['pet_tiger_fury', 'pet_golden_claw', 'pet_brave', 'pet_king_roar'],
    captureLocations: ['map_celestial_palace'],
  },
  {
    id: 'pet_vermilion_bird',
    name: '朱雀',
    description: '四象神兽之一，南方守护神',
    icon: '🔥',
    type: 'magic',
    baseRarity: 'mythic',
    element: 'fire' as Element,
    baseStats: {
      physicalAttack: 70,
      physicalDefense: 80,
      magicAttack: 200,
      magicDefense: 130,
      speed: 80,
      maxHp: 850,
      maxMp: 600,
      critRate: 0.25,
      critDamage: 1.3,
      hitRate: 0.99,
      dodgeRate: 0.15,
    },
    learnableSkills: ['pet_nirvana_fire', 'pet_eternal_flame', 'pet_rebirth', 'pet_mass_resurrect'],
    captureLocations: ['map_celestial_palace'],
  },
  {
    id: 'pet_black_tortoise',
    name: '玄武',
    description: '四象神兽之一，北方守护神',
    icon: '🐢',
    type: 'defense',
    baseRarity: 'mythic',
    element: 'water' as Element,
    baseStats: {
      physicalAttack: 80,
      physicalDefense: 180,
      magicAttack: 60,
      magicDefense: 160,
      speed: 35,
      maxHp: 1500,
      maxMp: 350,
      critRate: 0.08,
      critDamage: 0.5,
      hitRate: 0.96,
      dodgeRate: 0.05,
    },
    learnableSkills: ['pet_iron_wall', 'pet_provoke', 'pet_counter', 'pet_immortal'],
    captureLocations: ['map_celestial_palace'],
  },
  {
    id: 'pet_divine_phoenix',
    name: '涅槃凤皇',
    description: '超越凤凰的存在，经历无数次涅槃',
    icon: '☀️',
    type: 'magic',
    baseRarity: 'mythic',
    element: 'fire' as Element,
    baseStats: {
      physicalAttack: 90,
      physicalDefense: 100,
      magicAttack: 220,
      magicDefense: 150,
      speed: 85,
      maxHp: 1000,
      maxMp: 700,
      critRate: 0.28,
      critDamage: 1.4,
      hitRate: 0.99,
      dodgeRate: 0.18,
    },
    learnableSkills: ['pet_nirvana_fire', 'pet_eternal_flame', 'pet_mass_resurrect', 'pet_divine_shield'],
    captureLocations: ['map_origin'],
  },
];

/** 超级神兽（特殊活动/合成获取） */
const SUPER_DIVINE_PETS: PetTemplate[] = [
  {
    id: 'pet_super_dog',
    name: '超级神狗',
    description: '传说中的超级神兽，忠心护主',
    icon: '🐕',
    type: 'attack',
    baseRarity: 'mythic',
    element: 'fire' as Element,
    baseStats: {
      physicalAttack: 250,
      physicalDefense: 120,
      magicAttack: 80,
      magicDefense: 100,
      speed: 90,
      maxHp: 1200,
      maxMp: 400,
      critRate: 0.25,
      critDamage: 1.5,
      hitRate: 0.99,
      dodgeRate: 0.15,
    },
    learnableSkills: ['pet_divine_bite', 'pet_heavenly_roar', 'pet_brave', 'pet_immortal'],
    captureLocations: [],  // 特殊活动获取
  },
  {
    id: 'pet_super_pig',
    name: '超级神猪',
    description: '传说中的超级神兽，福运加持',
    icon: '🐷',
    type: 'support',
    baseRarity: 'mythic',
    element: 'earth' as Element,
    baseStats: {
      physicalAttack: 100,
      physicalDefense: 150,
      magicAttack: 150,
      magicDefense: 180,
      speed: 60,
      maxHp: 1500,
      maxMp: 600,
      critRate: 0.15,
      critDamage: 0.8,
      hitRate: 0.98,
      dodgeRate: 0.1,
    },
    learnableSkills: ['pet_divine_heal', 'pet_blessing', 'pet_resurrect', 'pet_immortal'],
    captureLocations: [],  // 特殊活动获取
  },
  {
    id: 'pet_super_monkey',
    name: '超级神猴',
    description: '传说中的超级神兽，身手敏捷',
    icon: '🐵',
    type: 'attack',
    baseRarity: 'mythic',
    element: 'metal' as Element,
    baseStats: {
      physicalAttack: 230,
      physicalDefense: 90,
      magicAttack: 100,
      magicDefense: 110,
      speed: 120,
      maxHp: 1000,
      maxMp: 500,
      critRate: 0.3,
      critDamage: 1.6,
      hitRate: 0.99,
      dodgeRate: 0.25,
    },
    learnableSkills: ['pet_monkey_king', 'pet_multi_strike', 'pet_dodge', 'pet_immortal'],
    captureLocations: [],  // 特殊活动获取
  },
];

// ==================== 特殊/活动宠物 ====================

/** 节日活动宠物 */
const SPECIAL_PETS: PetTemplate[] = [
  {
    id: 'pet_snowman',
    name: '雪人',
    description: '冬日里诞生的雪人朋友',
    icon: '⛄',
    type: 'support',
    baseRarity: 'rare',
    element: 'water' as Element,
    baseStats: {
      physicalAttack: 22,
      physicalDefense: 40,
      magicAttack: 35,
      magicDefense: 45,
      speed: 15,
      maxHp: 320,
      maxMp: 200,
      critRate: 0.05,
      critDamage: 0.35,
      hitRate: 0.92,
      dodgeRate: 0.03,
    },
    learnableSkills: ['pet_snowball', 'pet_freeze', 'pet_heal'],
    captureLocations: ['event_winter'],
  },
  {
    id: 'pet_lantern_spirit',
    name: '灯笼怪',
    description: '元宵节出没的灯笼精灵',
    icon: '🏮',
    type: 'magic',
    baseRarity: 'rare',
    element: 'fire' as Element,
    baseStats: {
      physicalAttack: 18,
      physicalDefense: 25,
      magicAttack: 48,
      magicDefense: 38,
      speed: 32,
      maxHp: 240,
      maxMp: 220,
      critRate: 0.08,
      critDamage: 0.45,
      hitRate: 0.94,
      dodgeRate: 0.06,
    },
    learnableSkills: ['pet_fireball', 'pet_illuminate', 'pet_heal'],
    captureLocations: ['event_lantern'],
  },
];

/** 宠物模板列表 */
export const PET_TEMPLATES: Record<string, PetTemplate> = {
  // 新手宠物
  ...Object.fromEntries(NOVICE_PETS.map(p => [p.id, p])),
  // 江南野外
  ...Object.fromEntries(JIANGNAN_PETS.map(p => [p.id, p])),
  // 长安周边
  ...Object.fromEntries(CHANGAN_PETS.map(p => [p.id, p])),
  // 大雁塔
  ...Object.fromEntries(TOWER_PETS.map(p => [p.id, p])),
  // 普陀/五庄
  ...Object.fromEntries(PUTUO_PETS.map(p => [p.id, p])),
  // 高级区域
  ...Object.fromEntries(ADVANCED_PETS.map(p => [p.id, p])),
  // 龙/凤
  ...Object.fromEntries(DRAGON_PHOENIX_PETS.map(p => [p.id, p])),
  // 魔族
  ...Object.fromEntries(DEMON_PETS.map(p => [p.id, p])),
  // 四象神兽
  ...Object.fromEntries(DIVINE_PETS.map(p => [p.id, p])),
  // 超级神兽
  ...Object.fromEntries(SUPER_DIVINE_PETS.map(p => [p.id, p])),
  // 特殊宠物
  ...Object.fromEntries(SPECIAL_PETS.map(p => [p.id, p])),
};

/** 获取宠物模板 */
export function getPetTemplate(id: string): PetTemplate | undefined {
  return PET_TEMPLATES[id];
}

/** 获取所有宠物模板 */
export function getAllPetTemplates(): PetTemplate[] {
  return Object.values(PET_TEMPLATES);
}

/** 获取地图可捕捉的宠物 */
export function getCapturablePets(mapId: string): PetTemplate[] {
  return Object.values(PET_TEMPLATES).filter(t =>
    t.captureLocations.includes(mapId)
  );
}

/** 获取指定类型的宠物 */
export function getPetsByType(type: string): PetTemplate[] {
  return Object.values(PET_TEMPLATES).filter(t => t.type === type);
}

/** 获取指定品质的宠物 */
export function getPetsByRarity(rarity: string): PetTemplate[] {
  return Object.values(PET_TEMPLATES).filter(t => t.baseRarity === rarity);
}

/** 获取可进化的宠物 */
export function getEvolvablePets(): PetTemplate[] {
  return Object.values(PET_TEMPLATES).filter(t => t.evolution);
}

export { randomAptitude };
