// 技能配置数据 - 梦幻西游风格
// 每个门派6个技能，等级要求：1/15/30/45/60/75

import type { Skill } from '@/types';

export const SKILLS: Record<string, Skill> = {
  // ==================== 通用技能 ====================
  skill_attack: {
    id: 'skill_attack',
    name: '普通攻击',
    description: '对敌人进行普通攻击',
    icon: '👊',
    type: 'active',
    damageType: 'physical',
    factionId: null,
    levelRequirement: 1,
    rarity: 'common',
    targetType: 'single_enemy',
    element: 'none',
    mpCost: 0,
    cooldown: 0,
    effects: [{ type: 'damage', damageType: 'physical', multiplier: 1, description: '普通攻击' }],
    multiplier: 1,
  },
  skill_defend: {
    id: 'skill_defend',
    name: '防御',
    description: '进入防御姿态，本回合受到伤害减半',
    icon: '🛡️',
    type: 'active',
    damageType: 'physical',
    factionId: null,
    levelRequirement: 1,
    rarity: 'common',
    targetType: 'self',
    element: 'none',
    mpCost: 0,
    cooldown: 0,
    effects: [{ type: 'buff', stat: 'physicalDefense', value: 50, duration: 1, description: '防御+50%' }],
    multiplier: 0,
  },
  skill_escape: {
    id: 'skill_escape',
    name: '逃跑',
    description: '尝试逃离战斗',
    icon: '🏃',
    type: 'active',
    damageType: 'physical',
    factionId: null,
    levelRequirement: 1,
    rarity: 'common',
    targetType: 'self',
    element: 'none',
    mpCost: 0,
    cooldown: 0,
    effects: [{ type: 'buff', duration: 0, description: '逃跑' }],
    multiplier: 0,
  },

  // ==================== 大唐官府（物理爆发门派）====================
  // 特点：高物理伤害、连击、爆发
  skill_hengsao: {
    id: 'skill_hengsao',
    name: '横扫千军',
    description: '连续攻击敌方3次，每次造成75%伤害，使用后休息1回合',
    icon: '⚔️',
    type: 'active',
    damageType: 'physical',
    factionId: 'faction_datang',
    levelRequirement: 1,
    rarity: 'rare',
    targetType: 'single_enemy',
    element: 'none',
    mpCost: 35,
    cooldown: 2,
    effects: [
      { type: 'damage', damageType: 'physical', multiplier: 0.75, description: '横扫千军' },
    ],
    multiplier: 2.25,
    hitCount: 3,
  },
  skill_houfa: {
    id: 'skill_houfa',
    name: '后发制人',
    description: '进入防御姿态，下回合攻击力提升100%',
    icon: '🎯',
    type: 'active',
    damageType: 'physical',
    factionId: 'faction_datang',
    levelRequirement: 15,
    rarity: 'common',
    targetType: 'self',
    element: 'none',
    mpCost: 25,
    cooldown: 0,
    effects: [
      { type: 'buff', stat: 'physicalDefense', value: 30, duration: 1, description: '防御+30%' },
      { type: 'buff', stat: 'physicalAttack', value: 100, duration: 2, description: '攻击+100%' },
    ],
    multiplier: 0,
  },
  skill_pofu: {
    id: 'skill_pofu',
    name: '破釜沉舟',
    description: '牺牲10%最大生命值，造成280%伤害',
    icon: '💥',
    type: 'active',
    damageType: 'physical',
    factionId: 'faction_datang',
    levelRequirement: 30,
    rarity: 'epic',
    targetType: 'single_enemy',
    element: 'none',
    mpCost: 50,
    cooldown: 3,
    effects: [{ type: 'damage', damageType: 'physical', multiplier: 2.8, description: '破釜沉舟' }],
    multiplier: 2.8,
  },
  skill_qianli: {
    id: 'skill_qianli',
    name: '千里神行',
    description: '提升速度50%，持续3回合',
    icon: '🌬️',
    type: 'active',
    damageType: 'physical',
    factionId: 'faction_datang',
    levelRequirement: 45,
    rarity: 'rare',
    targetType: 'self',
    element: 'none',
    mpCost: 30,
    cooldown: 4,
    effects: [{ type: 'buff', stat: 'speed', value: 50, duration: 3, description: '速度+50%' }],
    multiplier: 0,
  },
  skill_jianyu: {
    id: 'skill_jianyu',
    name: '剑雨飘香',
    description: '剑气纵横，攻击全体敌人，造成60%伤害',
    icon: '🗡️',
    type: 'active',
    damageType: 'physical',
    factionId: 'faction_datang',
    levelRequirement: 60,
    rarity: 'rare',
    targetType: 'all_enemies',
    element: 'none',
    mpCost: 55,
    cooldown: 1,
    effects: [{ type: 'damage', damageType: 'physical', multiplier: 0.6, description: '剑雨飘香' }],
    multiplier: 0.6,
  },
  skill_tianxia: {
    id: 'skill_tianxia',
    name: '天下无双',
    description: '连续攻击5次，每次55%伤害，无视防御',
    icon: '👑',
    type: 'active',
    damageType: 'true',
    factionId: 'faction_datang',
    levelRequirement: 75,
    rarity: 'legendary',
    targetType: 'single_enemy',
    element: 'none',
    mpCost: 80,
    cooldown: 5,
    effects: [{ type: 'damage', damageType: 'true', multiplier: 0.55, description: '天下无双' }],
    multiplier: 2.75,
    hitCount: 5,
  },

  // ==================== 化生寺（治疗辅助门派）====================
  // 特点：强力治疗、复活、防御增益
  skill_jingang: {
    id: 'skill_jingang',
    name: '金刚护体',
    description: '提升物理防御50点，持续4回合',
    icon: '🛡️',
    type: 'active',
    damageType: 'magic',
    factionId: 'faction_huasheng',
    levelRequirement: 1,
    rarity: 'common',
    targetType: 'single_ally',
    element: 'none',
    mpCost: 25,
    cooldown: 0,
    effects: [{ type: 'buff', stat: 'physicalDefense', value: 50, duration: 4, description: '物理防御+50' }],
    multiplier: 0,
  },
  skill_tuiqi: {
    id: 'skill_tuiqi',
    name: '推气过宫',
    description: '恢复友方单位生命值，治疗量基于法攻',
    icon: '💚',
    type: 'active',
    damageType: 'magic',
    factionId: 'faction_huasheng',
    levelRequirement: 15,
    rarity: 'common',
    targetType: 'single_ally',
    element: 'none',
    mpCost: 30,
    cooldown: 0,
    effects: [{ type: 'heal', statScale: { stat: 'magicAttack', ratio: 1.5 }, multiplier: 1, description: '恢复生命' }],
    multiplier: 1,
  },
  skill_foci: {
    id: 'skill_foci',
    name: '我佛慈悲',
    description: '复活死亡的友方单位，恢复40%生命',
    icon: '🙏',
    type: 'active',
    damageType: 'magic',
    factionId: 'faction_huasheng',
    levelRequirement: 30,
    rarity: 'epic',
    targetType: 'dead_ally',
    element: 'none',
    mpCost: 100,
    cooldown: 6,
    effects: [{ type: 'heal', multiplier: 0.4, description: '复活并恢复40%生命' }],
    multiplier: 0.4,
  },
  skill_fofa: {
    id: 'skill_fofa',
    name: '佛法无边',
    description: '恢复全体友方生命值',
    icon: '✨',
    type: 'active',
    damageType: 'magic',
    factionId: 'faction_huasheng',
    levelRequirement: 45,
    rarity: 'rare',
    targetType: 'all_allies',
    element: 'none',
    mpCost: 70,
    cooldown: 2,
    effects: [{ type: 'heal', statScale: { stat: 'magicAttack', ratio: 1 }, multiplier: 0.8, description: '群体治疗' }],
    multiplier: 0.8,
  },
  skill_zhoutian: {
    id: 'skill_zhoutian',
    name: '小周天',
    description: '为友方单位恢复MP，并提升法攻20%',
    icon: '🔮',
    type: 'active',
    damageType: 'magic',
    factionId: 'faction_huasheng',
    levelRequirement: 60,
    rarity: 'rare',
    targetType: 'single_ally',
    element: 'none',
    mpCost: 60,
    cooldown: 3,
    effects: [
      { type: 'buff', stat: 'magicAttack', value: 20, duration: 3, description: '法攻+20%' },
    ],
    multiplier: 0,
  },
  skill_dabei: {
    id: 'skill_dabei',
    name: '大悲咒',
    description: '强力群体治疗，并清除所有负面状态',
    icon: '📿',
    type: 'active',
    damageType: 'magic',
    factionId: 'faction_huasheng',
    levelRequirement: 75,
    rarity: 'legendary',
    targetType: 'all_allies',
    element: 'none',
    mpCost: 120,
    cooldown: 5,
    effects: [{ type: 'heal', statScale: { stat: 'magicAttack', ratio: 1.5 }, multiplier: 1.2, description: '大悲咒' }],
    multiplier: 1.2,
  },

  // ==================== 方寸山（封印控制门派）====================
  // 特点：封印技能、控制敌人、雷系伤害
  skill_dingshen: {
    id: 'skill_dingshen',
    name: '定身符',
    description: '封印目标的物理攻击，持续2回合',
    icon: '📜',
    type: 'active',
    damageType: 'magic',
    factionId: 'faction_fangcun',
    levelRequirement: 1,
    rarity: 'rare',
    targetType: 'single_enemy',
    element: 'none',
    mpCost: 35,
    cooldown: 1,
    effects: [{ type: 'debuff', statusEffect: 'stun', duration: 2, description: '定身2回合' }],
    multiplier: 0,
  },
  skill_shixin: {
    id: 'skill_shixin',
    name: '失心符',
    description: '封印目标的法术技能，持续2回合',
    icon: '💫',
    type: 'active',
    damageType: 'magic',
    factionId: 'faction_fangcun',
    levelRequirement: 15,
    rarity: 'rare',
    targetType: 'single_enemy',
    element: 'none',
    mpCost: 40,
    cooldown: 1,
    effects: [{ type: 'debuff', statusEffect: 'silence', duration: 2, description: '沉默2回合' }],
    multiplier: 0,
  },
  skill_cuimian: {
    id: 'skill_cuimian',
    name: '催眠符',
    description: '使目标进入睡眠状态，持续3回合，受到伤害会醒来',
    icon: '😴',
    type: 'active',
    damageType: 'magic',
    factionId: 'faction_fangcun',
    levelRequirement: 30,
    rarity: 'epic',
    targetType: 'single_enemy',
    element: 'none',
    mpCost: 50,
    cooldown: 3,
    effects: [{ type: 'debuff', statusEffect: 'stun', duration: 3, description: '睡眠3回合' }],
    multiplier: 0,
  },
  skill_wulei: {
    id: 'skill_wulei',
    name: '五雷咒',
    description: '召唤雷电攻击敌人，造成雷系伤害',
    icon: '⚡',
    type: 'active',
    damageType: 'magic',
    factionId: 'faction_fangcun',
    levelRequirement: 45,
    rarity: 'rare',
    targetType: 'single_enemy',
    element: 'metal',
    mpCost: 40,
    cooldown: 0,
    effects: [{ type: 'damage', damageType: 'magic', element: 'metal', multiplier: 1.8, description: '雷系伤害' }],
    multiplier: 1.8,
  },
  skill_lingbo: {
    id: 'skill_lingbo',
    name: '凌波微步',
    description: '提升自身闪避30%，持续3回合',
    icon: '🌊',
    type: 'active',
    damageType: 'magic',
    factionId: 'faction_fangcun',
    levelRequirement: 60,
    rarity: 'rare',
    targetType: 'self',
    element: 'none',
    mpCost: 45,
    cooldown: 4,
    effects: [{ type: 'buff', stat: 'dodgeRate', value: 30, duration: 3, description: '闪避+30%' }],
    multiplier: 0,
  },
  skill_tianshu: {
    id: 'skill_tianshu',
    name: '天书奇谭',
    description: '封印全体敌人1回合',
    icon: '📖',
    type: 'active',
    damageType: 'magic',
    factionId: 'faction_fangcun',
    levelRequirement: 75,
    rarity: 'legendary',
    targetType: 'all_enemies',
    element: 'none',
    mpCost: 90,
    cooldown: 6,
    effects: [{ type: 'debuff', statusEffect: 'stun', duration: 1, description: '群体封印' }],
    multiplier: 0,
  },

  // ==================== 女儿村（速度暗器门派）====================
  // 特点：高速、暗器、封印
  skill_mantian: {
    id: 'skill_mantian',
    name: '漫天花雨',
    description: '向全体敌人投掷暗器，造成75%伤害',
    icon: '🌸',
    type: 'active',
    damageType: 'physical',
    factionId: 'faction_nver',
    levelRequirement: 1,
    rarity: 'rare',
    targetType: 'all_enemies',
    element: 'none',
    mpCost: 40,
    cooldown: 0,
    effects: [{ type: 'damage', damageType: 'physical', multiplier: 0.75, description: '群体暗器攻击' }],
    multiplier: 0.75,
  },
  skill_hansha: {
    id: 'skill_hansha',
    name: '含沙射影',
    description: '对单个敌人造成高伤害，并降低命中率',
    icon: '🗡️',
    type: 'active',
    damageType: 'physical',
    factionId: 'faction_nver',
    levelRequirement: 15,
    rarity: 'common',
    targetType: 'single_enemy',
    element: 'none',
    mpCost: 25,
    cooldown: 0,
    effects: [
      { type: 'damage', damageType: 'physical', multiplier: 1.6, description: '暗器突袭' },
      { type: 'debuff', stat: 'hitRate', value: -15, duration: 2, description: '命中-15%' },
    ],
    multiplier: 1.6,
  },
  skill_pingting: {
    id: 'skill_pingting',
    name: '娉婷嬝娜',
    description: '提升自身闪避25%和速度20%，持续3回合',
    icon: '💃',
    type: 'active',
    damageType: 'physical',
    factionId: 'faction_nver',
    levelRequirement: 30,
    rarity: 'rare',
    targetType: 'self',
    element: 'none',
    mpCost: 35,
    cooldown: 3,
    effects: [
      { type: 'buff', stat: 'dodgeRate', value: 25, duration: 3, description: '闪避+25%' },
      { type: 'buff', stat: 'speed', value: 20, duration: 3, description: '速度+20%' },
    ],
    multiplier: 0,
  },
  skill_yixiao: {
    id: 'skill_yixiao',
    name: '一笑倾城',
    description: '封印目标技能，持续2回合',
    icon: '😊',
    type: 'active',
    damageType: 'magic',
    factionId: 'faction_nver',
    levelRequirement: 45,
    rarity: 'epic',
    targetType: 'single_enemy',
    element: 'none',
    mpCost: 50,
    cooldown: 2,
    effects: [{ type: 'debuff', statusEffect: 'silence', duration: 2, description: '封印技能' }],
    multiplier: 0,
  },
  skill_rumeng: {
    id: 'skill_rumeng',
    name: '如梦令',
    description: '使目标睡眠2回合，并造成伤害',
    icon: '🌙',
    type: 'active',
    damageType: 'magic',
    factionId: 'faction_nver',
    levelRequirement: 60,
    rarity: 'rare',
    targetType: 'single_enemy',
    element: 'none',
    mpCost: 55,
    cooldown: 3,
    effects: [
      { type: 'damage', damageType: 'magic', multiplier: 1.0, description: '如梦令' },
      { type: 'debuff', statusEffect: 'stun', duration: 2, description: '睡眠2回合' },
    ],
    multiplier: 1.0,
  },
  skill_luohua: {
    id: 'skill_luohua',
    name: '落花有意',
    description: '连续投掷暗器4次，每次60%伤害',
    icon: '🌺',
    type: 'active',
    damageType: 'physical',
    factionId: 'faction_nver',
    levelRequirement: 75,
    rarity: 'legendary',
    targetType: 'single_enemy',
    element: 'none',
    mpCost: 70,
    cooldown: 4,
    effects: [{ type: 'damage', damageType: 'physical', multiplier: 0.6, description: '落花有意' }],
    multiplier: 2.4,
    hitCount: 4,
  },

  // ==================== 龙宫（法术群攻门派）====================
  // 特点：水系法术、群体伤害、法术穿透
  skill_longjuan: {
    id: 'skill_longjuan',
    name: '龙卷雨击',
    description: '召唤水龙攻击全体敌人，造成85%水系伤害',
    icon: '🐉',
    type: 'active',
    damageType: 'magic',
    factionId: 'faction_longgong',
    levelRequirement: 1,
    rarity: 'rare',
    targetType: 'all_enemies',
    element: 'water',
    mpCost: 45,
    cooldown: 0,
    effects: [{ type: 'damage', damageType: 'magic', element: 'water', multiplier: 0.85, description: '水系群攻' }],
    multiplier: 0.85,
  },
  skill_longteng: {
    id: 'skill_longteng',
    name: '龙腾',
    description: '召唤龙魂攻击单个敌人，造成200%水系伤害',
    icon: '🌊',
    type: 'active',
    damageType: 'magic',
    factionId: 'faction_longgong',
    levelRequirement: 15,
    rarity: 'common',
    targetType: 'single_enemy',
    element: 'water',
    mpCost: 35,
    cooldown: 0,
    effects: [{ type: 'damage', damageType: 'magic', element: 'water', multiplier: 2.0, description: '水系单体' }],
    multiplier: 2.0,
  },
  skill_longyin: {
    id: 'skill_longyin',
    name: '龙吟',
    description: '龙吟声降低敌方法术防御25点，并造成伤害',
    icon: '🐉',
    type: 'active',
    damageType: 'magic',
    factionId: 'faction_longgong',
    levelRequirement: 30,
    rarity: 'common',
    targetType: 'all_enemies',
    element: 'none',
    mpCost: 40,
    cooldown: 0,
    effects: [
      { type: 'damage', damageType: 'magic', multiplier: 0.5, description: '龙吟' },
      { type: 'debuff', stat: 'magicDefense', value: -25, duration: 3, description: '法防-25' },
    ],
    multiplier: 0.5,
  },
  skill_molang: {
    id: 'skill_molang',
    name: '魔浪滔天',
    description: '召唤滔天巨浪攻击全体敌人，造成130%水系伤害',
    icon: '🌊',
    type: 'active',
    damageType: 'magic',
    factionId: 'faction_longgong',
    levelRequirement: 45,
    rarity: 'epic',
    targetType: 'all_enemies',
    element: 'water',
    mpCost: 80,
    cooldown: 3,
    effects: [{ type: 'damage', damageType: 'magic', element: 'water', multiplier: 1.3, description: '强力水系群攻' }],
    multiplier: 1.3,
  },
  skill_bingpo: {
    id: 'skill_bingpo',
    name: '冰魄寒光',
    description: '攻击单体敌人，并使其冻结1回合',
    icon: '❄️',
    type: 'active',
    damageType: 'magic',
    factionId: 'faction_longgong',
    levelRequirement: 60,
    rarity: 'rare',
    targetType: 'single_enemy',
    element: 'water',
    mpCost: 60,
    cooldown: 2,
    effects: [
      { type: 'damage', damageType: 'magic', element: 'water', multiplier: 1.8, description: '冰魄寒光' },
      { type: 'debuff', statusEffect: 'stun', duration: 1, description: '冻结1回合' },
    ],
    multiplier: 1.8,
  },
  skill_shenlong: {
    id: 'skill_shenlong',
    name: '神龙摆尾',
    description: '召唤神龙之力，攻击全体敌人造成150%伤害',
    icon: '🐲',
    type: 'active',
    damageType: 'magic',
    factionId: 'faction_longgong',
    levelRequirement: 75,
    rarity: 'legendary',
    targetType: 'all_enemies',
    element: 'water',
    mpCost: 100,
    cooldown: 4,
    effects: [{ type: 'damage', damageType: 'magic', element: 'water', multiplier: 1.5, description: '神龙摆尾' }],
    multiplier: 1.5,
  },

  // ==================== 天宫（雷系爆发门派）====================
  // 特点：雷系法术、单体爆发、法防增益
  skill_tianlei: {
    id: 'skill_tianlei',
    name: '天雷斩',
    description: '召唤天雷攻击敌人，造成170%雷系伤害',
    icon: '⚡',
    type: 'active',
    damageType: 'magic',
    factionId: 'faction_tiangong',
    levelRequirement: 1,
    rarity: 'rare',
    targetType: 'single_enemy',
    element: 'metal',
    mpCost: 30,
    cooldown: 0,
    effects: [{ type: 'damage', damageType: 'magic', element: 'metal', multiplier: 1.7, description: '雷系单体' }],
    multiplier: 1.7,
  },
  skill_leiting: {
    id: 'skill_leiting',
    name: '雷霆万钧',
    description: '召唤雷霆攻击全体敌人，造成95%雷系伤害',
    icon: '🌩️',
    type: 'active',
    damageType: 'magic',
    factionId: 'faction_tiangong',
    levelRequirement: 15,
    rarity: 'rare',
    targetType: 'all_enemies',
    element: 'metal',
    mpCost: 55,
    cooldown: 0,
    effects: [{ type: 'damage', damageType: 'magic', element: 'metal', multiplier: 0.95, description: '雷系群攻' }],
    multiplier: 0.95,
  },
  skill_tianshen: {
    id: 'skill_tianshen',
    name: '天神护体',
    description: '提升法术防御50点，持续4回合',
    icon: '👼',
    type: 'active',
    damageType: 'magic',
    factionId: 'faction_tiangong',
    levelRequirement: 30,
    rarity: 'common',
    targetType: 'self',
    element: 'none',
    mpCost: 35,
    cooldown: 3,
    effects: [{ type: 'buff', stat: 'magicDefense', value: 50, duration: 4, description: '法防+50' }],
    multiplier: 0,
  },
  skill_zhangxin: {
    id: 'skill_zhangxin',
    name: '掌心雷',
    description: '凝聚雷气于掌心，造成250%雷系伤害',
    icon: '💥',
    type: 'active',
    damageType: 'magic',
    factionId: 'faction_tiangong',
    levelRequirement: 45,
    rarity: 'epic',
    targetType: 'single_enemy',
    element: 'metal',
    mpCost: 65,
    cooldown: 2,
    effects: [{ type: 'damage', damageType: 'magic', element: 'metal', multiplier: 2.5, description: '强力雷系单体' }],
    multiplier: 2.5,
  },
  skill_leiling: {
    id: 'skill_leiling',
    name: '雷灵附体',
    description: '提升法术攻击40%，持续3回合',
    icon: '⚡',
    type: 'active',
    damageType: 'magic',
    factionId: 'faction_tiangong',
    levelRequirement: 60,
    rarity: 'rare',
    targetType: 'self',
    element: 'none',
    mpCost: 50,
    cooldown: 4,
    effects: [{ type: 'buff', stat: 'magicAttack', value: 40, duration: 3, description: '法攻+40%' }],
    multiplier: 0,
  },
  skill_haotian: {
    id: 'skill_haotian',
    name: '昊天雷霆',
    description: '召唤天劫之力，攻击全体敌人造成140%雷系伤害',
    icon: '🌌',
    type: 'active',
    damageType: 'magic',
    factionId: 'faction_tiangong',
    levelRequirement: 75,
    rarity: 'legendary',
    targetType: 'all_enemies',
    element: 'metal',
    mpCost: 110,
    cooldown: 4,
    effects: [{ type: 'damage', damageType: 'magic', element: 'metal', multiplier: 1.4, description: '昊天雷霆' }],
    multiplier: 1.4,
  },

  // ==================== 普陀山（治疗复活门派）====================
  // 特点：持续治疗、复活、防御增益
  skill_yangliu: {
    id: 'skill_yangliu',
    name: '杨柳甘露',
    description: '恢复友方单位生命值，并附加持续恢复效果',
    icon: '🌿',
    type: 'active',
    damageType: 'magic',
    factionId: 'faction_putuo',
    levelRequirement: 1,
    rarity: 'common',
    targetType: 'single_ally',
    element: 'none',
    mpCost: 30,
    cooldown: 0,
    effects: [
      { type: 'heal', statScale: { stat: 'magicAttack', ratio: 1.2 }, multiplier: 1, description: '恢复生命' },
    ],
    multiplier: 1,
  },
  skill_pudu: {
    id: 'skill_pudu',
    name: '普度众生',
    description: '恢复全体友方生命值',
    icon: '🙏',
    type: 'active',
    damageType: 'magic',
    factionId: 'faction_putuo',
    levelRequirement: 15,
    rarity: 'rare',
    targetType: 'all_allies',
    element: 'none',
    mpCost: 55,
    cooldown: 1,
    effects: [{ type: 'heal', statScale: { stat: 'magicAttack', ratio: 0.8 }, multiplier: 0.7, description: '群体治疗' }],
    multiplier: 0.7,
  },
  skill_lianhua: {
    id: 'skill_lianhua',
    name: '莲花妙法',
    description: '提升全体友方物理和法术防御30点，持续3回合',
    icon: '🪷',
    type: 'active',
    damageType: 'magic',
    factionId: 'faction_putuo',
    levelRequirement: 30,
    rarity: 'rare',
    targetType: 'all_allies',
    element: 'none',
    mpCost: 50,
    cooldown: 3,
    effects: [
      { type: 'buff', stat: 'physicalDefense', value: 30, duration: 3, description: '物防+30' },
      { type: 'buff', stat: 'magicDefense', value: 30, duration: 3, description: '法防+30' },
    ],
    multiplier: 0,
  },
  skill_qisi: {
    id: 'skill_qisi',
    name: '起死回生',
    description: '复活死亡的友方单位，恢复60%生命',
    icon: '✨',
    type: 'active',
    damageType: 'magic',
    factionId: 'faction_putuo',
    levelRequirement: 45,
    rarity: 'epic',
    targetType: 'dead_ally',
    element: 'none',
    mpCost: 100,
    cooldown: 5,
    effects: [{ type: 'heal', multiplier: 0.6, description: '复活并恢复60%生命' }],
    multiplier: 0.6,
  },
  skill_cihang: {
    id: 'skill_cihang',
    name: '慈航普度',
    description: '为全体友方恢复生命，并附加2回合再生效果',
    icon: '🕊️',
    type: 'active',
    damageType: 'magic',
    factionId: 'faction_putuo',
    levelRequirement: 60,
    rarity: 'rare',
    targetType: 'all_allies',
    element: 'none',
    mpCost: 80,
    cooldown: 3,
    effects: [
      { type: 'heal', statScale: { stat: 'magicAttack', ratio: 1 }, multiplier: 0.9, description: '慈航普度' },
      { type: 'buff', statusEffect: 'regen', duration: 2, description: '再生2回合' },
    ],
    multiplier: 0.9,
  },
  skill_guanyin: {
    id: 'skill_guanyin',
    name: '观音咒',
    description: '复活全体死亡友方，并恢复40%生命',
    icon: '👸',
    type: 'active',
    damageType: 'magic',
    factionId: 'faction_putuo',
    levelRequirement: 75,
    rarity: 'legendary',
    targetType: 'all_allies',
    element: 'none',
    mpCost: 150,
    cooldown: 8,
    effects: [{ type: 'heal', multiplier: 0.4, description: '群体复活' }],
    multiplier: 0.4,
  },

  // ==================== 五庄观（封印输出门派）====================
  // 特点：封印、剑系攻击、自我恢复
  skill_riyue: {
    id: 'skill_riyue',
    name: '日月乾坤',
    description: '封印目标，使其无法行动2回合',
    icon: '🌙',
    type: 'active',
    damageType: 'magic',
    factionId: 'faction_wuzhuang',
    levelRequirement: 1,
    rarity: 'rare',
    targetType: 'single_enemy',
    element: 'none',
    mpCost: 40,
    cooldown: 1,
    effects: [{ type: 'debuff', statusEffect: 'stun', duration: 2, description: '封印2回合' }],
    multiplier: 0,
  },
  skill_yanyu: {
    id: 'skill_yanyu',
    name: '烟雨剑法',
    description: '剑气攻击敌人，造成160%物理伤害',
    icon: '🗡️',
    type: 'active',
    damageType: 'physical',
    factionId: 'faction_wuzhuang',
    levelRequirement: 15,
    rarity: 'common',
    targetType: 'single_enemy',
    element: 'none',
    mpCost: 25,
    cooldown: 0,
    effects: [{ type: 'damage', damageType: 'physical', multiplier: 1.6, description: '剑系伤害' }],
    multiplier: 1.6,
  },
  skill_minggui: {
    id: 'skill_minggui',
    name: '命归术',
    description: '恢复自身30%生命值',
    icon: '💚',
    type: 'active',
    damageType: 'magic',
    factionId: 'faction_wuzhuang',
    levelRequirement: 30,
    rarity: 'common',
    targetType: 'self',
    element: 'none',
    mpCost: 40,
    cooldown: 0,
    effects: [{ type: 'heal', multiplier: 0.3, description: '恢复自身生命' }],
    multiplier: 0.3,
  },
  skill_tiandi: {
    id: 'skill_tiandi',
    name: '天地同寿',
    description: '封印目标1回合，并造成100%伤害',
    icon: '☯️',
    type: 'active',
    damageType: 'magic',
    factionId: 'faction_wuzhuang',
    levelRequirement: 45,
    rarity: 'epic',
    targetType: 'single_enemy',
    element: 'none',
    mpCost: 55,
    cooldown: 2,
    effects: [
      { type: 'damage', damageType: 'magic', multiplier: 1.0, description: '造成伤害' },
      { type: 'debuff', statusEffect: 'stun', duration: 1, description: '封印1回合' },
    ],
    multiplier: 1.0,
  },
  skill_qixing: {
    id: 'skill_qixing',
    name: '七星剑诀',
    description: '连续攻击3次，每次70%伤害',
    icon: '⭐',
    type: 'active',
    damageType: 'physical',
    factionId: 'faction_wuzhuang',
    levelRequirement: 60,
    rarity: 'rare',
    targetType: 'single_enemy',
    element: 'none',
    mpCost: 60,
    cooldown: 2,
    effects: [{ type: 'damage', damageType: 'physical', multiplier: 0.7, description: '七星剑诀' }],
    multiplier: 2.1,
    hitCount: 3,
  },
  skill_tamiao: {
    id: 'skill_tamiao',
    name: '踏罡步斗',
    description: '提升全队速度30%，持续3回合',
    icon: '🌀',
    type: 'active',
    damageType: 'magic',
    factionId: 'faction_wuzhuang',
    levelRequirement: 75,
    rarity: 'legendary',
    targetType: 'all_allies',
    element: 'none',
    mpCost: 90,
    cooldown: 5,
    effects: [{ type: 'buff', stat: 'speed', value: 30, duration: 3, description: '速度+30%' }],
    multiplier: 0,
  },

  // ==================== 狮驼岭（变身物理门派）====================
  // 特点：变身、连击、群体物理
  skill_bianshen: {
    id: 'skill_bianshen',
    name: '变身',
    description: '变身为兽形，提升攻击60点，持续4回合',
    icon: '🦁',
    type: 'active',
    damageType: 'physical',
    factionId: 'faction_shituo',
    levelRequirement: 1,
    rarity: 'rare',
    targetType: 'self',
    element: 'none',
    mpCost: 35,
    cooldown: 0,
    effects: [{ type: 'buff', stat: 'physicalAttack', value: 60, duration: 4, description: '攻击+60' }],
    multiplier: 0,
  },
  skill_shibo: {
    id: 'skill_shibo',
    name: '狮搏',
    description: '狮爪猛击敌人，造成180%物理伤害',
    icon: '🐾',
    type: 'active',
    damageType: 'physical',
    factionId: 'faction_shituo',
    levelRequirement: 15,
    rarity: 'common',
    targetType: 'single_enemy',
    element: 'none',
    mpCost: 30,
    cooldown: 0,
    effects: [{ type: 'damage', damageType: 'physical', multiplier: 1.8, description: '狮爪攻击' }],
    multiplier: 1.8,
  },
  skill_xiangta: {
    id: 'skill_xiangta',
    name: '象踏',
    description: '巨象践踏全体敌人，造成85%物理伤害',
    icon: '🐘',
    type: 'active',
    damageType: 'physical',
    factionId: 'faction_shituo',
    levelRequirement: 30,
    rarity: 'rare',
    targetType: 'all_enemies',
    element: 'none',
    mpCost: 50,
    cooldown: 0,
    effects: [{ type: 'damage', damageType: 'physical', multiplier: 0.85, description: '群体物理伤害' }],
    multiplier: 0.85,
  },
  skill_yingji: {
    id: 'skill_yingji',
    name: '鹰击',
    description: '连续攻击5次，每次55%伤害',
    icon: '🦅',
    type: 'active',
    damageType: 'physical',
    factionId: 'faction_shituo',
    levelRequirement: 45,
    rarity: 'epic',
    targetType: 'single_enemy',
    element: 'none',
    mpCost: 65,
    cooldown: 3,
    effects: [{ type: 'damage', damageType: 'physical', multiplier: 0.55, description: '鹰击5连' }],
    multiplier: 2.75,
    hitCount: 5,
  },
  skill_zhenshan: {
    id: 'skill_zhenshan',
    name: '震山击',
    description: '猛击地面，攻击全体敌人并降低其防御',
    icon: '🏔️',
    type: 'active',
    damageType: 'physical',
    factionId: 'faction_shituo',
    levelRequirement: 60,
    rarity: 'rare',
    targetType: 'all_enemies',
    element: 'none',
    mpCost: 60,
    cooldown: 2,
    effects: [
      { type: 'damage', damageType: 'physical', multiplier: 0.9, description: '震山击' },
      { type: 'debuff', stat: 'physicalDefense', value: -20, duration: 2, description: '防御-20' },
    ],
    multiplier: 0.9,
  },
  skill_xiongshi: {
    id: 'skill_xiongshi',
    name: '雄狮怒吼',
    description: '咆哮震慑全场，攻击全体敌人造成120%伤害并眩晕1回合',
    icon: '🦁',
    type: 'active',
    damageType: 'physical',
    factionId: 'faction_shituo',
    levelRequirement: 75,
    rarity: 'legendary',
    targetType: 'all_enemies',
    element: 'none',
    mpCost: 100,
    cooldown: 5,
    effects: [
      { type: 'damage', damageType: 'physical', multiplier: 1.2, description: '雄狮怒吼' },
      { type: 'debuff', statusEffect: 'stun', duration: 1, description: '眩晕1回合' },
    ],
    multiplier: 1.2,
  },

  // ==================== 魔王寨（火系群攻门派）====================
  // 特点：火系法术、灼烧、法攻增益
  skill_feisha: {
    id: 'skill_feisha',
    name: '飞砂走石',
    description: '召唤飞砂攻击全体敌人，造成80%火系伤害并附加灼烧',
    icon: '🔥',
    type: 'active',
    damageType: 'magic',
    factionId: 'faction_mowang',
    levelRequirement: 1,
    rarity: 'rare',
    targetType: 'all_enemies',
    element: 'fire',
    mpCost: 50,
    cooldown: 0,
    effects: [
      { type: 'damage', damageType: 'magic', element: 'fire', multiplier: 0.8, description: '火系群攻' },
      { type: 'debuff', statusEffect: 'burn', duration: 2, description: '灼烧2回合' },
    ],
    multiplier: 0.8,
  },
  skill_sanmei: {
    id: 'skill_sanmei',
    name: '三昧真火',
    description: '召唤真火攻击敌人，造成200%火系伤害',
    icon: '🔥',
    type: 'active',
    damageType: 'magic',
    factionId: 'faction_mowang',
    levelRequirement: 15,
    rarity: 'rare',
    targetType: 'single_enemy',
    element: 'fire',
    mpCost: 40,
    cooldown: 0,
    effects: [{ type: 'damage', damageType: 'magic', element: 'fire', multiplier: 2.0, description: '火系单体' }],
    multiplier: 2.0,
  },
  skill_niujin: {
    id: 'skill_niujin',
    name: '牛劲',
    description: '提升法术攻击50点，持续3回合',
    icon: '🐂',
    type: 'active',
    damageType: 'magic',
    factionId: 'faction_mowang',
    levelRequirement: 30,
    rarity: 'common',
    targetType: 'self',
    element: 'none',
    mpCost: 35,
    cooldown: 3,
    effects: [{ type: 'buff', stat: 'magicAttack', value: 50, duration: 3, description: '法攻+50' }],
    multiplier: 0,
  },
  skill_liehuo: {
    id: 'skill_liehuo',
    name: '烈火燎原',
    description: '召唤烈火攻击全体敌人，造成110%火系伤害',
    icon: '☄️',
    type: 'active',
    damageType: 'magic',
    factionId: 'faction_mowang',
    levelRequirement: 45,
    rarity: 'epic',
    targetType: 'all_enemies',
    element: 'fire',
    mpCost: 75,
    cooldown: 2,
    effects: [{ type: 'damage', damageType: 'magic', element: 'fire', multiplier: 1.1, description: '强力火系群攻' }],
    multiplier: 1.1,
  },
  skill_huohai: {
    id: 'skill_huohai',
    name: '火海燎天',
    description: '召唤火海，攻击全体敌人造成伤害并附加3回合灼烧',
    icon: '🌋',
    type: 'active',
    damageType: 'magic',
    factionId: 'faction_mowang',
    levelRequirement: 60,
    rarity: 'rare',
    targetType: 'all_enemies',
    element: 'fire',
    mpCost: 85,
    cooldown: 3,
    effects: [
      { type: 'damage', damageType: 'magic', element: 'fire', multiplier: 1.0, description: '火海燎天' },
      { type: 'debuff', statusEffect: 'burn', duration: 3, description: '灼烧3回合' },
    ],
    multiplier: 1.0,
  },
  skill_moyan: {
    id: 'skill_moyan',
    name: '魔焰冲天',
    description: '释放魔王之力，攻击全体敌人造成140%火系伤害',
    icon: '👹',
    type: 'active',
    damageType: 'magic',
    factionId: 'faction_mowang',
    levelRequirement: 75,
    rarity: 'legendary',
    targetType: 'all_enemies',
    element: 'fire',
    mpCost: 110,
    cooldown: 4,
    effects: [{ type: 'damage', damageType: 'magic', element: 'fire', multiplier: 1.4, description: '魔焰冲天' }],
    multiplier: 1.4,
  },

  // ==================== 阴曹地府（固定伤害门派）====================
  // 特点：固定伤害、中毒、减益
  skill_yanluo: {
    id: 'skill_yanluo',
    name: '阎罗令',
    description: '造成固定伤害100点，并使目标中毒3回合',
    icon: '💀',
    type: 'active',
    damageType: 'fixed',
    factionId: 'faction_difu',
    levelRequirement: 1,
    rarity: 'common',
    targetType: 'single_enemy',
    element: 'none',
    mpCost: 30,
    cooldown: 0,
    effects: [
      { type: 'damage', damageType: 'fixed', baseValue: 100, description: '固定伤害' },
      { type: 'debuff', statusEffect: 'poison', duration: 3, description: '中毒3回合' },
    ],
    multiplier: 1,
  },
  skill_panguan: {
    id: 'skill_panguan',
    name: '判官令',
    description: '降低敌方防御30点并造成100%伤害',
    icon: '📜',
    type: 'active',
    damageType: 'magic',
    factionId: 'faction_difu',
    levelRequirement: 15,
    rarity: 'common',
    targetType: 'single_enemy',
    element: 'none',
    mpCost: 30,
    cooldown: 0,
    effects: [
      { type: 'damage', damageType: 'magic', multiplier: 1.0, description: '法术伤害' },
      { type: 'debuff', stat: 'physicalDefense', value: -30, duration: 2, description: '防御-30' },
    ],
    multiplier: 1.0,
  },
  skill_shifu: {
    id: 'skill_shifu',
    name: '尸腐毒',
    description: '使目标中毒4回合，每回合造成最大生命6%伤害',
    icon: '☠️',
    type: 'active',
    damageType: 'magic',
    factionId: 'faction_difu',
    levelRequirement: 30,
    rarity: 'rare',
    targetType: 'single_enemy',
    element: 'none',
    mpCost: 45,
    cooldown: 0,
    effects: [{ type: 'debuff', statusEffect: 'poison', duration: 4, description: '中毒4回合' }],
    multiplier: 0,
  },
  skill_guiyan: {
    id: 'skill_guiyan',
    name: '鬼眼',
    description: '降低敌方命中率20%，持续3回合',
    icon: '👁️',
    type: 'active',
    damageType: 'magic',
    factionId: 'faction_difu',
    levelRequirement: 45,
    rarity: 'common',
    targetType: 'all_enemies',
    element: 'none',
    mpCost: 40,
    cooldown: 2,
    effects: [{ type: 'debuff', stat: 'hitRate', value: -20, duration: 3, description: '命中-20%' }],
    multiplier: 0,
  },
  skill_yunhun: {
    id: 'skill_yunhun',
    name: '勾魂摄魄',
    description: '造成固定伤害150点，并吸取目标生命',
    icon: '👻',
    type: 'active',
    damageType: 'fixed',
    factionId: 'faction_difu',
    levelRequirement: 60,
    rarity: 'rare',
    targetType: 'single_enemy',
    element: 'none',
    mpCost: 55,
    cooldown: 1,
    effects: [
      { type: 'damage', damageType: 'fixed', baseValue: 150, description: '固定伤害' },
      { type: 'heal', multiplier: 0.5, description: '吸取生命' },
    ],
    multiplier: 1,
  },
  skill_huangquan: {
    id: 'skill_huangquan',
    name: '黄泉路引',
    description: '攻击全体敌人，造成固定伤害120点并使其中毒3回合',
    icon: '💀',
    type: 'active',
    damageType: 'fixed',
    factionId: 'faction_difu',
    levelRequirement: 75,
    rarity: 'legendary',
    targetType: 'all_enemies',
    element: 'none',
    mpCost: 90,
    cooldown: 4,
    effects: [
      { type: 'damage', damageType: 'fixed', baseValue: 120, description: '固定伤害' },
      { type: 'debuff', statusEffect: 'poison', duration: 3, description: '中毒3回合' },
    ],
    multiplier: 1,
  },

  // ==================== 盘丝洞（封印吸取门派）====================
  // 特点：封印、吸取MP、混乱
  skill_pansi: {
    id: 'skill_pansi',
    name: '盘丝阵',
    description: '封印目标物理攻击2回合',
    icon: '🕸️',
    type: 'active',
    damageType: 'magic',
    factionId: 'faction_pansi',
    levelRequirement: 1,
    rarity: 'rare',
    targetType: 'single_enemy',
    element: 'none',
    mpCost: 40,
    cooldown: 1,
    effects: [{ type: 'debuff', statusEffect: 'stun', duration: 2, description: '封印物理2回合' }],
    multiplier: 0,
  },
  skill_gouhun: {
    id: 'skill_gouhun',
    name: '勾魂',
    description: '吸取敌方MP，并造成100%伤害',
    icon: '👻',
    type: 'active',
    damageType: 'magic',
    factionId: 'faction_pansi',
    levelRequirement: 15,
    rarity: 'common',
    targetType: 'single_enemy',
    element: 'none',
    mpCost: 25,
    cooldown: 0,
    effects: [
      { type: 'damage', damageType: 'magic', multiplier: 1.0, description: '造成伤害' },
      { type: 'heal', stat: 'mp', multiplier: 0.3, description: '吸取MP' },
    ],
    multiplier: 1.0,
  },
  skill_meiyan: {
    id: 'skill_meiyan',
    name: '媚眼',
    description: '封印目标技能2回合',
    icon: '😍',
    type: 'active',
    damageType: 'magic',
    factionId: 'faction_pansi',
    levelRequirement: 30,
    rarity: 'rare',
    targetType: 'single_enemy',
    element: 'none',
    mpCost: 50,
    cooldown: 2,
    effects: [{ type: 'debuff', statusEffect: 'silence', duration: 2, description: '封印技能2回合' }],
    multiplier: 0,
  },
  skill_moyin: {
    id: 'skill_moyin',
    name: '魔音摄心',
    description: '使全体敌人混乱1回合',
    icon: '🎶',
    type: 'active',
    damageType: 'magic',
    factionId: 'faction_pansi',
    levelRequirement: 45,
    rarity: 'epic',
    targetType: 'all_enemies',
    element: 'none',
    mpCost: 70,
    cooldown: 4,
    effects: [{ type: 'debuff', statusEffect: 'stun', duration: 1, description: '群体混乱1回合' }],
    multiplier: 0,
  },
  skill_huamo: {
    id: 'skill_huamo',
    name: '画眉深浅',
    description: '降低敌方全体防御20点，持续2回合',
    icon: '💄',
    type: 'active',
    damageType: 'magic',
    factionId: 'faction_pansi',
    levelRequirement: 60,
    rarity: 'rare',
    targetType: 'all_enemies',
    element: 'none',
    mpCost: 55,
    cooldown: 2,
    effects: [{ type: 'debuff', stat: 'physicalDefense', value: -20, duration: 2, description: '防御-20' }],
    multiplier: 0,
  },
  skill_qianqiu: {
    id: 'skill_qianqiu',
    name: '千秋一梦',
    description: '封印全体敌人技能1回合，并造成伤害',
    icon: '🌙',
    type: 'active',
    damageType: 'magic',
    factionId: 'faction_pansi',
    levelRequirement: 75,
    rarity: 'legendary',
    targetType: 'all_enemies',
    element: 'none',
    mpCost: 100,
    cooldown: 5,
    effects: [
      { type: 'damage', damageType: 'magic', multiplier: 0.8, description: '千秋一梦' },
      { type: 'debuff', statusEffect: 'silence', duration: 1, description: '群体封印' },
    ],
    multiplier: 0.8,
  },

  // ==================== 敌人通用技能 ====================
  // 基础敌人攻击技能
  enemy_basic_attack: {
    id: 'enemy_basic_attack',
    name: '撕咬',
    description: '基础物理攻击',
    icon: '🐾',
    type: 'active',
    damageType: 'physical',
    factionId: null,
    levelRequirement: 1,
    rarity: 'common',
    targetType: 'single_enemy',
    element: 'none',
    mpCost: 0,
    cooldown: 0,
    effects: [{ type: 'damage', damageType: 'physical', multiplier: 1.0, description: '撕咬' }],
    multiplier: 1.0,
  },
  enemy_claw: {
    id: 'enemy_claw',
    name: '利爪',
    description: '用利爪攻击',
    icon: '🦅',
    type: 'active',
    damageType: 'physical',
    factionId: null,
    levelRequirement: 1,
    rarity: 'common',
    targetType: 'single_enemy',
    element: 'none',
    mpCost: 0,
    cooldown: 0,
    effects: [{ type: 'damage', damageType: 'physical', multiplier: 1.1, description: '利爪攻击' }],
    multiplier: 1.1,
  },
  enemy_venom_bite: {
    id: 'enemy_venom_bite',
    name: '毒牙',
    description: '带毒的撕咬，使目标中毒',
    icon: '🐍',
    type: 'active',
    damageType: 'physical',
    factionId: null,
    levelRequirement: 1,
    rarity: 'common',
    targetType: 'single_enemy',
    element: 'none',
    mpCost: 10,
    cooldown: 0,
    effects: [
      { type: 'damage', damageType: 'physical', multiplier: 0.8, description: '毒牙攻击' },
      { type: 'debuff', statusEffect: 'poison', duration: 2, description: '中毒2回合' },
    ],
    multiplier: 0.8,
  },
  enemy_charge: {
    id: 'enemy_charge',
    name: '冲撞',
    description: '猛烈冲撞敌人',
    icon: '🐂',
    type: 'active',
    damageType: 'physical',
    factionId: null,
    levelRequirement: 1,
    rarity: 'common',
    targetType: 'single_enemy',
    element: 'none',
    mpCost: 0,
    cooldown: 1,
    effects: [{ type: 'damage', damageType: 'physical', multiplier: 1.5, description: '冲撞' }],
    multiplier: 1.5,
  },
  enemy_web_shot: {
    id: 'enemy_web_shot',
    name: '蛛网',
    description: '喷射蛛网减速敌人',
    icon: '🕸️',
    type: 'active',
    damageType: 'magic',
    factionId: null,
    levelRequirement: 1,
    rarity: 'common',
    targetType: 'single_enemy',
    element: 'none',
    mpCost: 15,
    cooldown: 2,
    effects: [
      { type: 'damage', damageType: 'magic', multiplier: 0.6, description: '蛛网伤害' },
      { type: 'debuff', stat: 'speed', value: -20, duration: 2, description: '减速' },
    ],
    multiplier: 0.6,
  },
  enemy_ghost_touch: {
    id: 'enemy_ghost_touch',
    name: '鬼爪',
    description: '幽灵之爪，造成魔法伤害',
    icon: '👻',
    type: 'active',
    damageType: 'magic',
    factionId: null,
    levelRequirement: 1,
    rarity: 'common',
    targetType: 'single_enemy',
    element: 'none',
    mpCost: 10,
    cooldown: 0,
    effects: [{ type: 'damage', damageType: 'magic', multiplier: 1.0, description: '鬼爪' }],
    multiplier: 1.0,
  },
  enemy_fire_breath: {
    id: 'enemy_fire_breath',
    name: '火焰吐息',
    description: '喷吐火焰攻击',
    icon: '🔥',
    type: 'active',
    damageType: 'magic',
    factionId: null,
    levelRequirement: 1,
    rarity: 'common',
    targetType: 'single_enemy',
    element: 'fire',
    mpCost: 20,
    cooldown: 1,
    effects: [
      { type: 'damage', damageType: 'magic', element: 'fire', multiplier: 1.2, description: '火焰吐息' },
      { type: 'debuff', statusEffect: 'burn', duration: 2, description: '灼烧2回合' },
    ],
    multiplier: 1.2,
  },
  enemy_water_jet: {
    id: 'enemy_water_jet',
    name: '水流喷射',
    description: '喷射水流攻击',
    icon: '💦',
    type: 'active',
    damageType: 'magic',
    factionId: null,
    levelRequirement: 1,
    rarity: 'common',
    targetType: 'single_enemy',
    element: 'water',
    mpCost: 15,
    cooldown: 0,
    effects: [{ type: 'damage', damageType: 'magic', element: 'water', multiplier: 1.0, description: '水流喷射' }],
    multiplier: 1.0,
  },
  enemy_sonic_screech: {
    id: 'enemy_sonic_screech',
    name: '尖啸',
    description: '发出刺耳尖叫',
    icon: '📢',
    type: 'active',
    damageType: 'magic',
    factionId: null,
    levelRequirement: 1,
    rarity: 'common',
    targetType: 'all_enemies',
    element: 'none',
    mpCost: 25,
    cooldown: 2,
    effects: [{ type: 'damage', damageType: 'magic', multiplier: 0.5, description: '声波攻击' }],
    multiplier: 0.5,
  },
};

/** 获取技能配置 */
export function getSkill(id: string): Skill | undefined {
  return SKILLS[id];
}

/** 获取门派技能列表 */
export function getFactionSkills(factionId: string): Skill[] {
  return Object.values(SKILLS).filter(s => s.factionId === factionId);
}

/** 获取通用技能 */
export function getCommonSkills(): Skill[] {
  return Object.values(SKILLS).filter(s => s.factionId === null);
}

/** 获取可学习技能（按等级要求） */
export function getLearnableSkills(factionId: string, level: number): Skill[] {
  return Object.values(SKILLS).filter(
    s => s.factionId === factionId && s.levelRequirement <= level
  );
}
